// Generated by Suite Builder from a crawl of the site. Checks for IndustriesDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.industriesdetail.actions;

import net.atos.tests.pages.industriesdetail.IndustriesDetailPage;
import net.atos.tests.pages.industriesdetail.IndustriesDetailElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on IndustriesDetailPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class IndustriesDetailVerifyActions {
    private final Page page;

    public IndustriesDetailVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public IndustriesDetailVerifyActions isLoaded() {
        IndustriesDetailPage here = new IndustriesDetailPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public IndustriesDetailVerifyActions isThePageOf(String name) {
        Checks.isOnPath(page, UrlPaths.industriesDetail(name));
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public IndustriesDetailVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"How we make an impact\", \"Dive deeper\", \"Contact us for more information.\")",
                IndustriesDetailElements.HOW_WE_MAKE_AN_IMPACT_HEADING, IndustriesDetailElements.DIVE_DEEPER_HEADING, IndustriesDetailElements.CONTACT_US_FOR_MORE_INFORMATION_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(IndustriesDetailElements.SOME_HEADING)}. */
    public IndustriesDetailVerifyActions shows(IndustriesDetailElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public IndustriesDetailVerifyActions doesNotShow(IndustriesDetailElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public IndustriesDetailVerifyActions says(IndustriesDetailElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public IndustriesDetailVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public IndustriesDetailVerifyActions holds(IndustriesDetailElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public IndustriesDetailVerifyActions isEmpty(IndustriesDetailElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public IndustriesDetailVerifyActions refusesEmpty(IndustriesDetailElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public IndustriesDetailVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, IndustriesDetailElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
