// Generated by Suite Builder from a crawl of the site. Click actions for IndustriesDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.industriesdetail.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.ClientSuccessClientStoriesDetailPage;
import net.atos.tests.pages.industriesdetail.IndustriesDetailElements;
import net.atos.tests.pages.industriesdetail.IndustriesDetailPage;
import net.atos.tests.pages.lpatosthreatresearch.LpAtosThreatResearchPage;
import net.atos.tests.pages.lpdigitalsecuritymagazine.LpDigitalSecurityMagazinePage;
import net.atos.tests.pages.sitedetailpage8.SiteDetailPage8;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on IndustriesDetailPage. Clicks that change page return the next page; others return this. */
public class IndustriesDetailClickActions {
    private final Page page;

    public IndustriesDetailClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to SiteDetailPage8 (e.g. Read more) and waits for it. It opens in a new tab. */
    public SiteDetailPage8 goToSiteDetail8(String id, String name, String name2) {
        Page tab = UserActions.clickOpeningNewTab(page, IndustriesDetailElements.getSiteDetail8Link(id, name, name2));
        return new SiteDetailPage8(tab).get();
    }

    /** Clicks a link to ClientSuccessClientStoriesDetailPage (e.g. Read more >) and waits for it. It opens in a new tab. */
    public ClientSuccessClientStoriesDetailPage goToClientSuccessClientStoriesDetail(String name) {
        Page tab = UserActions.clickOpeningNewTab(page, IndustriesDetailElements.getClientSuccessClientStoriesDetailLink(name));
        return new ClientSuccessClientStoriesDetailPage(tab).get();
    }

    /** Clicks the link to LpDigitalSecurityMagazinePage (Learn more >) and waits for it. It opens in a new tab. */
    public LpDigitalSecurityMagazinePage goToLpDigitalSecurityMagazine() {
        Page tab = UserActions.clickOpeningNewTab(page, IndustriesDetailElements.LP_DIGITAL_SECURITY_MAGAZINE_LINK);
        return new LpDigitalSecurityMagazinePage(tab).get();
    }

    /** Clicks the link to LpAtosThreatResearchPage (Learn more >) and waits for it. It opens in a new tab. */
    public LpAtosThreatResearchPage goToLpAtosThreatResearch() {
        Page tab = UserActions.clickOpeningNewTab(page, IndustriesDetailElements.LP_ATOS_THREAT_RESEARCH_LINK);
        return new LpAtosThreatResearchPage(tab).get();
    }

    /** Clicks the button "previous arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage previousArrow() {
        UserActions.click(page, IndustriesDetailElements.PREVIOUS_ARROW_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "next arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage nextArrow() {
        UserActions.click(page, IndustriesDetailElements.NEXT_ARROW_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "DSm 19". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage dsm19() {
        UserActions.click(page, IndustriesDetailElements.DSM_19_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "Adaptive cyber resilience wp". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage adaptiveCyberResilienceWp() {
        UserActions.click(page, IndustriesDetailElements.ADAPTIVE_CYBER_RESILIENCE_WP_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "CYS main page". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage cysMainPage() {
        UserActions.click(page, IndustriesDetailElements.CYS_MAIN_PAGE_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "TRC". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage trc() {
        UserActions.click(page, IndustriesDetailElements.TRC_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "Previous slide (only for visual purpose, links already av...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage previousSlideOnlyForVisual() {
        UserActions.click(page, IndustriesDetailElements.PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "Next slide (only for visual purpose, links already availa...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage nextSlideOnlyForVisual() {
        UserActions.click(page, IndustriesDetailElements.NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "previous slide". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage previousSlide() {
        UserActions.click(page, IndustriesDetailElements.PREVIOUS_SLIDE_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "next slide". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage nextSlide() {
        UserActions.click(page, IndustriesDetailElements.NEXT_SLIDE_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "Solent NHS Trust". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage solentNhsTrust() {
        UserActions.click(page, IndustriesDetailElements.SOLENT_NHS_TRUST_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Clicks the button "CPI". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public IndustriesDetailPage cpi() {
        UserActions.click(page, IndustriesDetailElements.CPI_BUTTON);
        return new IndustriesDetailPage(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public IndustriesDetailVerifyActions verify() {
        return new IndustriesDetailVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public IndustriesDetailClickActions acceptTerms() {
    //     UserActions.click(page, IndustriesDetailElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
