// Generated by Suite Builder from a crawl of the site. The "Download the complementary full report to discover why Atos " form on LpDetailPage, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what LpDetailTasks.fillDownloadTheComplementaryFullReportToDiscoverWhyAtosForm takes.
package net.atos.tests.pages.lpdetail;

import net.atos.tests.core.SiteConfig;

/**
 * The "Download the complementary full report to discover why Atos " form on LpDetailPage, as one value: its fields in page order, what
 * {@link LpDetailTasks#fillDownloadTheComplementaryFullReportToDiscoverWhyAtosForm(DownloadTheComplementaryFullReportToDiscoverWhyAtos)} types and chooses. {@code sample()} gives values a test can
 * send; change one with a copy: {@code DownloadTheComplementaryFullReportToDiscoverWhyAtos.sample().withFirstName("...")}.
 */
public record DownloadTheComplementaryFullReportToDiscoverWhyAtos(String firstName, String lastName, String businessEmailAddress, String companyOrganisationName, String jobTitle) {

    /**
     * Values any copy of the site takes, each plausible for its field; one can be set for a run on the
     * command line (-DfirstName=...) or in suite.properties, by its name.
     */
    public static DownloadTheComplementaryFullReportToDiscoverWhyAtos sample() {
        return new DownloadTheComplementaryFullReportToDiscoverWhyAtos(
                SiteConfig.value("firstName", "Test *First Name:"),
                SiteConfig.value("lastName", "Test *Last Name:"),
                SiteConfig.value("businessEmailAddress", "test@example.com"),
                SiteConfig.value("companyOrganisationName", "Test *Company/Organisation Name:"),
                SiteConfig.value("jobTitle", "Test *Job Title:"));
    }

    /** This DownloadTheComplementaryFullReportToDiscoverWhyAtos with firstName in place of its own. */
    public DownloadTheComplementaryFullReportToDiscoverWhyAtos withFirstName(String firstName) {
        return new DownloadTheComplementaryFullReportToDiscoverWhyAtos(firstName, lastName, businessEmailAddress, companyOrganisationName, jobTitle);
    }

    /** This DownloadTheComplementaryFullReportToDiscoverWhyAtos with lastName in place of its own. */
    public DownloadTheComplementaryFullReportToDiscoverWhyAtos withLastName(String lastName) {
        return new DownloadTheComplementaryFullReportToDiscoverWhyAtos(firstName, lastName, businessEmailAddress, companyOrganisationName, jobTitle);
    }

    /** This DownloadTheComplementaryFullReportToDiscoverWhyAtos with businessEmailAddress in place of its own. */
    public DownloadTheComplementaryFullReportToDiscoverWhyAtos withBusinessEmailAddress(String businessEmailAddress) {
        return new DownloadTheComplementaryFullReportToDiscoverWhyAtos(firstName, lastName, businessEmailAddress, companyOrganisationName, jobTitle);
    }

    /** This DownloadTheComplementaryFullReportToDiscoverWhyAtos with companyOrganisationName in place of its own. */
    public DownloadTheComplementaryFullReportToDiscoverWhyAtos withCompanyOrganisationName(String companyOrganisationName) {
        return new DownloadTheComplementaryFullReportToDiscoverWhyAtos(firstName, lastName, businessEmailAddress, companyOrganisationName, jobTitle);
    }

    /** This DownloadTheComplementaryFullReportToDiscoverWhyAtos with jobTitle in place of its own. */
    public DownloadTheComplementaryFullReportToDiscoverWhyAtos withJobTitle(String jobTitle) {
        return new DownloadTheComplementaryFullReportToDiscoverWhyAtos(firstName, lastName, businessEmailAddress, companyOrganisationName, jobTitle);
    }
}
