// Generated by Suite Builder from a crawl of the site. Locators for LpDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetail;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 23 pages like /en/lp/isg-eu-ai-driven-app-services, /en/lp/leader-isg-provider-lens-servicenow-2025, /en/lp/agentic-ai-hackathon.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum LpDetailElements implements PageElement {
    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: each of its 3 pages read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: each of its 3 pages read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // "Download the complementary full report to discover why Atos " form (from the crawl: nothing was typed, clicked or sent).
    /** text field "*First Name:", required: seen by the crawl on /en/lp/isg-eu-ai-driven-app-services. */
    FIRST_NAME_INPUT(page -> page.locator("xpath=//input[@id='FirstName']")),
    /** text field "*Last Name:", required: seen by the crawl on /en/lp/isg-eu-ai-driven-app-services. */
    LAST_NAME_INPUT(page -> page.locator("xpath=//input[@id='LastName']")),
    /** email field "*Business Email Address:", required: seen by the crawl on /en/lp/isg-eu-ai-driven-app-services. */
    BUSINESS_EMAIL_ADDRESS_INPUT(page -> page.locator("xpath=//input[@id='Email']")),
    /** text field "*Company/Organisation Name:", required: seen by the crawl on /en/lp/isg-eu-ai-driven-app-services. */
    COMPANY_ORGANISATION_NAME_INPUT(page -> page.locator("xpath=//input[@id='Company']")),
    /** text field "*Job Title:": seen by the crawl on /en/lp/isg-eu-ai-driven-app-services. */
    JOB_TITLE_INPUT(page -> page.locator("xpath=//input[@id='Title']")),
    /** button "Submit": seen by the crawl on /en/lp/isg-eu-ai-driven-app-services. */
    SUBMIT_BUTTON(page -> page.locator("xpath=//button[normalize-space()='Submit']")),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Previous slide (only for visual purpose, links already av...": seen by the crawl on /en/lp/agentic-ai-hackathon. */
    PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Previous slide (only for visual purpose, links already available just before)']")),
    /** button "Next slide (only for visual purpose, links already availa...": seen by the crawl on /en/lp/agentic-ai-hackathon. */
    NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Next slide (only for visual purpose, links already available just before)']")),
    /** button "Play Click to play video": seen by the crawl on /en/lp/agentic-ai-hackathon. */
    PLAY_CLICK_TO_PLAY_VIDEO_BUTTON(page -> page.locator("xpath=//div[@id='div-kkOCejfustQ-snpg']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    LpDetailElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    LpDetailElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
