// Generated by Suite Builder from a crawl of the site. Page object for ExpertDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.expertdetail;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.expertdetail.actions.ExpertDetailReadActions;
import net.atos.tests.pages.expertdetail.actions.ExpertDetailVerifyActions;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 4 pages, like /en/services,
 *                   /en/expert/chris-mcclean, /en/expert/zeina-zakhour.
 * Stories call it:  "View all Services &gt;" (the links that lead here).
 * Get here:         new ExpertDetailPage(page).open("chris-mcclean")
 *                   from any page: navigateTo().viewAllServices() (in the "Services" menu)
 *                   from BlogDetailPage:
 *                   click().goToExpertDetail("accelerate-your-journey-to-digital-net-zero")
 *                   from LpDigitalSecurityMagazinePage: click().goToExpertDetail("zeina-zakhour")
 *                   from LpDetailPage4: click().goToExpertDetail("chris-mcclean")
 * The crawl saw:    4 pages of this type (/en/services, /en/expert/chris-mcclean,
 *                   /en/expert/zeina-zakhour, ...).
 * Proven loaded by: the main heading (isLoaded(), PROVES_LOADED: what a copy edit leaves alone
 *                   first).
 * As crawled:       crawl/pages/en/services.html, crawl/pages/en/expert/chris-mcclean.html, ...
 *                   (the page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/ExpertDetailPage/
 *                   (saved-pages/README.md) and add what it shows to ExpertDetailElements.
 * </pre>
 */
public class ExpertDetailPage extends LoadablePage<ExpertDetailPage> implements
        ReadableAction<ExpertDetailReadActions>,
        VerifiableAction<ExpertDetailVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    /** Every title of this type starts and ends like this (from the crawl: {name} - Atos). */
    public static final String TITLE_STARTS_WITH = "";
    public static final String TITLE_ENDS_WITH = " - Atos";

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/en/expert/*", "/en/*");

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default c8d085bd
    public static final List<String> EXAMPLES = List.of(
            "chris-mcclean",
            "zeina-zakhour",
            "justin-cook");
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default e22fee3e
    static final List<ExpertDetailElements> PROVES_LOADED = List.of(
            ExpertDetailElements.MAIN_HEADING);
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public ExpertDetailPage(Page page) {
        super(page);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public ExpertDetailPage open(String name) {
        expectedPath = UrlPaths.expertDetail(name);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(page, expectedPath)
                : WaitActions.waitForUrlShape(page, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE_STARTS_WITH, TITLE_ENDS_WITH)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\"");
        }

        for (ExpertDetailElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, ExpertDetailElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 200;
    }

    @Override
    public ExpertDetailReadActions read() {
        return new ExpertDetailReadActions(page);
    }

    @Override
    public ExpertDetailVerifyActions verify() {
        return new ExpertDetailVerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
