// Generated by Suite Builder from a crawl of the site. Locators for ExpertDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.expertdetail;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 4 pages like /en/services, /en/expert/chris-mcclean, /en/expert/zeina-zakhour.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum ExpertDetailElements implements PageElement {
    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: each of its 4 pages read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: each of its 4 pages read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    ExpertDetailElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    ExpertDetailElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
