// Generated by Suite Builder from a crawl of the site. Checks for IndustriesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.industries.actions;

import net.atos.tests.pages.industries.IndustriesPage;
import net.atos.tests.pages.industries.IndustriesElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on IndustriesPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class IndustriesVerifyActions {
    private final Page page;

    public IndustriesVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public IndustriesVerifyActions isLoaded() {
        IndustriesPage here = new IndustriesPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public IndustriesVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Industries\", \"Tailored Solutions for Your Industry Needs\", \"Driving Industry-Focused Innovation\", \"Energy and Utilities\", \"Financial Services and Insurance\", \"Healthcare and Life Sciences\")",
                IndustriesElements.INDUSTRIES_HEADING, IndustriesElements.TAILORED_SOLUTIONS_FOR_YOUR_INDUSTRY_NEEDS_HEADING, IndustriesElements.DRIVING_INDUSTRY_FOCUSED_INNOVATION_HEADING, IndustriesElements.ENERGY_AND_UTILITIES_HEADING, IndustriesElements.FINANCIAL_SERVICES_AND_INSURANCE_HEADING, IndustriesElements.HEALTHCARE_AND_LIFE_SCIENCES_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(IndustriesElements.SOME_HEADING)}. */
    public IndustriesVerifyActions shows(IndustriesElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public IndustriesVerifyActions doesNotShow(IndustriesElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public IndustriesVerifyActions says(IndustriesElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public IndustriesVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public IndustriesVerifyActions holds(IndustriesElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public IndustriesVerifyActions isEmpty(IndustriesElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public IndustriesVerifyActions refusesEmpty(IndustriesElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public IndustriesVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, IndustriesElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
