// Generated by Suite Builder from a crawl of the site. Which requests are ads.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.core;

import java.util.List;
import java.util.Locale;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Ad networks, blocked in every test (BaseTest) unless {@code -DblockAds=false}. Their full-page ads
 * take over the click a test makes (automationexercise.com: a click on "Products" landed on
 * /#google_vignette), and they keep pages loading. They are not the site under test.
 */
public final class Ads {
    /** Hosts of ad networks; their subdomains count too. */
    public static final List<String> HOSTS = List.of(
            "doubleclick.net", "googlesyndication.com", "googleadservices.com", "adservice.google.com",
            "googletagservices.com", "amazon-adsystem.com", "adnxs.com", "taboola.com",
            "outbrain.com", "criteo.com", "pubmatic.com", "rubiconproject.com",
            "moatads.com", "casalemedia.com", "smartadserver.com", "yieldmo.com",
            "sharethrough.com");

    private Ads() {
    }

    /** True for a request to an ad network (or a subdomain of one). */
    public static boolean isAd(String url) {
        int start = url.indexOf("://");
        if (start < 0) return false;
        int end = url.indexOf('/', start + 3);
        String host = url.substring(start + 3, end < 0 ? url.length() : end).toLowerCase(Locale.ROOT);
        int port = host.indexOf(':');
        if (port >= 0) host = host.substring(0, port);
        for (List<String> hosts : List.of(HOSTS, MORE_HOSTS)) {
            for (String ad : hosts) {
                if (host.equals(ad) || host.endsWith("." + ad)) return true;
            }
        }
        return false;
    }

    // ==== YOURS (more-hosts): safe to edit; regenerating keeps what is between these lines ====
    /** More hosts to block on this site (an ad or tracking network the list above lacks). */
    public static final List<String> MORE_HOSTS = List.of();
    // ==== END YOURS (more-hosts) ====
}
