// Generated by Suite Builder from a crawl of the site. Finds elements inside frames, by the frame path the crawl recorded.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.core;

import com.microsoft.playwright.FrameLocator;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Elements inside frames (an iframe, a frameset): the frame path the crawl recorded, each frame
 * element's XPath in the document that holds it, outermost first.
 * {@code Frames.in(page, "//iframe[@id='pay']")} is that frame, and a locator from it finds what is
 * inside: {@code Headings.named(Frames.in(page, "//iframe[@id='pay']"), "Card details")}. Playwright
 * needs no switching in and out: each locator carries its frame.
 */
public final class Frames {
    private Frames() {
    }

    /** The frame at the end of the path, one frame element after another from the page down. */
    public static FrameLocator in(Page page, String... path) {
        FrameLocator frame = page.frameLocator("xpath=" + path[0]);
        for (int i = 1; i < path.length; i++) frame = frame.frameLocator("xpath=" + path[i]);
        return frame;
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
