// Generated by Suite Builder from a crawl of the site. Implemented by every Elements enum.
// EDIT RULES: do not edit this file; regenerating replaces all of it. To name one element differently in steps, override label() on that constant in its Elements enum.
package net.atos.tests.core;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;

import java.util.Locale;

/** An element of a page: its locator, and how steps and failures name it. */
public interface PageElement {
    Locator locator(Page page);

    /** The constant's name, e.g. SUBMIT_BUTTON. */
    String name();

    /**
     * How steps and failure messages name it: SUBMIT_BUTTON -> "the submit button"; one whose name
     * starts with YOUR keeps it: YOUR_CV_INPUT -> "your cv input", never "the your cv input". A constant
     * can say it better: {@code SEND_BUTTON(...) { @Override public String label() { return "the Send button"; } }}.
     */
    default String label() {
        String words = name().toLowerCase(Locale.ROOT).replace('_', ' ');
        return words.startsWith("your ") ? words : "the " + words;
    }

    /**
     * One element made on the fly, named in steps by its label: what a family link helper returns,
     * so the click is {@code UserActions.click(page, HomeElements.getResultLink("Ivysaur"))}.
     */
    static PageElement of(String name, String label, LocatorProvider provider) {
        return new PageElement() {
            @Override
            public Locator locator(Page page) {
                return provider.get(page);
            }

            @Override
            public String name() {
                return name;
            }

            @Override
            public String label() {
                return label;
            }
        };
    }
}
