// Generated by Suite Builder from a crawl of the site. Where the site under test lives, and the values tests must not hard-code.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.core;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Properties;

// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * The site under test, and the suite's settings (G-129). Each setting is read from {@code -Dname=...},
 * else its environment variable (BASE_URL for baseUrl, TEST_DELAY for testDelay), else
 * src/test/resources/suite.properties, else its default in the code; the run's first line says which.
 * Defaults to the crawled site; point the suite elsewhere (a staging copy) with baseUrl.
 */
public final class SiteConfig {
    public static final String CRAWLED_URL = "https://atos.net";
    /** The settings a run is told, in the order the run's first line gives them. */
    public static final List<String> SETTINGS = List.of("baseUrl", "environment", "browser", "headed", "userAgent", "blockAds",
            "testDelay", "stopAfter", "elementTimeout", "pageLoadTimeout", "loadBudget");
    /** The file a team keeps its settings in (this whole file is theirs). */
    public static final Path FILE = Path.of("src", "test", "resources", "suite.properties");
    private static final String SAID = settle();

    private SiteConfig() {
    }

    /** The run's first line: each setting given, its value and where it came from; the rest are the code's defaults. */
    public static String settings() {
        return SAID;
    }

    /** Puts each setting the environment or suite.properties gives, and -D does not, into the system properties, where the suite reads it. */
    private static String settle() {
        Properties file = new Properties();
        if (Files.isRegularFile(FILE)) {
            try (Reader in = Files.newBufferedReader(FILE, StandardCharsets.UTF_8)) {
                file.load(in);
            } catch (IOException e) {
                System.out.println("   note: could not read " + FILE + ": " + e.getMessage());
            }
        }
        List<String> said = new ArrayList<>();
        for (String name : SETTINGS) {
            String env = name.replaceAll("([a-z])([A-Z])", "$1_$2").toUpperCase(Locale.ROOT);
            String value = System.getProperty(name);
            String from = "-D" + name;
            if (value == null || value.isBlank()) {
                value = System.getenv(env);
                from = env;
            }
            if (value == null || value.isBlank()) {
                value = file.getProperty(name);
                from = "suite.properties";
            }
            if (value == null || value.isBlank()) continue;
            System.setProperty(name, value.trim());
            said.add(name + " " + value.trim() + " (" + from + ")");
        }
        if (said.stream().noneMatch(line -> line.startsWith("baseUrl "))) said.add(0, "baseUrl " + CRAWLED_URL + " (the crawl's)");
        return "Settings: " + String.join(", ", said) + "; the rest as the code says (" + FILE + " lists them all).";
    }

    /** Where the site under test lives: the baseUrl setting, else the address the crawl read. */
    public static String baseUrl() {
        String value = System.getProperty("baseUrl");
        return value == null || value.isBlank() ? CRAWLED_URL : strip(value);
    }

    /** The full URL of a path on the site under test, e.g. url("/about"). */
    public static String url(String path) {
        return baseUrl() + (path.startsWith("/") ? path : "/" + path);
    }

    /**
     * A secret a test needs (a password, an API key): from {@code -Dname=...} or the environment
     * variable NAME (upper case; dots and dashes become underscores). Fails, saying how to pass it,
     * when neither is set. Secrets never go into the code, a saved page or a log.
     */
    public static String secret(String name) {
        String value = lookup(name);
        if (value == null) {
            throw new Error("This test needs " + name + ": run with -D" + name + "=... or set the "
                    + envName(name) + " environment variable. Never write it into the code.");
        }
        return value;
    }

    /**
     * Test data that may differ between copies of the site (a product that exists on staging, say):
     * from {@code -Dname=...} or the environment variable NAME, else the fallback.
     */
    public static String value(String name, String fallback) {
        String value = lookup(name);
        return value == null ? fallback : value;
    }

    private static String lookup(String name) {
        String fromProperty = System.getProperty(name);
        if (fromProperty != null && !fromProperty.isBlank()) return fromProperty;
        String fromEnv = System.getenv(envName(name));
        return fromEnv != null && !fromEnv.isBlank() ? fromEnv : null;
    }

    /** "login.password" -> "LOGIN_PASSWORD" */
    private static String envName(String name) {
        return name.replace('.', '_').replace('-', '_').toUpperCase(java.util.Locale.ROOT);
    }

    private static String strip(String url) {
        return url.endsWith("/") ? url.substring(0, url.length() - 1) : url;
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // More settings the suite needs, e.g.:
    // public static String searchTerm() {
    //     return value("searchTerm", "cloud");
    // }
    // ==== END YOURS (extras) ====
}
