// Generated by Suite Builder from a crawl of the site. Page object for SiteDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetail;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.pages.sitedetail.actions.SiteDetailClickActions;
import net.atos.tests.pages.sitedetail.actions.SiteDetailReadActions;
import net.atos.tests.pages.sitedetail.actions.SiteDetailVerifyActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 3 pages, like /en/.
 * Stories call it:  "Homepage" (the links that lead here).
 * Get here:         new SiteDetailPage(page).open("en")
 *                   from any page: navigateTo().homepage()
 *                   from ClientSuccessClientStoriesPage: click().goToSiteDetail("")
 * The crawl saw:    1 page of this type (/en/); it showed "Cybersecurity Awareness Month 2026",
 *                   "Building a human firewall in an AI-powered world", "Accelerating
 *                   Intelligence", "Latest news", "Atos to develop a new digital service model for
 *                   Barcelona City Council employees" and "Ideas and frontiers".
 * Proven loaded by: the heading "Cybersecurity Awareness Month 2026" and the heading "Accelerating
 *                   Intelligence" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/en.html (the page's HTML when crawled: check a locator there with
 *                   suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/SiteDetailPage/
 *                   (saved-pages/README.md) and add what it shows to SiteDetailElements.
 * </pre>
 */
public class SiteDetailPage extends LoadablePage<SiteDetailPage> implements
        ClickableAction<SiteDetailClickActions>,
        ReadableAction<SiteDetailReadActions>,
        VerifiableAction<SiteDetailVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/*");

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 6e629a81
    public static final List<String> EXAMPLES = List.of(
            "en");
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default dc3ecdf8
    static final List<SiteDetailElements> PROVES_LOADED = List.of(
            SiteDetailElements.CYBERSECURITY_AWARENESS_MONTH_2026_HEADING,
            SiteDetailElements.ACCELERATING_INTELLIGENCE_HEADING);
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public SiteDetailPage(Page page) {
        super(page);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public SiteDetailPage open(String name) {
        expectedPath = UrlPaths.siteDetail(name);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(page, expectedPath)
                : WaitActions.waitForUrlShape(page, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);


        for (SiteDetailElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, SiteDetailElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    @Override
    public SiteDetailClickActions click() {
        return new SiteDetailClickActions(page);
    }

    @Override
    public SiteDetailReadActions read() {
        return new SiteDetailReadActions(page);
    }

    @Override
    public SiteDetailVerifyActions verify() {
        return new SiteDetailVerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
