// Generated by Suite Builder from a crawl of the site. Browser setup for every test.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests;

import net.atos.tests.core.Ads;
import net.atos.tests.core.Credentials;
import net.atos.tests.core.Pace;
import net.atos.tests.core.Timings;
import net.atos.tests.core.SiteConfig;
import net.atos.tests.core.StepLog;
import net.atos.tests.pages.signin.SignIns;
import net.atos.tests.core.WaitActions;
import com.microsoft.playwright.APIRequest;
import com.microsoft.playwright.APIRequestContext;
import com.microsoft.playwright.Browser;
import com.microsoft.playwright.BrowserContext;
import com.microsoft.playwright.BrowserType;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestInfo;
import org.junit.jupiter.api.extension.AfterTestExecutionCallback;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.junit.jupiter.api.extension.TestWatcher;
import org.opentest4j.TestAbortedException;

import java.lang.reflect.Method;
import java.nio.file.Path;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * One browser per test class, a fresh context (cookies, storage) per test. Test classes may run at
 * once ({@code -Dthreads=4}): each has its own Playwright and browser, held by the thread that runs it
 * (Playwright's objects belong to one thread).
 * Ad networks are blocked ({@link Ads}; {@code -DblockAds=false} lets them through).
 * Headless by default. Watch it run with {@code -Dheaded=true} (or {@code -Dheadless=false}):
 * every action is then slowed down by half a second so you can follow; change that with
 * {@code -DslowMo=1000} (milliseconds).
 * Each test prints a line as it starts and ends, so a slow site doesn't look like a stuck run, and
 * its steps in plain English as it takes them; a failed test says which step failed, and why.
 * <p>Every test is watched ({@link Evidence}): a failed one leaves a screenshot, the DOM, a
 * Playwright trace, console errors, failed requests and its steps in target/failures/, without any
 * test asking for it. Every test class extends this one (SuiteRulesTest checks), so none is left out.
 */
@ExtendWith(RerunOnce.class)
public abstract class BaseTest {
    static {
        SiteConfig.settings(); // the settings in place before any are read (G-129)
    }
    private static final ThreadLocal<Playwright> PLAYWRIGHT = new ThreadLocal<>();
    private static final ThreadLocal<Browser> BROWSER = new ThreadLocal<>();

    /** This test class's browser. */
    protected static Browser browser() {
        return BROWSER.get();
    }
    protected BrowserContext context;
    /** How a test without a browser asks the site ({@link WithoutBrowser}): Playwright's HTTP, as the crawl's browser. */
    protected APIRequestContext http;
    protected Page page;
    /** What this test will leave behind if it fails. */
    protected Evidence evidence;
    private long startedAt;
    /** This test's own TestInfo, for its second try's fresh start (G-135). */
    private TestInfo info;

    /**
     * A test class that asks the site by HTTP only (LinkReportTest): no browser is opened for it, so
     * it answers in seconds. It has no page and leaves no screenshot; its steps and reason still show.
     */
    public interface WithoutBrowser {
    }

    /**
     * The User-Agent the crawl used: the site answered it. Some sites stall or refuse headless
     * Chrome's own. Override with {@code -DuserAgent="..."}.
     */
    static final String CRAWL_USER_AGENT = "Mozilla/5.0 (compatible; SuiteBuilder/1.0; +https://github.com/Ghost-in-the-Kernel-Labs/Ghost-in-the-Kernel-Labs-suite-builder-docs)";

    /** Saves a failed test's evidence while its page is still open (before @AfterEach closes it). */
    @RegisterExtension
    static final AfterTestExecutionCallback KEEP_EVIDENCE = new KeepEvidence();

    /** When a test fails, says in plain English which step it failed at, why, and where its evidence is. */
    @RegisterExtension
    static final TestWatcher EXPLAIN_FAILURES = new ExplainFailures();

    /** After several tests in a row fail the same way (the site is down), the rest are skipped, saying why. */
    @RegisterExtension
    static final StopEarly STOP_EARLY = new StopEarly();

    private static final ThreadLocal<Path> SAVED = new ThreadLocal<>();
    /** The failed test's note on its page's scripts that did not load, said under its reason. */
    private static final ThreadLocal<String> SCRIPTS = new ThreadLocal<>();

    /** True once this run has said how old its crawl is. */
    private static boolean started;

    /**
     * Once per run, before the first browser: how old the crawl is. The suite's rules are not checked
     * here: SuiteRulesTest checks them with every run, and a test asked for alone
     * ({@code -Dtest=ContactFormTest}) runs whatever they say (G-119).
     */
    private static synchronized void startTheRun() {
        if (started) return;
        started = true;
        noteTheCrawlsAge();
        // Every role's account file, blank, where there is none: a fresh clone shows where accounts go (G-159).
        Credentials.blankFiles(SignIns.ROLES);
    }

    @BeforeAll
    protected static void launchBrowser(TestInfo all) throws java.io.IOException {
        startTheRun();
        boolean headed = Boolean.parseBoolean(System.getProperty("headed", "false"))
                || !Boolean.parseBoolean(System.getProperty("headless", "true"));
        long slowMo = headed ? Long.getLong("slowMo", 500L) : 0L;
        PLAYWRIGHT.set(Playwright.create());
        if (all.getTestClass().filter(WithoutBrowser.class::isAssignableFrom).isPresent()) return;
        BROWSER.set(browserType().launch(new BrowserType.LaunchOptions()
                .setHeadless(!headed)
                .setSlowMo(slowMo)));
    }

    /**
     * The browser the tests run in: Chromium, unless {@code -Dbrowser=firefox} or {@code -Dbrowser=webkit}
     * (WebKit is Safari's engine: where Safari-only breakage shows). Playwright downloads all three.
     */
    static BrowserType browserType() {
        String name = System.getProperty("browser", "chromium").trim().toLowerCase(java.util.Locale.ROOT);
        return switch (name) {
            case "chromium", "chrome" -> PLAYWRIGHT.get().chromium();
            case "firefox" -> PLAYWRIGHT.get().firefox();
            case "webkit", "safari" -> PLAYWRIGHT.get().webkit();
            default -> throw new IllegalArgumentException("-Dbrowser=" + name + ": use chromium, firefox or webkit.");
        };
    }

    /**
     * Says, once per run, when the crawl the suite was built from is old: the site may have changed
     * since, and every page class, element and snapshot came from that crawl. Only a note: it fails
     * nothing. {@code -DcrawlMaxAgeDays} (default 1).
     */
    private static void noteTheCrawlsAge() {
        try {
            java.nio.file.Path manifest = java.nio.file.Paths.get("crawl", "manifest.json");
            if (!java.nio.file.Files.isRegularFile(manifest)) return;
            String text = java.nio.file.Files.readString(manifest, java.nio.charset.StandardCharsets.UTF_8);
            int at = text.indexOf("\"crawlFileSaved\": \"");
            if (at < 0) return;
            int start = at + "\"crawlFileSaved\": \"".length();
            java.time.Instant saved = java.time.Instant.parse(text.substring(start, text.indexOf('"', start)));
            long days = java.time.Duration.between(saved, java.time.Instant.now()).toDays();
            if (days > Long.getLong("crawlMaxAgeDays", 1L)) {
                System.out.println("Note: this suite was built from a crawl " + days + " days old. The site may have changed since:"
                        + " page classes, elements and crawl/pages/ are only as current as the crawl. Crawl again: suite build "
                        + site());
            }
        } catch (java.io.IOException | RuntimeException e) {
            // a note, never a reason to fail
        }
    }

    /** The site's host, as suite build takes it: example.com. */
    private static String site() {
        String host = java.net.URI.create(SiteConfig.baseUrl()).getHost();
        return host != null && host.startsWith("www.") ? host.substring(4) : String.valueOf(host);
    }

    @AfterAll
    protected static void closeBrowser() {
        if (PLAYWRIGHT.get() != null) PLAYWRIGHT.get().close();
        PLAYWRIGHT.remove();
        BROWSER.remove();
    }

    @BeforeEach
    protected void newContext(TestInfo test) {
        System.out.println("-> " + getClass().getSimpleName() + ": " + test.getDisplayName());
        info = test;
        Pace.betweenTests();
        Timings.startTest(getClass().getSimpleName() + " > " + test.getDisplayName());
        StepLog.start();
        startedAt = System.currentTimeMillis();
        if (this instanceof WithoutBrowser) {
            String asUserAgent = System.getProperty("userAgent", CRAWL_USER_AGENT);
            APIRequest.NewContextOptions asked = new APIRequest.NewContextOptions().setTimeout(WaitActions.PAGE_LOAD_TIMEOUT);
            if (!asUserAgent.isBlank()) asked.setUserAgent(asUserAgent);
            http = PLAYWRIGHT.get().request().newContext(asked);
            return;
        }
        Browser.NewContextOptions options = new Browser.NewContextOptions().setViewportSize(1440, 900);
        String userAgent = System.getProperty("userAgent", CRAWL_USER_AGENT);
        if (!userAgent.isBlank()) options.setUserAgent(userAgent);
        context = browser().newContext(options);
        if (Boolean.parseBoolean(System.getProperty("blockAds", "true"))) {
            context.route(Ads::isAd, route -> route.abort());
        }
        // Fail within seconds rather than minutes: the elementTimeout for a click or a check, the pageLoadTimeout for a page.
        context.setDefaultTimeout(WaitActions.ELEMENT_TIMEOUT);
        context.setDefaultNavigationTimeout(WaitActions.PAGE_LOAD_TIMEOUT);
        page = context.newPage();
        // One run of a parameterized test: its own evidence folder, the method's name and its number.
        String method = test.getTestMethod().map(Method::getName).orElse("test") + StepLog.runOf(test.getDisplayName());
        evidence = new Evidence(context, page, getClass().getSimpleName(), method, test.getDisplayName());
    }

    @AfterEach
    protected void closeContext() {
        if (context != null) context.close();
        if (http != null) http.dispose();
        System.out.println(String.format("   done in %.1f s", (System.currentTimeMillis() - startedAt) / 1000.0));
    }

    /**
     * For RerunOnce (G-135): the failed first try's evidence saved as try-1/ beside where the second's
     * will be, its browser closed, and a clean one opened as before any test: cookies, storage and
     * routes start again. Returns where the first try's evidence is, or null.
     */
    final Path freshTry(Throwable first) {
        Path kept = null;
        if (evidence != null) {
            kept = evidence.firstTry().failed(first, browser().version());
        }
        closeContext();
        newContext(info);
        return kept;
    }

    private static final class KeepEvidence implements AfterTestExecutionCallback {
        @Override
        public void afterTestExecution(ExtensionContext context) {
            if (!(context.getRequiredTestInstance() instanceof BaseTest test) || test.evidence == null) return;
            // A skip (Checks.assume) is not a failure: it leaves no evidence.
            Throwable cause = context.getExecutionException().filter(e -> !(e instanceof TestAbortedException)).orElse(null);
            if (cause == null) {
                test.evidence.passed();
            } else {
                SAVED.set(test.evidence.failed(cause, browser().version()));
            }
            if (cause != null) SCRIPTS.set(test.evidence.scriptNote());
        }
    }

    private static final class ExplainFailures implements TestWatcher {
        @Override
        public void testFailed(ExtensionContext context, Throwable cause) {
            System.out.println(StepLog.failure(cause));
            String scripts = SCRIPTS.get();
            SCRIPTS.remove();
            if (scripts != null) System.out.println(scripts);
            Path saved = SAVED.get();
            SAVED.remove();
            if (saved != null) {
                System.out.println("   evidence: " + saved + " (screenshot, page.html, steps.txt; open trace.zip at https://trace.playwright.dev)");
            }
        }
    }

    /**
     * Signs in as the role before a test of a page the crawl read signed in as it (G-158, G-159): its
     * account from core/Credentials (the environment, Suite Builder's store when docked, secrets/), typed
     * through the role's sign-in page in pages/signin. What is typed is never logged, nor in the evidence.
     */
    /** Each role's session, signed in once a run in a browser context of its own, never traced: what is typed is in no trace. */
    private static final java.util.Map<String, java.util.List<com.microsoft.playwright.options.Cookie>> SESSIONS = new java.util.concurrent.ConcurrentHashMap<>();

    protected void signInAs(String role) {
        java.util.List<com.microsoft.playwright.options.Cookie> cookies = SESSIONS.get(role);
        if (cookies == null) {
            Browser.NewContextOptions options = new Browser.NewContextOptions().setViewportSize(1440, 900);
            String userAgent = System.getProperty("userAgent", CRAWL_USER_AGENT);
            if (!userAgent.isBlank()) options.setUserAgent(userAgent);
            try (BrowserContext alone = browser().newContext(options)) {
                alone.setDefaultTimeout(WaitActions.ELEMENT_TIMEOUT);
                alone.setDefaultNavigationTimeout(WaitActions.PAGE_LOAD_TIMEOUT);
                SignIns.as(alone.newPage(), role);
                cookies = alone.cookies();
            }
            SESSIONS.put(role, cookies);
        } else {
            StepLog.step("Sign in as " + role + " (signed in once this run: its session again)");
        }
        context.addCookies(cookies);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Setup every test needs (logging in once, say) goes here. A test of a story goes in the
    // stories package and extends StoryTest.
    // ==== END YOURS (extras) ====
}
