// Generated by Suite Builder from a crawl of the site. The harness tests itself: evidence, checks and actions, on a page of its own.
// EDIT RULES: OFF LIMITS, to people and AIs alike. This file is one of the suite's rules (SUITE-RULES.md). A change to it, a move, a rename or a deletion is a change outside a YOURS block: regenerating will overwrite it, SR-16 reports it and suite verify finds it. To get a test through, fix the test or push back on the story; to change a rule, change Suite Builder.
package net.atos.tests;

import net.atos.tests.core.Checks;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.core.WaitActions;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.parallel.Isolated;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The suite tests the site; this tests the suite. A few seconds, on a page it writes itself (no
 * site, no network), with every whole run ({@code mvn test}; -Dgroups=harness alone), last:
 *
 * <ul>
 * <li>a failure leaves its evidence (screenshot, page.html, trace, steps, console, network, run);
 * <li>every check passes what it should, and fails what it should with exactly the message a
 *     person will read in a real failure;
 * <li>every action does what its step says, and the step log says it.
 * </ul>
 *
 * <p>When one of these fails, the harness is broken, not the site: every other failure in the run
 * is suspect until it is fixed. Rebuilding the suite puts the harness back as generated.
 */
@Tag("harness")
@Order(Integer.MAX_VALUE)
@Isolated
class HarnessTest extends BaseTest {

    /** The page every test here runs on: made up, loaded straight into the browser. */
    static final String PAGE = """
            <!DOCTYPE html>
            <html><head><title>Harness page</title><style>html { scroll-behavior: smooth; }</style></head><body>
            <h1>Harness <span>page</span></h1>
            <h2>Contact&nbsp;<strong>Us</strong></h2>
            <button id="add">Add one</button>
            <button id="hidden" style="display:none">Hidden</button>
            <button id="later">Later</button>
            <button class="twin">Twin</button><button class="twin">Twin</button>
            <p id="count">0</p>
            <p id="spaced">  Hello
                 world  </p>
            <label>Name <input id="name"></label>
            <form action="/never"><label>Town <input id="town" required></label></form>
            <label><input type="checkbox" id="agree"> I agree</label>
            <select id="colour"><option>Red</option><option value="b">Blue</option></select>
            <p id="late"></p>
            <p id="quoted">Say "hi"</p>
            <button id="off" disabled>Off</button>
            <a id="help" href="/help">Help</a>
            <ul id="items"><li>One</li><li>Two</li><li style="display:none">Three</li></ul>
            <img src="https://harness.invalid/harness-missing.png" alt="">
            <div style="height: 2400px"></div>
            <button id="far">Far down</button>
            <p id="far-clicked"></p>
            <h2 id="reveal" style="opacity: 0; transition: opacity 0.2s">Revealed on scroll</h2>
            <div style="height: 1200px"></div>
            <script>
              document.getElementById('add').onclick = () => {
                const count = document.getElementById('count');
                count.textContent = String(Number(count.textContent) + 1);
              };
              document.getElementById('later').onclick = () =>
                setTimeout(() => { document.getElementById('late').textContent = 'Arrived'; }, 200);
              document.getElementById('far').onclick = () => { document.getElementById('far-clicked').textContent = 'Clicked'; };
              // A section that fades in once it is scrolled to, as many sites draw theirs (Site G, 2026-10-03).
              new IntersectionObserver((seen) => seen.forEach((e) => { if (e.isIntersecting) e.target.style.opacity = '1'; })).observe(document.getElementById('reveal'));
              console.error('harness: a console error');
            </script>
            </body></html>
            """;

    /** The harness page's elements, declared the way every page's Elements enum is. */
    enum Harness implements PageElement {
        ADD_BUTTON(page -> page.locator("css=#add")),
        HIDDEN_BUTTON(page -> page.locator("css=#hidden")),
        LATER_BUTTON(page -> page.locator("css=#later")),
        TWIN_BUTTON(page -> page.locator("css=.twin")),
        BROKEN_LOCATOR(page -> page.locator("xpath=//button[")),
        COUNT(page -> page.locator("css=#count")),
        SPACED_TEXT(page -> page.locator("css=#spaced")),
        NAME_FIELD(page -> page.locator("css=#name")),
        TOWN_FIELD(page -> page.locator("css=#town")),
        AGREE_BOX(page -> page.locator("css=#agree")),
        COLOUR_LIST(page -> page.locator("css=#colour")),
        LATE_TEXT(page -> page.locator("css=#late")),
        OFF_BUTTON(page -> page.locator("css=#off")),
        HELP_LINK(page -> page.locator("css=#help")),
        FAR_BUTTON(page -> page.locator("css=#far")),
        FAR_TEXT(page -> page.locator("css=#far-clicked")),
        REVEALED_HEADING(page -> page.locator("css=#reveal")),
        CONTACT_HEADING(page -> Headings.named(page, "Contact Us")),
        MISSING_HEADING(page -> Headings.named(page, "Nowhere"));

        private final LocatorProvider provider;

        Harness(LocatorProvider provider) {
            this.provider = provider;
        }

        @Override
        public Locator locator(Page page) {
            return provider.get(page);
        }
    }

    @BeforeEach
    void openTheHarnessPage() {
        // The page's one image fails at once, every time, without the network: network.txt must list it.
        context.route("**/harness-missing.png", route -> route.abort());
        page.setContent(PAGE);
        WaitActions.shortenWaits(500L);
    }

    @AfterEach
    void normalWaits() {
        WaitActions.shortenWaits(null);
    }

    // ---- evidence ------------------------------------------------------------------------------

    @Test
    @DisplayName("A failure leaves its evidence: screenshot, page, trace, steps, console, network, run")
    void aFailureLeavesItsEvidence() throws IOException {
        UserActions.click(page, Harness.ADD_BUTTON);
        AssertionError failure = failureOf(() -> Checks.isShown(page, Harness.HIDDEN_BUTTON));
        Path dir = evidence.failed(failure, browser().version(), true); // in full, however many failures the run had
        try {
            for (String file : List.of("screenshot.png", "page.html", "trace.zip", "steps.txt", "console.txt", "network.txt", "run.txt")) {
                Path path = dir.resolve(file);
                assertTrue(Files.isRegularFile(path) && Files.size(path) > 0, "A failure should leave " + path + ", and it is missing or empty.");
            }
            String steps = read(dir.resolve("steps.txt"));
            assertTrue(steps.contains("1. Click the add button\n2. Check that the hidden button is shown   <- FAILED HERE"),
                    "steps.txt should list the steps and mark the failed one; it says:\n" + steps);
            assertTrue(steps.contains("Because: java.lang.AssertionError: Expected the hidden button to be shown"),
                    "steps.txt should say why it failed; it says:\n" + steps);
            assertTrue(read(dir.resolve("page.html")).contains("<h1>Harness <span>page</span></h1>"),
                    "page.html should hold the page as it was when the test failed.");
            assertTrue(read(dir.resolve("console.txt")).contains("harness: a console error"),
                    "console.txt should hold the page's console errors; it says:\n" + read(dir.resolve("console.txt")));
            assertTrue(read(dir.resolve("network.txt")).contains("harness-missing.png"),
                    "network.txt should hold the request that failed; it says:\n" + read(dir.resolve("network.txt")));
            String explained = StepLog.failure(failure);
            assertTrue(explained.startsWith("   FAILED at step 2: Check that the hidden button is shown\n   because: Expected the hidden button to be shown"),
                    "A failure should be explained with its step and reason; it was:\n" + explained);
        } finally {
            Evidence.deleteAll(dir); // this failure was on purpose: it leaves nothing to be mistaken for a real one
        }
    }

    // ---- checks: what they pass ----------------------------------------------------------------

    @Test
    @DisplayName("Checks pass what they should")
    void checksPassWhatTheyShould() {
        Checks.isShown(page, Harness.ADD_BUTTON);
        Checks.isNotShown(page, Harness.HIDDEN_BUTTON);
        Checks.hasText(page, Harness.SPACED_TEXT, "Hello world");
        Checks.containsText(page, Harness.SPACED_TEXT, "world");
        Checks.pageShowsText(page, "Add one");
        Checks.titleIs(page, "Harness page");
        Checks.allShown(page, "its buttons and headings", Harness.ADD_BUTTON, Harness.CONTACT_HEADING);
        UserActions.click(page, Harness.LATER_BUTTON);
        Checks.hasText(page, Harness.LATE_TEXT, "Arrived"); // appears 0.2 s after the click: the check waits for it
        assertTrue(StepLog.steps().size() == 9, "Every check and action should log one step; the log has: " + StepLog.steps());
    }

    @Test
    @DisplayName("A heading split across elements, with a non-breaking space, is found by its words")
    void headingsAreFoundByTheirWords() {
        Checks.isShown(page, Harness.CONTACT_HEADING);
    }

    // ---- checks: what they fail, and what they say ---------------------------------------------

    @Test
    @DisplayName("isShown fails on a hidden element, saying so")
    void isShownFails() {
        says(() -> Checks.isShown(page, Harness.HIDDEN_BUTTON),
                "Expected the hidden button to be shown, but it was not (waited 0.5 s).");
    }

    @Test
    @DisplayName("isNotShown fails on a shown element, saying so")
    void isNotShownFails() {
        says(() -> Checks.isNotShown(page, Harness.ADD_BUTTON),
                "Expected the add button not to be shown, but it still was (waited 0.5 s).");
    }

    @Test
    @DisplayName("hasText fails on other text, quoting what it found")
    void hasTextFails() {
        says(() -> Checks.hasText(page, Harness.SPACED_TEXT, "Goodbye"),
                "Expected the spaced text to say \"Goodbye\", but it said \"Hello world\" (waited 0.5 s).");
    }

    @Test
    @DisplayName("hasText fails on a hidden element, saying it was not shown")
    void hasTextFailsWhenHidden() {
        says(() -> Checks.hasText(page, Harness.HIDDEN_BUTTON, "Hidden"),
                "Expected the hidden button to say \"Hidden\", but it said nothing (it was not shown) (waited 0.5 s).");
    }

    @Test
    @DisplayName("containsText fails when the words are missing")
    void containsTextFails() {
        says(() -> Checks.containsText(page, Harness.SPACED_TEXT, "Goodbye"),
                "Expected the spaced text to mention \"Goodbye\", but it said \"Hello world\" (waited 0.5 s).");
    }

    @Test
    @DisplayName("hasValue fails on an empty field")
    void hasValueFails() {
        says(() -> Checks.hasValue(page, Harness.NAME_FIELD, "Ann"),
                "Expected the name field to hold \"Ann\", but it held \"\" (waited 0.5 s).");
    }

    @Test
    @DisplayName("pageShowsText fails when the page does not show it")
    void pageShowsTextFails() {
        says(() -> Checks.pageShowsText(page, "Goodbye"),
                "Expected the page to show \"Goodbye\", but it did not (waited 0.5 s).");
    }

    @Test
    @DisplayName("titleIs fails on another title, quoting it")
    void titleIsFails() {
        says(() -> Checks.titleIs(page, "Other page"),
                "Expected the page title \"Other page\", but it was \"Harness page\" (waited 0.5 s).");
    }

    @Test
    @DisplayName("allShown fails naming the first element missing")
    void allShownFails() {
        says(() -> Checks.allShown(page, "its headings", Harness.CONTACT_HEADING, Harness.MISSING_HEADING, Harness.HIDDEN_BUTTON),
                "Expected the page to show the missing heading, but it did not (waited 0.5 s).");
    }

    @Test
    @DisplayName("assume skips, saying why, when what a test needs is not there; passes on when it is")
    void assumeSkipsSayingWhy() {
        Checks.assume(true, "never said");
        assertTrue(StepLog.steps().stream().noneMatch(step -> step.contains("never said")), "assume, met, should say nothing");
        try {
            Checks.assume(false, "no policy with an amount due in policies.csv");
            throw new AssertionError("assume, not met, should have skipped the test");
        } catch (Checks.NotMet skipped) {
            assertTrue("no policy with an amount due in policies.csv".equals(skipped.getMessage()), "The skip should say why; it said: " + skipped.getMessage());
        }
        List<String> steps = StepLog.steps();
        assertTrue(steps.get(steps.size() - 1).equals("Skipped: no policy with an amount due in policies.csv"), "The last step should say it was skipped, and why: " + steps);
    }

    @Test
    @DisplayName("The state checks pass what they should, and text with quotes is found as given")
    void stateChecksPass() {
        Checks.pageShowsText(page, "Say \"hi\"");
        Checks.hasCount(page, "items", page.locator("css=#items li"), 2);
        Checks.isEnabled(page, Harness.ADD_BUTTON);
        Checks.isDisabled(page, Harness.OFF_BUTTON);
        Checks.isNotChecked(page, Harness.AGREE_BOX);
        UserActions.tick(page, Harness.AGREE_BOX);
        Checks.isChecked(page, Harness.AGREE_BOX);
        Checks.hasAttribute(page, Harness.HELP_LINK, "href", "/help");
        Checks.refusesEmpty(page, Harness.TOWN_FIELD);
    }

    @Test
    @DisplayName("refusesEmpty fails on a field the browser would send empty, saying why")
    void refusesEmptyFails() {
        says(() -> Checks.refusesEmpty(page, Harness.NAME_FIELD),
                "Expected the form not to be sent with the name field empty, but it is not required (waited 0.5 s).");
    }

    @Test
    @DisplayName("hasCount fails on another number, saying how many it saw")
    void hasCountFails() {
        says(() -> Checks.hasCount(page, "items", page.locator("css=#items li"), 3),
                "Expected the page to show 3 items, but it showed 2 (waited 0.5 s).");
    }

    @Test
    @DisplayName("isEnabled fails on a disabled button, and isChecked on an empty box")
    void stateChecksFail() {
        says(() -> Checks.isEnabled(page, Harness.OFF_BUTTON),
                "Expected the off button to be enabled, but it was disabled (waited 0.5 s).");
        says(() -> Checks.isDisabled(page, Harness.HIDDEN_BUTTON),
                "Expected the hidden button to be disabled, but it was not shown (waited 0.5 s).");
        says(() -> Checks.isChecked(page, Harness.AGREE_BOX),
                "Expected the agree box to be checked, but it was not (waited 0.5 s).");
    }

    @Test
    @DisplayName("hasAttribute fails on another value, quoting it")
    void hasAttributeFails() {
        says(() -> Checks.hasAttribute(page, Harness.HELP_LINK, "href", "/about"),
                "Expected the help link's href to be \"/about\", but it was \"/help\" (waited 0.5 s).");
        says(() -> Checks.hasAttribute(page, Harness.HELP_LINK, "title", "Help"),
                "Expected the help link's title to be \"Help\", but it was missing (waited 0.5 s).");
    }

    // ---- actions -------------------------------------------------------------------------------

    @Test
    @DisplayName("A click on something never shown says why, not Playwright's bare timeout")
    void clickOnHiddenSaysWhy() {
        says(() -> UserActions.click(page, Harness.HIDDEN_BUTTON), "the hidden button was not shown within 0.5 s: it is not on the page, or only where a visitor cannot see it (a closed menu, another slide, a layout for another screen size)");
    }

    @Test
    @DisplayName("A click that should open a new tab and does not says where this tab is")
    void noNewTabSaysWhere() {
        String here = page.url();
        says(() -> UserActions.clickOpeningNewTab(page, Harness.ADD_BUTTON), "Clicking the add button opened no new tab within 0.5 s; this tab stayed on " + here);
    }

    @Test
    @DisplayName("A locator that is not valid, or that matches several elements, is said to be so at once, not \"not shown\"")
    void locatorDefectsAreSaid() {
        // Two matches where one is meant (Playwright's strict mode): by a check, a reader and an action alike.
        String twins = "the twin button matches 2 elements on the page; its locator must match one (add .first(), or narrow it: ai/recipes/add-an-element.md)";
        says(() -> Checks.isShown(page, Harness.TWIN_BUTTON), twins);
        says(() -> Checks.hasText(page, Harness.TWIN_BUTTON, "Twin"), twins);
        says(() -> UserActions.click(page, Harness.TWIN_BUTTON), twins);
        says(() -> UserActions.type(page, Harness.TWIN_BUTTON, "x"), twins);
        // A locator that is not valid (the browser's own words follow, and differ by browser).
        saysAtFirst(() -> Checks.isShown(page, Harness.BROKEN_LOCATOR), "the broken locator's locator is not valid: ");
        saysAtFirst(() -> Checks.hasText(page, Harness.BROKEN_LOCATOR, "x"), "the broken locator's locator is not valid: ");
        saysAtFirst(() -> UserActions.click(page, Harness.BROKEN_LOCATOR), "the broken locator's locator is not valid: ");
        saysAtFirst(() -> UserActions.type(page, Harness.BROKEN_LOCATOR, "x"), "the broken locator's locator is not valid: ");
    }

    @Test
    @DisplayName("A button far down a page that scrolls smoothly takes the click")
    void farDownASmoothPage() {
        UserActions.click(page, Harness.FAR_BUTTON);
        Checks.hasText(page, Harness.FAR_TEXT, "Clicked");
    }

    @Test
    @DisplayName("A heading that fades in as it is scrolled to is found: the check scrolls to it, as a visitor would")
    void fadesInWhenScrolledTo() {
        Checks.isShown(page, Harness.REVEALED_HEADING);
        Checks.hasText(page, Harness.REVEALED_HEADING, "Revealed on scroll");
    }

    @Test
    @DisplayName("Actions do what their steps say, and the steps say it")
    void actionsDoWhatTheySay() {
        UserActions.click(page, Harness.ADD_BUTTON);
        UserActions.click(page, Harness.ADD_BUTTON);
        Checks.hasText(page, Harness.COUNT, "2");
        UserActions.type(page, Harness.NAME_FIELD, "Ann");
        Checks.hasValue(page, Harness.NAME_FIELD, "Ann");
        UserActions.clear(page, Harness.NAME_FIELD);
        Checks.hasValue(page, Harness.NAME_FIELD, "");
        UserActions.typeSecret(page, Harness.NAME_FIELD, "hunter2");
        UserActions.tick(page, Harness.AGREE_BOX);
        assertTrue(Harness.AGREE_BOX.locator(page).isChecked(), "tick should tick the box.");
        UserActions.untick(page, Harness.AGREE_BOX);
        assertTrue(!Harness.AGREE_BOX.locator(page).isChecked(), "untick should untick the box.");
        UserActions.choose(page, Harness.COLOUR_LIST, "Blue");
        Checks.hasValue(page, Harness.COLOUR_LIST, "Blue");
        String read = UserActions.readText(page, Harness.SPACED_TEXT);
        assertTrue("Hello world".equals(read), "readText should read \"Hello world\"; it read \"" + read + "\".");
        List<String> expected = List.of(
                "Click the add button",
                "Click the add button",
                "Check that the count says \"2\"",
                "Type \"Ann\" into the name field",
                "Check that the name field holds \"Ann\"",
                "Clear the name field",
                "Check that the name field holds \"\"",
                "Type the secret into the name field",
                "Tick the agree box",
                "Untick the agree box",
                "Choose \"Blue\" in the colour list",
                "Check that the colour list holds \"Blue\"",
                "Read the spaced text: \"Hello world\"");
        assertTrue(StepLog.steps().equals(expected), "The step log should read, in order:\n" + expected + "\nIt read:\n" + StepLog.steps());
        assertTrue(StepLog.steps().stream().noneMatch(step -> step.contains("hunter2")), "A secret must never be logged.");
    }

    // ---- helpers ---------------------------------------------------------------------------------

    /** The check's failure: that it failed, and exactly what it said. */
    private static void saysAtFirst(Runnable check, String start) {
        AssertionError failure = failureOf(check);
        assertTrue(String.valueOf(failure.getMessage()).startsWith(start), "The failure should start:\n  " + start + "\nIt said:\n  " + failure.getMessage());
    }

    private static void says(Runnable check, String message) {
        AssertionError failure = failureOf(check);
        assertTrue(message.equals(failure.getMessage()), "The failure should say:\n  " + message + "\nIt said:\n  " + failure.getMessage());
    }

    private static AssertionError failureOf(Runnable check) {
        try {
            check.run();
        } catch (AssertionError failure) {
            return failure;
        }
        throw new AssertionError("The check passed, and it should have failed.");
    }

    private static String read(Path file) throws IOException {
        return Files.readString(file, StandardCharsets.UTF_8);
    }
}
