// Generated by Suite Builder from a crawl of the site. A run that stops early when its tests keep failing the same way.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests;

import net.atos.tests.core.SiteConfig;
import net.atos.tests.core.StepLog;

import org.junit.jupiter.api.extension.ConditionEvaluationResult;
import org.junit.jupiter.api.extension.ExecutionCondition;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.TestWatcher;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * A run stops early when its tests keep failing the same way: after 5 tests in a row
 * fail for the same reason (the site is down, a wall the suite cannot pass), the tests left are
 * skipped, saying why, instead of each waiting out its timeouts against a site that is not there.
 * Two reasons are the same when they differ only in what they name: an address, a quoted text, a
 * number. A test that passes starts the count again. -DstopAfter=n sets how many (0: never stop).
 * The link report runs first; when it could not reach the site at all, the run stops at once.
 */
public final class StopEarly implements TestWatcher, ExecutionCondition {
    private static final int STOP_AFTER = Integer.parseInt(SiteConfig.value("stopAfter", "5"));
    private static String lastWay;
    private static int inARow;
    /** Why the run stopped; null while it goes on. */
    private static volatile String stopped;

    @Override
    public ConditionEvaluationResult evaluateExecutionCondition(ExtensionContext test) {
        if (stopped == null || test.getTestMethod().isEmpty()) return ConditionEvaluationResult.enabled("the run goes on");
        return ConditionEvaluationResult.disabled("not run: the run stopped early, " + stopped);
    }

    @Override
    public void testFailed(ExtensionContext test, Throwable cause) {
        failed(StepLog.reason(cause), test.getRequiredTestClass().getSimpleName().equals("LinkReportTest"));
    }

    /** One count for the whole run, whichever class's extension and thread report it. */
    // Decision: G-144
    private static synchronized void failed(String reason, boolean linkReport) {
        String way = StepLog.way(reason);
        if (linkReport && way.equals("the site cannot be reached") && STOP_AFTER > 0 && stopped == null) {
            stopped = "the link report could not reach the site (" + reason + ")";
            System.out.println("\n   STOPPING EARLY: " + stopped + ".\n   The tests left are skipped; fix that first, then run again."
                    + " (-DstopAfter=0 runs every test whatever happens.)\n");
            return;
        }
        inARow = way.equals(lastWay) ? inARow + 1 : 1;
        lastWay = way;
        if (STOP_AFTER > 0 && inARow >= STOP_AFTER && stopped == null) {
            stopped = inARow + " tests in a row failed the same way (" + reason + ")";
            System.out.println("\n   STOPPING EARLY: " + stopped + ".\n   The tests left are skipped; fix that first, then run again."
                    + " (-DstopAfter=0 runs every test whatever happens.)\n");
        }
    }

    @Override
    public void testSuccessful(ExtensionContext test) {
        passed();
    }

    private static synchronized void passed() {
        lastWay = null;
        inARow = 0;
    }
}
