// Generated by Suite Builder from a crawl of the site. Which user story a test checks.
// EDIT RULES: do not edit this file; regenerating replaces all of it. Put it on your test classes and methods.
package net.atos.tests;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The user story a test checks: {@code @Story("PROJ-123")}, or with its title,
 * {@code @Story(value = "PROJ-123", title = "A visitor can find the careers page")}. StoryTest prints
 * it as the test starts, so a run's output and a failure point back to the story.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface Story {
    /** The story's id in the team's tracker. */
    String value();

    /** The story's title, as the BA wrote it. */
    String title() default "";
}
