// Generated by Suite Builder from a crawl of the site. Click actions for LpDetailPage6.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage6.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.lpdetailpage6.LpDetail6Elements;
import net.atos.tests.pages.lpdetailpage6.LpDetailPage6;
import net.atos.tests.pages.sitedetailpage4.SiteDetailPage4;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on LpDetailPage6. Clicks that change page return the next page; others return this. */
public class LpDetail6ClickActions {
    private final Page page;

    public LpDetail6ClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to SiteDetailPage4 (e.g. Sustainable Workplace) and waits for it. It opens in a new tab. */
    public SiteDetailPage4 goToSiteDetail4(String name, String name2) {
        Page tab = UserActions.clickOpeningNewTab(page, LpDetail6Elements.getSiteDetail4Link(name, name2));
        return new SiteDetailPage4(tab).get();
    }

    /** Clicks the button "Submit". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDetailPage6 submit() {
        UserActions.click(page, LpDetail6Elements.SUBMIT_BUTTON);
        return new LpDetailPage6(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public LpDetail6VerifyActions verify() {
        return new LpDetail6VerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public LpDetail6ClickActions acceptTerms() {
    //     UserActions.click(page, LpDetail6Elements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
