// Generated by Suite Builder from a crawl of the site. Locators for ClientSuccessPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.clientsuccess;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /en/client-success.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum ClientSuccessElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Client Success Stories": every crawled page of this type showed it. */
    CLIENT_SUCCESS_STORIES_HEADING(page -> Headings.named(page, "Client Success Stories")),
    /** Heading "Your Challenges, Our Solutions": every crawled page of this type showed it. */
    YOUR_CHALLENGES_OUR_SOLUTIONS_HEADING(page -> Headings.named(page, "Your Challenges, Our Solutions")),
    /** Heading "Client Stories Spotlight": every crawled page of this type showed it. */
    CLIENT_STORIES_SPOTLIGHT_HEADING(page -> Headings.named(page, "Client Stories Spotlight")),
    /** Heading "Transforming Defra's Digital Workplace with Sustainable IT Solutions": every crawled page of this type showed it. */
    TRANSFORMING_DEFRA_S_DIGITAL_WORKPLACE_WITH_SUSTAINABLE_IT_SOLUTIONS_HEADING(page -> Headings.named(page, "Transforming Defra's Digital Workplace with Sustainable IT Solutions")),
    /** Heading "Unlocking the power of data with project Triton": every crawled page of this type showed it. */
    UNLOCKING_THE_POWER_OF_DATA_WITH_PROJECT_TRITON_HEADING(page -> Headings.named(page, "Unlocking the power of data with project Triton")),
    /** Heading "Digitizing pharmaceutical manufacturing methods": every crawled page of this type showed it. */
    DIGITIZING_PHARMACEUTICAL_MANUFACTURING_METHODS_HEADING(page -> Headings.named(page, "Digitizing pharmaceutical manufacturing methods")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: its page read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: its page read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Previous slide (only for visual purpose, links already av...": seen by the crawl on /en/client-success. */
    PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Previous slide (only for visual purpose, links already available just before)']")),
    /** button "Next slide (only for visual purpose, links already availa...": seen by the crawl on /en/client-success. */
    NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Next slide (only for visual purpose, links already available just before)']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    ClientSuccessElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    ClientSuccessElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
