// Generated by Suite Builder from a crawl of the site. Locators for PrivacyCookiesAndOtherPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.privacycookiesandother;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /en/privacy/cookies-and-other-tracking-technologies.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum PrivacyCookiesAndOtherElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Atos Approach to Privacy": every crawled page of this type showed it. */
    ATOS_APPROACH_TO_PRIVACY_HEADING(page -> Headings.named(page, "Atos Approach to Privacy")),
    /** Heading "Cookies and other Tracking Technologies": every crawled page of this type showed it. */
    COOKIES_AND_OTHER_TRACKING_TECHNOLOGIES_HEADING(page -> Headings.named(page, "Cookies and other Tracking Technologies")),
    /** Heading "Cookies on Atos.net": every crawled page of this type showed it. */
    COOKIES_ON_ATOS_NET_HEADING(page -> Headings.named(page, "Cookies on Atos.net")),
    /** Heading "Matomo Analytics": every crawled page of this type showed it. */
    MATOMO_ANALYTICS_HEADING(page -> Headings.named(page, "Matomo Analytics")),
    /** Heading "Contact us": every crawled page of this type showed it. */
    CONTACT_US_HEADING(page -> Headings.named(page, "Contact us")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: its page read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: its page read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    PrivacyCookiesAndOtherElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    PrivacyCookiesAndOtherElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
