// Generated by Suite Builder from a crawl of the site. Implemented by every page class.
// EDIT RULES: do not edit this file; regenerating replaces all of it. Each page's own click() methods go in its own actions class.
package net.atos.tests.core.actions;

/** A page with what can be clicked, reached with {@code page.click()}. */
public interface ClickableAction<T> {
    T click();
}
