// Generated by Suite Builder from a crawl of the site. The "Contact Us" form on SiteDetailPage9, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what SiteDetail9Tasks.fillContactUsForm takes.
package net.atos.tests.pages.sitedetailpage9;

import net.atos.tests.core.SiteConfig;

/**
 * The "Contact Us" form on SiteDetailPage9, as one value: its fields in page order, what
 * {@link SiteDetail9Tasks#fillContactUsForm(ContactUs)} types and chooses. {@code sample()} gives values a test can
 * send; change one with a copy: {@code ContactUs.sample().withPreferredLanguage("...")}.
 */
public record ContactUs(String preferredLanguage, String inquiryType, String inquiry, String firstName, String lastName, String companyOrganizationName, String businessEmailAddress, String country) {

    /**
     * Values any copy of the site takes, each plausible for its field; one can be set for a run on the
     * command line (-DpreferredLanguage=...) or in suite.properties, by its name.
     */
    public static ContactUs sample() {
        return new ContactUs(
                SiteConfig.value("preferredLanguage", "English-GB"),
                SiteConfig.value("inquiryType", "New Solution or Services for Your Business"),
                SiteConfig.value("inquiry", "A test from the suite: please ignore."),
                SiteConfig.value("firstName", "Test First Name"),
                SiteConfig.value("lastName", "Test Last Name"),
                SiteConfig.value("companyOrganizationName", "Test Company/Organization Name"),
                SiteConfig.value("businessEmailAddress", "test@example.com"),
                SiteConfig.value("country", "Afghanistan"));
    }

    /** This ContactUs with preferredLanguage in place of its own. */
    public ContactUs withPreferredLanguage(String preferredLanguage) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }

    /** This ContactUs with inquiryType in place of its own. */
    public ContactUs withInquiryType(String inquiryType) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }

    /** This ContactUs with inquiry in place of its own. */
    public ContactUs withInquiry(String inquiry) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }

    /** This ContactUs with firstName in place of its own. */
    public ContactUs withFirstName(String firstName) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }

    /** This ContactUs with lastName in place of its own. */
    public ContactUs withLastName(String lastName) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }

    /** This ContactUs with companyOrganizationName in place of its own. */
    public ContactUs withCompanyOrganizationName(String companyOrganizationName) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }

    /** This ContactUs with businessEmailAddress in place of its own. */
    public ContactUs withBusinessEmailAddress(String businessEmailAddress) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }

    /** This ContactUs with country in place of its own. */
    public ContactUs withCountry(String country) {
        return new ContactUs(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country);
    }
}
