// Generated by Suite Builder from a crawl of the site. Checks for BlogDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.blogdetail.actions;

import net.atos.tests.pages.blogdetail.BlogDetailPage;
import net.atos.tests.pages.blogdetail.BlogDetailElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on BlogDetailPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class BlogDetailVerifyActions {
    private final Page page;

    public BlogDetailVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public BlogDetailVerifyActions isLoaded() {
        BlogDetailPage here = new BlogDetailPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public BlogDetailVerifyActions isThePageOf(String name) {
        Checks.isOnPath(page, UrlPaths.blogDetail(name));
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public BlogDetailVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Categories\", \"Related posts\")",
                BlogDetailElements.CATEGORIES_HEADING, BlogDetailElements.RELATED_POSTS_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(BlogDetailElements.SOME_HEADING)}. */
    public BlogDetailVerifyActions shows(BlogDetailElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public BlogDetailVerifyActions doesNotShow(BlogDetailElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public BlogDetailVerifyActions says(BlogDetailElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public BlogDetailVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public BlogDetailVerifyActions holds(BlogDetailElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public BlogDetailVerifyActions isEmpty(BlogDetailElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public BlogDetailVerifyActions refusesEmpty(BlogDetailElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public BlogDetailVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, BlogDetailElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
