// Generated by Suite Builder from a crawl of the site. Page object for ClientSuccessClientStoriesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.clientsuccessclientstories;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.CheckableAction;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.EnterableAction;
import net.atos.tests.core.actions.ExecutableTask;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.clientsuccessclientstories.actions.ClientSuccessClientStoriesCheckActions;
import net.atos.tests.pages.clientsuccessclientstories.actions.ClientSuccessClientStoriesClickActions;
import net.atos.tests.pages.clientsuccessclientstories.actions.ClientSuccessClientStoriesEnterActions;
import net.atos.tests.pages.clientsuccessclientstories.actions.ClientSuccessClientStoriesReadActions;
import net.atos.tests.pages.clientsuccessclientstories.actions.ClientSuccessClientStoriesVerifyActions;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /en/client-success/client-stories.
 * Stories call it:  "All Client Stories" (the links that lead here).
 * Get here:         new ClientSuccessClientStoriesPage(page).open()
 *                   from any page: navigateTo().clientSuccessClientStories() (in the "Insights"
 *                   menu)
 * The crawl saw:    1 page of this type (/en/client-success/client-stories); it showed "Atos Client
 *                   Stories", "Celebrating success", "Flender China: Accelerating engineering
 *                   excellence with Agentic AI", "Primetals Technologies accelerates global S/4HANA
 *                   transformation with Atos", "SUNOTEC’s HR transformation for a renewable future"
 *                   and "Translink: End-to-end observability for seamless travel".
 * Proven loaded by: the main heading and the heading "Atos Client Stories" (isLoaded(),
 *                   PROVES_LOADED: what a copy edit leaves alone first).
 * Has a form:       on 1 of 1 page. Sending it on the live site sends real data: read
 *                   ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/en/client-success/client-stories.html (the page's HTML when
 *                   crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/ClientSuccessClientStoriesPage/
 *                   (saved-pages/README.md) and add what it shows to
 *                   ClientSuccessClientStoriesElements.
 * </pre>
 */
public class ClientSuccessClientStoriesPage extends LoadablePage<ClientSuccessClientStoriesPage> implements
        ClickableAction<ClientSuccessClientStoriesClickActions>,
        CheckableAction<ClientSuccessClientStoriesCheckActions>,
        EnterableAction<ClientSuccessClientStoriesEnterActions>,
        ReadableAction<ClientSuccessClientStoriesReadActions>,
        VerifiableAction<ClientSuccessClientStoriesVerifyActions>,
        ExecutableTask<ClientSuccessClientStoriesTasks>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "Client Stories - Atos";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 2b4a63bf
    static final List<ClientSuccessClientStoriesElements> PROVES_LOADED = List.of(
            ClientSuccessClientStoriesElements.MAIN_HEADING,
            ClientSuccessClientStoriesElements.ATOS_CLIENT_STORIES_HEADING);
    // ==== END YOURS (load-proof) ====

    public ClientSuccessClientStoriesPage(Page page) {
        super(page);
    }

    /** Goes to /en/client-success/client-stories and waits until it has fully loaded. */
    public ClientSuccessClientStoriesPage open() {
        navigate(UrlPaths.CLIENT_SUCCESS_CLIENT_STORIES);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.CLIENT_SUCCESS_CLIENT_STORIES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.CLIENT_SUCCESS_CLIENT_STORIES);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (ClientSuccessClientStoriesElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, ClientSuccessClientStoriesElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 200;
    }

    @Override
    public ClientSuccessClientStoriesClickActions click() {
        return new ClientSuccessClientStoriesClickActions(page);
    }

    @Override
    public ClientSuccessClientStoriesCheckActions check() {
        return new ClientSuccessClientStoriesCheckActions(page, true);
    }

    @Override
    public ClientSuccessClientStoriesCheckActions uncheck() {
        return new ClientSuccessClientStoriesCheckActions(page, false);
    }

    @Override
    public ClientSuccessClientStoriesEnterActions enter() {
        return new ClientSuccessClientStoriesEnterActions(page);
    }

    @Override
    public ClientSuccessClientStoriesReadActions read() {
        return new ClientSuccessClientStoriesReadActions(page);
    }

    @Override
    public ClientSuccessClientStoriesVerifyActions verify() {
        return new ClientSuccessClientStoriesVerifyActions(page);
    }

    @Override
    public ClientSuccessClientStoriesTasks execute() {
        return new ClientSuccessClientStoriesTasks(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
