// Generated by Suite Builder from a crawl of the site. Click actions for LpDigitalSovereigntyForPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdigitalsovereigntyfor.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.blogdetail.BlogDetailPage;
import net.atos.tests.pages.lpdigitalsovereigntyfor.LpDigitalSovereigntyForElements;
import net.atos.tests.pages.lpdigitalsovereigntyfor.LpDigitalSovereigntyForPage;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on LpDigitalSovereigntyForPage. Clicks that change page return the next page; others return this. */
public class LpDigitalSovereigntyForClickActions {
    private final Page page;

    public LpDigitalSovereigntyForClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to BlogDetailPage (e.g. Read more - Sovereignty isn’t one-size-fits-all: A pragmatic path to cloud, dat…) and waits for it. */
    public BlogDetailPage goToBlogDetail(String name) {
        UserActions.click(page, LpDigitalSovereigntyForElements.getBlogDetailLink(name));
        return new BlogDetailPage(page).get();
    }

    /** Clicks the button "Previous slide (only for visual purpose, links already av...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyForPage previousSlideOnlyForVisual() {
        UserActions.click(page, LpDigitalSovereigntyForElements.PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new LpDigitalSovereigntyForPage(page);
    }

    /** Clicks the button "Next slide (only for visual purpose, links already availa...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyForPage nextSlideOnlyForVisual() {
        UserActions.click(page, LpDigitalSovereigntyForElements.NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new LpDigitalSovereigntyForPage(page);
    }

    /** Clicks the button "previous arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyForPage previousArrow() {
        UserActions.click(page, LpDigitalSovereigntyForElements.PREVIOUS_ARROW_BUTTON);
        return new LpDigitalSovereigntyForPage(page);
    }

    /** Clicks the button "next arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyForPage nextArrow() {
        UserActions.click(page, LpDigitalSovereigntyForElements.NEXT_ARROW_BUTTON);
        return new LpDigitalSovereigntyForPage(page);
    }

    /** Clicks the button "Polyalert". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyForPage polyalert() {
        UserActions.click(page, LpDigitalSovereigntyForElements.POLYALERT_BUTTON);
        return new LpDigitalSovereigntyForPage(page);
    }

    /** Clicks the button "Polycom". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyForPage polycom() {
        UserActions.click(page, LpDigitalSovereigntyForElements.POLYCOM_BUTTON);
        return new LpDigitalSovereigntyForPage(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public LpDigitalSovereigntyForVerifyActions verify() {
        return new LpDigitalSovereigntyForVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public LpDigitalSovereigntyForClickActions acceptTerms() {
    //     UserActions.click(page, LpDigitalSovereigntyForElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
