// Generated by Suite Builder from a crawl of the site. Tasks for ExerciseRightsRegardingPersonalPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.exerciserightsregardingpersonal;

import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Multi-step tasks on ExerciseRightsRegardingPersonalPage, built from its actions (fill in a form and submit it, say).
 * The crawl's own are below; add more in the YOURS block.
 */
public class ExerciseRightsRegardingPersonalTasks {
    private final Page page;

    public ExerciseRightsRegardingPersonalTasks(Page page) {
        this.page = page;
    }

    /**
     * Fills the "a form" form, field by field in page order, and stops before sending it: a generated
     * test never sends a form (ai/recipes/forms-and-test-data.md). To send it, a story adds {@code .click().submit()}: what the site does then is not something the crawl saw. Its values: {@code ExerciseRightsRegardingPersonalForm.sample()},
     * or a copy with one changed, {@code ExerciseRightsRegardingPersonalForm.sample().withFirstName("...")}.
     */
    public ExerciseRightsRegardingPersonalPage fillForm(ExerciseRightsRegardingPersonalForm form) {
        ExerciseRightsRegardingPersonalPage here = new ExerciseRightsRegardingPersonalPage(page);
        here.enter().firstName(form.firstName()).lastName(form.lastName()).emailAddress(form.emailAddress()).telephoneNumber(form.telephoneNumber()).preferredContactDetails(form.preferredContactDetails()).dataSubjectIsOther(form.dataSubjectIsOther()).atosEmployeeId(form.atosEmployeeId()).jobTitle(form.jobTitle()).gbuDivisionLegalEmployingEntity(form.gbuDivisionLegalEmployingEntity()).country(form.country()).approximateDateOnWhichData(form.approximateDateOnWhichData()).toBetterAssistInFulfilling(form.toBetterAssistInFulfilling()).toHelpUsBetterUnderstand(form.toHelpUsBetterUnderstand());
        return here;
    }

    /**
     * @deprecated Takes the form's record now (G-152): {@code fillForm(ExerciseRightsRegardingPersonalForm.sample())}. This one goes
     * in a later release.
     */
    @Deprecated
    public ExerciseRightsRegardingPersonalPage fillForm(String firstName, String lastName, String emailAddress, String telephoneNumber, String preferredContactDetails, String dataSubjectIsOther, String atosEmployeeId, String jobTitle, String gbuDivisionLegalEmployingEntity, String country, String approximateDateOnWhichData, String toBetterAssistInFulfilling, String toHelpUsBetterUnderstand) {
        return fillForm(new ExerciseRightsRegardingPersonalForm(firstName, lastName, emailAddress, telephoneNumber, preferredContactDetails, dataSubjectIsOther, atosEmployeeId, jobTitle, gbuDivisionLegalEmployingEntity, country, approximateDateOnWhichData, toBetterAssistInFulfilling, toHelpUsBetterUnderstand));
    }

    // ==== YOURS (tasks): safe to edit; regenerating keeps what is between these lines ====
    // One method per task a story names, built from this page's actions (ai/recipes/add-a-task.md), e.g.:
    // public ThankYouPage signUp(String email) {
    //     ExerciseRightsRegardingPersonalPage here = new ExerciseRightsRegardingPersonalPage(page);
    //     here.enter().email(email);
    //     here.check().terms();
    //     return here.click().submit();
    // }
    // ==== END YOURS (tasks) ====
}
