// Generated by Suite Builder from a crawl of the site. Page object for ExerciseRightsRegardingPersonalPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.exerciserightsregardingpersonal;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.CheckableAction;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.EnterableAction;
import net.atos.tests.core.actions.ExecutableTask;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.exerciserightsregardingpersonal.actions.ExerciseRightsRegardingPersonalCheckActions;
import net.atos.tests.pages.exerciserightsregardingpersonal.actions.ExerciseRightsRegardingPersonalClickActions;
import net.atos.tests.pages.exerciserightsregardingpersonal.actions.ExerciseRightsRegardingPersonalEnterActions;
import net.atos.tests.pages.exerciserightsregardingpersonal.actions.ExerciseRightsRegardingPersonalReadActions;
import net.atos.tests.pages.exerciserightsregardingpersonal.actions.ExerciseRightsRegardingPersonalVerifyActions;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /en/exercise-rights-regarding-personal-data.
 * Stories call it:  "here" (the links that lead here).
 * Get here:         new ExerciseRightsRegardingPersonalPage(page).open()
 *                   from SiteDetailPage2: click().goToExerciseRightsRegardingPersonal()
 * The crawl saw:    1 page of this type (/en/exercise-rights-regarding-personal-data); it showed
 *                   "Exercise your rights regarding your Personal Data", "I wish to make a
 *                   complaint concerning the processing of my personal data", "CAPTCHA" and "Data
 *                   Protection information notice for this processing".
 * Proven loaded by: the main heading and the heading "CAPTCHA" (isLoaded(), PROVES_LOADED: what a
 *                   copy edit leaves alone first).
 * Has a form:       on 1 of 1 page. Sending it on the live site sends real data: read
 *                   ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/en/exercise-rights-regarding-personal-data.html (the page's HTML
 *                   when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to
 *                   saved-pages/ExerciseRightsRegardingPersonalPage/ (saved-pages/README.md) and
 *                   add what it shows to ExerciseRightsRegardingPersonalElements.
 * </pre>
 */
public class ExerciseRightsRegardingPersonalPage extends LoadablePage<ExerciseRightsRegardingPersonalPage> implements
        ClickableAction<ExerciseRightsRegardingPersonalClickActions>,
        CheckableAction<ExerciseRightsRegardingPersonalCheckActions>,
        EnterableAction<ExerciseRightsRegardingPersonalEnterActions>,
        ReadableAction<ExerciseRightsRegardingPersonalReadActions>,
        VerifiableAction<ExerciseRightsRegardingPersonalVerifyActions>,
        ExecutableTask<ExerciseRightsRegardingPersonalTasks>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "Exercise your rights regarding your Personal Data - Atos";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default a8931004
    static final List<ExerciseRightsRegardingPersonalElements> PROVES_LOADED = List.of(
            ExerciseRightsRegardingPersonalElements.MAIN_HEADING,
            ExerciseRightsRegardingPersonalElements.CAPTCHA_HEADING);
    // ==== END YOURS (load-proof) ====

    public ExerciseRightsRegardingPersonalPage(Page page) {
        super(page);
    }

    /** Goes to /en/exercise-rights-regarding-personal-data and waits until it has fully loaded. */
    public ExerciseRightsRegardingPersonalPage open() {
        navigate(UrlPaths.EXERCISE_RIGHTS_REGARDING_PERSONAL);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.EXERCISE_RIGHTS_REGARDING_PERSONAL);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.EXERCISE_RIGHTS_REGARDING_PERSONAL);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (ExerciseRightsRegardingPersonalElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, ExerciseRightsRegardingPersonalElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 400;
    }

    @Override
    public ExerciseRightsRegardingPersonalClickActions click() {
        return new ExerciseRightsRegardingPersonalClickActions(page);
    }

    @Override
    public ExerciseRightsRegardingPersonalCheckActions check() {
        return new ExerciseRightsRegardingPersonalCheckActions(page, true);
    }

    @Override
    public ExerciseRightsRegardingPersonalCheckActions uncheck() {
        return new ExerciseRightsRegardingPersonalCheckActions(page, false);
    }

    @Override
    public ExerciseRightsRegardingPersonalEnterActions enter() {
        return new ExerciseRightsRegardingPersonalEnterActions(page);
    }

    @Override
    public ExerciseRightsRegardingPersonalReadActions read() {
        return new ExerciseRightsRegardingPersonalReadActions(page);
    }

    @Override
    public ExerciseRightsRegardingPersonalVerifyActions verify() {
        return new ExerciseRightsRegardingPersonalVerifyActions(page);
    }

    @Override
    public ExerciseRightsRegardingPersonalTasks execute() {
        return new ExerciseRightsRegardingPersonalTasks(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
