// Generated by Suite Builder from a crawl of the site. Locators for ExerciseRightsRegardingPersonalPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.exerciserightsregardingpersonal;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /en/exercise-rights-regarding-personal-data.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum ExerciseRightsRegardingPersonalElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Exercise your rights regarding your Personal Data": every crawled page of this type showed it. */
    EXERCISE_YOUR_RIGHTS_REGARDING_YOUR_PERSONAL_DATA_HEADING(page -> Headings.named(page, "Exercise your rights regarding your Personal Data")),
    /** Heading "I wish to make a complaint concerning the processing of my personal data": every crawled page of this type showed it. */
    I_WISH_TO_MAKE_A_COMPLAINT_CONCERNING_THE_PROCESSING_OF_MY_PERSONAL_DATA_HEADING(page -> Headings.named(page, "I wish to make a complaint concerning the processing of my personal data")),
    /** Heading "CAPTCHA": every crawled page of this type showed it. */
    CAPTCHA_HEADING(page -> Headings.named(page, "CAPTCHA")),
    /** Heading "Data Protection information notice for this processing": every crawled page of this type showed it. */
    DATA_PROTECTION_INFORMATION_NOTICE_FOR_THIS_PROCESSING_HEADING(page -> Headings.named(page, "Data Protection information notice for this processing")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: its page read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: its page read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // A form (from the crawl: nothing was typed, clicked or sent).
    /** text field "First name", required: seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    FIRST_NAME_INPUT(page -> page.locator("xpath=//input[@id='input_1_1']")),
    /** text field "Last name", required: seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    LAST_NAME_INPUT(page -> page.locator("xpath=//input[@id='input_1_10']")),
    /** email field "Email address", required: seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    EMAIL_ADDRESS_INPUT(page -> page.locator("xpath=//input[@id='input_1_4']")),
    /** tel field "Telephone number": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    TELEPHONE_NUMBER_INPUT(page -> page.locator("xpath=//input[@id='input_1_20']")),
    /** dropdown "Preferred contact details", required: seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    PREFERRED_CONTACT_DETAILS_SELECT(page -> page.locator("xpath=//select[@id='input_1_23']")),
    /** checkbox "A candidate for an Atos job": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    A_CANDIDATE_FOR_AN_ATOS_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_27_1']")),
    /** checkbox "An active Atos employee": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    AN_ACTIVE_ATOS_EMPLOYEE_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_27_2']")),
    /** checkbox "A former Atos employee": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    A_FORMER_ATOS_EMPLOYEE_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_27_3']")),
    /** checkbox "Provider Employee / Representative": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    PROVIDER_EMPLOYEE_REPRESENTATIVE_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_27_4']")),
    /** checkbox "Guest at Atos Premises or Events": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    GUEST_AT_ATOS_PREMISES_OR_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_27_5']")),
    /** checkbox "Website visitor": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    WEBSITE_VISITOR_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_27_6']")),
    /** checkbox "Other - please specify in the field below": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    OTHER_PLEASE_SPECIFY_IN_THE_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_27_7']")),
    /** text field "Data Subject is other:": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    DATA_SUBJECT_IS_OTHER_INPUT(page -> page.locator("xpath=//input[@id='input_1_28']")),
    /** text field "Atos employee ID": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    ATOS_EMPLOYEE_ID_INPUT(page -> page.locator("xpath=//input[@id='input_1_8']")),
    /** text field "Job title": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    JOB_TITLE_INPUT(page -> page.locator("xpath=//input[@id='input_1_9']")),
    /** text field "GBU / Division / Legal employing entity (legal only)": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    GBU_DIVISION_LEGAL_EMPLOYING_ENTITY_INPUT(page -> page.locator("xpath=//input[@id='input_1_26']")),
    /** dropdown "Country", required: seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    COUNTRY_SELECT(page -> page.locator("xpath=//select[@id='input_1_22']")),
    /** text field "Approximate date on which data were initially collected": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    APPROXIMATE_DATE_ON_WHICH_DATA_INPUT(page -> page.locator("xpath=//input[@id='input_1_24']")),
    /** checkbox "Right of access: I want to know which personal data is pr...": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    RIGHT_OF_ACCESS_I_WANT_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_29_1']")),
    /** checkbox "Right to rectification: I want to modify and rectify the...": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    RIGHT_TO_RECTIFICATION_I_WANT_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_29_2']")),
    /** checkbox "Right to erasure: I want my personal data not to be proce...": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    RIGHT_TO_ERASURE_I_WANT_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_29_3']")),
    /** checkbox "Right to restriction of processing: I want my personal da...": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    RIGHT_TO_RESTRICTION_OF_PROCESSING_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_29_4']")),
    /** checkbox "Right to object: I don’t want my personal data processed.": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    RIGHT_TO_OBJECT_I_DON_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_29_5']")),
    /** checkbox "I wish to make a complaint concerning the processing of m...": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    I_WISH_TO_MAKE_A_CHECKBOX(page -> page.locator("xpath=//input[@id='choice_1_29_6']")),
    /** text area "To better assist in fulfilling your request, please tell...": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    TO_BETTER_ASSIST_IN_FULFILLING_INPUT(page -> page.locator("xpath=//textarea[@id='input_1_32']")),
    /** text area "To help us better understand your request, please explain...": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    TO_HELP_US_BETTER_UNDERSTAND_INPUT(page -> page.locator("xpath=//textarea[@id='input_1_5']")),
    /** button "Submit": seen by the crawl on /en/exercise-rights-regarding-personal-data. */
    SUBMIT_BUTTON(page -> page.locator("xpath=//input[@id='gform_submit_button_1']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    ExerciseRightsRegardingPersonalElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    ExerciseRightsRegardingPersonalElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
