// Generated by Suite Builder from a crawl of the site. EnterActions for LpOperationalizingAiOvercomingPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpoperationalizingaiovercoming.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.SiteConfig;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.lpoperationalizingaiovercoming.LpOperationalizingAiOvercomingElements;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Text to type into fields on LpOperationalizingAiOvercomingPage.
 * The crawl's own are below; add more (elements to LpOperationalizingAiOvercomingElements, then methods here) in the YOURS block.
 */
public class LpOperationalizingAiOvercomingEnterActions {
    private final Page page;

    public LpOperationalizingAiOvercomingEnterActions(Page page) {
        this.page = page;
    }

    /** Types into the text field "*First Name:". */
    public LpOperationalizingAiOvercomingEnterActions firstName(String text) {
        UserActions.type(page, LpOperationalizingAiOvercomingElements.FIRST_NAME_INPUT, text);
        return this;
    }

    /** Empties the text field "*First Name:". */
    public LpOperationalizingAiOvercomingEnterActions clearFirstName() {
        UserActions.clear(page, LpOperationalizingAiOvercomingElements.FIRST_NAME_INPUT);
        return this;
    }

    /** Types into the text field "*Last Name:". */
    public LpOperationalizingAiOvercomingEnterActions lastName(String text) {
        UserActions.type(page, LpOperationalizingAiOvercomingElements.LAST_NAME_INPUT, text);
        return this;
    }

    /** Empties the text field "*Last Name:". */
    public LpOperationalizingAiOvercomingEnterActions clearLastName() {
        UserActions.clear(page, LpOperationalizingAiOvercomingElements.LAST_NAME_INPUT);
        return this;
    }

    /** Types into the email field "*Business Email Address:". */
    public LpOperationalizingAiOvercomingEnterActions businessEmailAddress(String text) {
        UserActions.type(page, LpOperationalizingAiOvercomingElements.BUSINESS_EMAIL_ADDRESS_INPUT, text);
        return this;
    }

    /** Empties the email field "*Business Email Address:". */
    public LpOperationalizingAiOvercomingEnterActions clearBusinessEmailAddress() {
        UserActions.clear(page, LpOperationalizingAiOvercomingElements.BUSINESS_EMAIL_ADDRESS_INPUT);
        return this;
    }

    /** Types into the text field "*Company Name:". */
    public LpOperationalizingAiOvercomingEnterActions companyName(String text) {
        UserActions.type(page, LpOperationalizingAiOvercomingElements.COMPANY_NAME_INPUT, text);
        return this;
    }

    /** Empties the text field "*Company Name:". */
    public LpOperationalizingAiOvercomingEnterActions clearCompanyName() {
        UserActions.clear(page, LpOperationalizingAiOvercomingElements.COMPANY_NAME_INPUT);
        return this;
    }

    /** Types into the tel field "*Phone Number:". */
    public LpOperationalizingAiOvercomingEnterActions phoneNumber(String text) {
        UserActions.type(page, LpOperationalizingAiOvercomingElements.PHONE_NUMBER_INPUT, text);
        return this;
    }

    /** Empties the tel field "*Phone Number:". */
    public LpOperationalizingAiOvercomingEnterActions clearPhoneNumber() {
        UserActions.clear(page, LpOperationalizingAiOvercomingElements.PHONE_NUMBER_INPUT);
        return this;
    }

    /** Types into the text field "*Job Title:". */
    public LpOperationalizingAiOvercomingEnterActions jobTitle(String text) {
        UserActions.type(page, LpOperationalizingAiOvercomingElements.JOB_TITLE_INPUT, text);
        return this;
    }

    /** Empties the text field "*Job Title:". */
    public LpOperationalizingAiOvercomingEnterActions clearJobTitle() {
        UserActions.clear(page, LpOperationalizingAiOvercomingElements.JOB_TITLE_INPUT);
        return this;
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public LpOperationalizingAiOvercomingVerifyActions verify() {
        return new LpOperationalizingAiOvercomingVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per field, e.g.:
    // public LpOperationalizingAiOvercomingEnterActions email(String text) {
    //     UserActions.type(page, LpOperationalizingAiOvercomingElements.EMAIL_INPUT, text);
    //     return this;
    // }
    // A password or other secret: UserActions.typeSecret(page, LpOperationalizingAiOvercomingElements.PASSWORD_INPUT, SiteConfig.secret("password"));
    // A dropdown: UserActions.choose(page, LpOperationalizingAiOvercomingElements.COUNTRY_SELECT, country);
    // ==== END YOURS (actions) ====
}
