// Generated by Suite Builder from a crawl of the site. Checks for LpOperationalizingAiOvercomingPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpoperationalizingaiovercoming.actions;

import net.atos.tests.pages.lpoperationalizingaiovercoming.LpOperationalizingAiOvercomingPage;
import net.atos.tests.pages.lpoperationalizingaiovercoming.LpOperationalizingAiOvercomingElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on LpOperationalizingAiOvercomingPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class LpOperationalizingAiOvercomingVerifyActions {
    private final Page page;

    public LpOperationalizingAiOvercomingVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public LpOperationalizingAiOvercomingVerifyActions isLoaded() {
        LpOperationalizingAiOvercomingPage here = new LpOperationalizingAiOvercomingPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public LpOperationalizingAiOvercomingVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Unlock the Full Value of AI for the Enterprise\", \"Download the white paper\", \"Brian Ray\", \"Dive Deeper\", \"AI Services …\")",
                LpOperationalizingAiOvercomingElements.UNLOCK_THE_FULL_VALUE_OF_AI_FOR_THE_ENTERPRISE_HEADING, LpOperationalizingAiOvercomingElements.DOWNLOAD_THE_WHITE_PAPER_HEADING, LpOperationalizingAiOvercomingElements.BRIAN_RAY_HEADING, LpOperationalizingAiOvercomingElements.DIVE_DEEPER_HEADING, LpOperationalizingAiOvercomingElements.AI_SERVICES_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(LpOperationalizingAiOvercomingElements.SOME_HEADING)}. */
    public LpOperationalizingAiOvercomingVerifyActions shows(LpOperationalizingAiOvercomingElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public LpOperationalizingAiOvercomingVerifyActions doesNotShow(LpOperationalizingAiOvercomingElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public LpOperationalizingAiOvercomingVerifyActions says(LpOperationalizingAiOvercomingElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public LpOperationalizingAiOvercomingVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public LpOperationalizingAiOvercomingVerifyActions holds(LpOperationalizingAiOvercomingElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public LpOperationalizingAiOvercomingVerifyActions isEmpty(LpOperationalizingAiOvercomingElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public LpOperationalizingAiOvercomingVerifyActions refusesEmpty(LpOperationalizingAiOvercomingElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public LpOperationalizingAiOvercomingVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, LpOperationalizingAiOvercomingElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
