// Generated by Suite Builder from a crawl of the site. Page object for SiteDetailPage6.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage6;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.pages.sitedetailpage6.actions.SiteDetail6ClickActions;
import net.atos.tests.pages.sitedetailpage6.actions.SiteDetail6ReadActions;
import net.atos.tests.pages.sitedetailpage6.actions.SiteDetail6VerifyActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 6 pages, like
 *                   /en/services/cybersecurity/hybrid-cloud-security,
 *                   /en/services/digital-workplace/engaged-employee-experience,
 *                   /en/services/cybersecurity/identity-security.
 * Stories call it:  "Hybrid Cloud Security", "Identity Security", "OT Security", "Engaged Employee
 *                   Experience", "Intelligent Collaboration" (the links that lead here).
 * Get here:         new SiteDetailPage6(page).open("services", "cybersecurity",
 *                   "hybrid-cloud-security")
 *                   from any page: navigateTo().hybridCloudSecurity() (in the "Services" menu)
 *                   from any page: navigateTo().identitySecurity() (in the "Services" menu)
 *                   from any page: navigateTo().otSecurity() (in the "Services" menu)
 *                   from BlogDetailPage: click().goToSiteDetail6("atos-and-sap")
 *                   from SiteDetailPage5: click().goToSiteDetail6("digital-workplace",
 *                   "intelligent-collaboration", "")
 *                   from ClientSuccessClientStoriesDetailPage:
 *                   click().goToSiteDetail6("atos-and-sap")
 * The crawl saw:    6 pages of this type (/en/services/cybersecurity/hybrid-cloud-security,
 *                   /en/services/digital-workplace/engaged-employee-experience,
 *                   /en/services/cybersecurity/identity-security, ...); every one showed "Dive
 *                   deeper" and "Contact us for more information.".
 * Proven loaded by: the heading "Dive deeper" and the heading "Contact us for more information."
 *                   (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/en/services/cybersecurity/hybrid-cloud-security.html,
 *                   crawl/pages/en/services/digital-workplace/engaged-employee-experience.html, ...
 *                   (the page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/SiteDetailPage6/
 *                   (saved-pages/README.md) and add what it shows to SiteDetail6Elements.
 * </pre>
 */
public class SiteDetailPage6 extends LoadablePage<SiteDetailPage6> implements
        ClickableAction<SiteDetail6ClickActions>,
        ReadableAction<SiteDetail6ReadActions>,
        VerifiableAction<SiteDetail6VerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/en/*/*/*", "/en/alliances-partnerships/*");

    /** A page of this type, as the parameters of open(). */
    public record Example(String name, String name2, String name3) {
    }

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default ac614a2b
    public static final List<Example> EXAMPLES = List.of(
            new Example("services", "cybersecurity", "hybrid-cloud-security"),
            new Example("services", "digital-workplace", "engaged-employee-experience"),
            new Example("services", "cybersecurity", "identity-security"),
            new Example("services", "cybersecurity", "ot-security"),
            new Example("services", "digital-workplace", "intelligent-collaboration"));
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 88e332a3
    static final List<SiteDetail6Elements> PROVES_LOADED = List.of(
            SiteDetail6Elements.DIVE_DEEPER_HEADING,
            SiteDetail6Elements.CONTACT_US_FOR_MORE_INFORMATION_HEADING);
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public SiteDetailPage6(Page page) {
        super(page);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public SiteDetailPage6 open(String name, String name2, String name3) {
        expectedPath = UrlPaths.siteDetail6(name, name2, name3);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(page, expectedPath)
                : WaitActions.waitForUrlShape(page, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);


        for (SiteDetail6Elements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, SiteDetail6Elements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 200;
    }

    @Override
    public SiteDetail6ClickActions click() {
        return new SiteDetail6ClickActions(page);
    }

    @Override
    public SiteDetail6ReadActions read() {
        return new SiteDetail6ReadActions(page);
    }

    @Override
    public SiteDetail6VerifyActions verify() {
        return new SiteDetail6VerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
