// Generated by Suite Builder from a crawl of the site. Locators for SiteDetailPage6.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage6;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.uri.UrlPaths;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 6 pages like /en/services/cybersecurity/hybrid-cloud-security, /en/services/digital-workplace/engaged-employee-experience, /en/services/cybersecurity/identity-security.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum SiteDetail6Elements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Dive deeper": every crawled page of this type showed it. */
    DIVE_DEEPER_HEADING(page -> Headings.named(page, "Dive deeper")),
    /** Heading "Contact us for more information.": every crawled page of this type showed it. */
    CONTACT_US_FOR_MORE_INFORMATION_HEADING(page -> Headings.named(page, "Contact us for more information.")),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Previous slide (only for visual purpose, links already av...": seen by the crawl on /en/services/cybersecurity/hybrid-cloud-security. */
    PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Previous slide (only for visual purpose, links already available just before)']")),
    /** button "Next slide (only for visual purpose, links already availa...": seen by the crawl on /en/services/cybersecurity/hybrid-cloud-security. */
    NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Next slide (only for visual purpose, links already available just before)']")),
    /** button "Play Atos Experience Operations Center (XOC)": seen by the crawl on /en/services/digital-workplace/engaged-employee-experience. */
    PLAY_ATOS_EXPERIENCE_OPERATIONS_CENTER_BUTTON(page -> page.locator("xpath=//div[@aria-label='Play Atos Experience Operations Center (XOC)']")),
    /** button "Play Meet the Atos SAP Practice": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    PLAY_MEET_THE_ATOS_SAP_BUTTON(page -> page.locator("xpath=//div[@aria-label='Play Meet the Atos SAP Practice']")),
    /** button "Go to slide 1": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    GO_TO_SLIDE_1_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 1']")),
    /** button "Go to slide 2": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    GO_TO_SLIDE_2_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 2']")),
    /** button "previous arrow": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    PREVIOUS_ARROW_BUTTON(page -> page.locator("xpath=//div[@aria-label='previous arrow']")),
    /** button "next arrow": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    NEXT_ARROW_BUTTON(page -> page.locator("xpath=//div[@aria-label='next arrow']")),
    /** button "Zentiva": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    ZENTIVA_BUTTON(page -> page.locator("xpath=//div[@aria-label='Zentiva']")),
    /** button "Spadel": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    SPADEL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Spadel']")),
    /** button "Global ITSM": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    GLOBAL_ITSM_BUTTON(page -> page.locator("xpath=//div[@aria-label='Global ITSM']")),
    /** button "Secure service provider": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    SECURE_SERVICE_PROVIDER_BUTTON(page -> page.locator("xpath=//div[@aria-label='Secure service provider']")),
    /** button "Siemens Energy": seen by the crawl on /en/alliances-partnerships/atos-and-sap. */
    SIEMENS_ENERGY_BUTTON(page -> page.locator("xpath=//div[@aria-label='Siemens Energy']")),
    /** button "Play Click to play video": seen by the crawl on /en/services/cybersecurity/ot-security. */
    PLAY_CLICK_TO_PLAY_VIDEO_BUTTON(page -> page.locator("xpath=//div[@id='Introduction']//div[@aria-label='Play Click to play video']")),
    /** button "Play Click to play video": seen by the crawl on /en/services/cybersecurity/ot-security. */
    PLAY_CLICK_TO_PLAY_VIDEO_BUTTON_2(page -> page.locator("xpath=//div[@id='div-bFHgjm4_rKc-znjh']")),
    /** button "previous arrow": seen by the crawl on /en/services/digital-workplace/intelligent-collaboration. */
    PREVIOUS_ARROW_BUTTON_2(page -> page.locator("xpath=//div[@id='n2-ss-47-arrow-previous']")),
    /** button "next arrow": seen by the crawl on /en/services/digital-workplace/intelligent-collaboration. */
    NEXT_ARROW_BUTTON_2(page -> page.locator("xpath=//div[@id='n2-ss-47-arrow-next']")),
    /** button "NHS Trust": seen by the crawl on /en/services/digital-workplace/intelligent-collaboration. */
    NHS_TRUST_BUTTON(page -> page.locator("xpath=//div[@aria-label='NHS Trust']")),
    /** button "Microsoft": seen by the crawl on /en/services/digital-workplace/intelligent-collaboration. */
    MICROSOFT_BUTTON(page -> page.locator("xpath=//div[@aria-label='Microsoft']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    SiteDetail6Elements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    SiteDetail6Elements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    /** A link to BlogDetailPage, e.g. https://atos.net/en/blog/turning-eu-sustainability-regulations-into-design-intelligence-from-compliance-to-a-competitive-advantage. */
    public static PageElement getBlogDetailLink(String name) {
        String href = "/en/blog/" + name;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("BLOG_DETAIL_LINK", "the link to the blog detail page \"" + name + "\"", page -> page.locator(xpath).first());
    }

    /** A link to SiteDetailPage8, e.g. https://atos.net/en/2025/press-release_2025_07_16/20-years-of-trusted-partnership-atos-awarded-golden-certificate-by-sap-as-global-operations-partner. */
    public static PageElement getSiteDetail8Link(String id, String name, String name2) {
        String href = "/en/" + id + "/" + name + "/" + name2;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("SITE_DETAIL8_LINK", "the link to the site detail page8 \"" + id + "/" + name + "/" + name2 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to SiteDetailPage4, e.g. https://atos.net/en/services/digital-workplace/engaged-employee-experience/experience-operations-center. */
    public static PageElement getSiteDetail4Link(String name, String name2, String name3, String name4) {
        String href = "/en/" + name + "/" + name2 + "/" + name3 + "/" + name4;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("SITE_DETAIL4_LINK", "the link to the site detail page4 \"" + name + "/" + name2 + "/" + name3 + "/" + name4 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to ClientSuccessClientStoriesDetailPage, e.g. https://atos.net/en/client-stories/telephony-transformation-for-nhs-trust. */
    public static PageElement getClientSuccessClientStoriesDetailLink(String name) {
        String href = name + "/en/client-stories/telephony-transformation-for-nhs-trust";
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("CLIENT_SUCCESS_CLIENT_STORIES_DETAIL_LINK", "the link to the client success client stories detail page \"" + name + "\"", page -> page.locator(xpath).first());
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
