// Generated by Suite Builder from a crawl of the site. CheckActions for LpCybershieldDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpcybershielddetail.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.SiteConfig;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.lpcybershielddetail.LpCybershieldDetailElements;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Checkboxes and radio buttons on LpCybershieldDetailPage: page.check() checks them, page.uncheck() unchecks them.
 * The crawl's own are below; add more (elements to LpCybershieldDetailElements, then methods here) in the YOURS block.
 */
public class LpCybershieldDetailCheckActions {
    private final Page page;
    private final boolean check;

    public LpCybershieldDetailCheckActions(Page page, boolean check) {
        this.page = page;
        this.check = check;
    }

    /** Ticks the checkbox "Cyber shield" (page.check()), or unticks it (page.uncheck()). */
    public LpCybershieldDetailCheckActions cyberShield() {
        UserActions.setTicked(page, LpCybershieldDetailElements.CYBER_SHIELD_CHECKBOX, check);
        return this;
    }

    /** Ticks the checkbox "Advisories" (page.check()), or unticks it (page.uncheck()). */
    public LpCybershieldDetailCheckActions advisories() {
        UserActions.setTicked(page, LpCybershieldDetailElements.ADVISORIES_CHECKBOX, check);
        return this;
    }

    /** Ticks the checkbox "Cyber threats" (page.check()), or unticks it (page.uncheck()). */
    public LpCybershieldDetailCheckActions cyberThreats() {
        UserActions.setTicked(page, LpCybershieldDetailElements.CYBER_THREATS_CHECKBOX, check);
        return this;
    }

    /** Ticks the checkbox "Incident response" (page.check()), or unticks it (page.uncheck()). */
    public LpCybershieldDetailCheckActions incidentResponse() {
        UserActions.setTicked(page, LpCybershieldDetailElements.INCIDENT_RESPONSE_CHECKBOX, check);
        return this;
    }

    /** Ticks the checkbox "Security Research" (page.check()), or unticks it (page.uncheck()). */
    public LpCybershieldDetailCheckActions securityResearch() {
        UserActions.setTicked(page, LpCybershieldDetailElements.SECURITY_RESEARCH_CHECKBOX, check);
        return this;
    }

    /** Ticks the checkbox "Vulnerabilities" (page.check()), or unticks it (page.uncheck()). */
    public LpCybershieldDetailCheckActions vulnerabilities() {
        UserActions.setTicked(page, LpCybershieldDetailElements.VULNERABILITIES_CHECKBOX, check);
        return this;
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public LpCybershieldDetailVerifyActions verify() {
        return new LpCybershieldDetailVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per checkbox or radio button, e.g.:
    // public LpCybershieldDetailCheckActions terms() {
    //     UserActions.setTicked(page, LpCybershieldDetailElements.TERMS_CHECKBOX, check);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
