// Generated by Suite Builder from a crawl of the site. Links land on the pages they promise.
// EDIT RULES: do not edit this file; regenerating replaces all of it. It is rebuilt from the crawl. Stories go next to it, in this folder (ai/AI-README.md).
package net.atos.tests.cases;

import net.atos.tests.BaseTest;

import net.atos.tests.core.Checks;
import net.atos.tests.pages.alliancespartnershipsdetail.AlliancesPartnershipsDetailPage;
import net.atos.tests.pages.blogdetail.BlogDetailPage;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.ClientSuccessClientStoriesDetailPage;
import net.atos.tests.pages.industriesdetail.IndustriesDetailPage;
import net.atos.tests.pages.industriesdetailpage2.IndustriesDetailPage2;
import net.atos.tests.pages.lpatosthreatresearch.LpAtosThreatResearchPage;
import net.atos.tests.pages.lpcybershielddetail.LpCybershieldDetailPage;
import net.atos.tests.pages.lpdetailpage2.LpDetailPage2;
import net.atos.tests.pages.lpdetailpage3.LpDetailPage3;
import net.atos.tests.pages.lpdetailpage4.LpDetailPage4;
import net.atos.tests.pages.lpdetailpage5.LpDetailPage5;
import net.atos.tests.pages.lpdetailpage6.LpDetailPage6;
import net.atos.tests.pages.lpdigitalsecuritymagazine.LpDigitalSecurityMagazinePage;
import net.atos.tests.pages.lpdigitalsecuritymagazinepage2.LpDigitalSecurityMagazinePage2;
import net.atos.tests.pages.lpdigitalsovereigntyfor.LpDigitalSovereigntyForPage;
import net.atos.tests.pages.newsroom.NewsroomPage;
import net.atos.tests.pages.sitedetail.SiteDetailPage;
import net.atos.tests.pages.sitedetailpage2.SiteDetailPage2;
import net.atos.tests.pages.sitedetailpage3.SiteDetailPage3;
import net.atos.tests.pages.sitedetailpage4.SiteDetailPage4;
import net.atos.tests.pages.sitedetailpage5.SiteDetailPage5;
import net.atos.tests.pages.sitedetailpage6.SiteDetailPage6;
import net.atos.tests.pages.sitedetailpage7.SiteDetailPage7;
import net.atos.tests.pages.sitedetailpage8.SiteDetailPage8;
import net.atos.tests.pages.sitedetailpage9.SiteDetailPage9;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/** The header and footer links, and links between page types found by the crawl, land where they should. */
@Tag("navigation")
class NavigationTest extends BaseTest {

    @Test
    @DisplayName("header \"Contact us\" lands on SiteDetailPage2 (/en/contact-us)")
    void headerContactUs() {
        new SiteDetailPage(page).open("en").navigateTo().contactUs().verify().isLoaded();
    }

    @Test
    @DisplayName("header \"Join us\" lands on /en/join-us")
    void headerJoinUs() {
        new SiteDetailPage(page).open("en").navigateTo().joinUs();
        Checks.isOnPath(page, "/en/join-us");
    }

    @Test
    @DisplayName("footer \"Accessibility Statement\" lands on /en/accessibility-statement")
    void footerAccessibilityStatement() {
        new SiteDetailPage(page).open("en").navigateTo().accessibilityStatement();
        Checks.isOnPath(page, "/en/accessibility-statement");
    }

    @Test
    @DisplayName("footer \"Terms of use\" lands on SiteDetailPage2 (/en/terms-and-conditions)")
    void footerTermsOfUse() {
        new SiteDetailPage(page).open("en").navigateTo().termsOfUse().verify().isLoaded();
    }

    @Test
    @DisplayName("footer \"Privacy\" lands on SiteDetailPage2 (/en/privacy)")
    void footerPrivacy() {
        new SiteDetailPage(page).open("en").navigateTo().privacy().verify().isLoaded();
    }

    @Test
    @DisplayName("footer \"Homepage\" lands on SiteDetailPage (/en/)")
    void footerHomepage() {
        new SiteDetailPage(page).open("en").navigateTo().homepage().verify().isLoaded();
    }

    @Test
    @DisplayName("/en/expert/neil-milliken -> /en/contact-us lands on SiteDetailPage2")
    void siteDetail2LinksToSiteDetail2() {
        new SiteDetailPage2(page).open("expert", "neil-milliken").click().goToSiteDetail2("contact-us").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/future-makers-research-community -> /en/blog/preparing-your-workforce-for-the-age-of-agentic-ai lands on BlogDetailPage")
    void siteDetail3LinksToBlogDetail() {
        new SiteDetailPage3(page).open("future-makers-research-community").click().goToBlogDetail("preparing-your-workforce-for-the-age-of-agentic-ai").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/future-makers-research-community -> /en/lp/agentic-ai-hackathon lands on LpDetailPage")
    void siteDetail3LinksToLpDetail() {
        new SiteDetailPage3(page).open("future-makers-research-community").click().goToLpDetail("agentic-ai-hackathon").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/future-makers-research-community -> /en/lp/world-creativity-innovation-week lands on LpDetailPage2")
    void siteDetail3LinksToLpDetail2() {
        new SiteDetailPage3(page).open("future-makers-research-community").click().goToLpDetail2("world-creativity-innovation-week").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/building-sovereign-agentic-ai -> /en/blog/the-future-of-humans-and-ai-in-the-digital-workplace lands on BlogDetailPage")
    void blogDetailLinksToBlogDetail() {
        new BlogDetailPage(page).open("building-sovereign-agentic-ai").click().goToBlogDetail("the-future-of-humans-and-ai-in-the-digital-workplace").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/building-sovereign-agentic-ai -> /en/expert/adrien-flambeaux lands on SiteDetailPage2")
    void blogDetailLinksToSiteDetail2() {
        new BlogDetailPage(page).open("building-sovereign-agentic-ai").click().goToSiteDetail2("expert", "adrien-flambeaux").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/building-ai-capability-through-gamified-learning -> /en/alliances-partnerships/atos-and-aws lands on SiteDetailPage4")
    void blogDetailLinksToSiteDetail4() {
        new BlogDetailPage(page).open("building-ai-capability-through-gamified-learning").click().goToSiteDetail4("alliances-partnerships", "atos-and-aws").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/regenerative-it-sustainable-technology-environmental-stewardship -> /en/2024/press-release_2024_11_04/atos-sustainable-workplace-research-finds-device-lifespan-can-double-while-still-delighting-users lands on SiteDetailPage8")
    void blogDetailLinksToSiteDetail8() {
        new BlogDetailPage(page).open("regenerative-it-sustainable-technology-environmental-stewardship").click().goToSiteDetail8("2024", "press-release_2024_11_04", "atos-sustainable-workplace-research-finds-device-lifespan-can-double-while-still-delighting-users").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/hybrid-clouds-carbon-footprint-the-intersection-of-technology-and-sustainability -> /en/portfolio/accelerate-your-journey-to-digital-net-zero lands on ExpertDetailPage")
    void blogDetailLinksToExpertDetail() {
        new BlogDetailPage(page).open("hybrid-clouds-carbon-footprint-the-intersection-of-technology-and-sustainability").click().goToExpertDetail("accelerate-your-journey-to-digital-net-zero").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/how-sports-data-enables-media-to-tell-the-stories-of-sport -> /en/sports-and-major-events/olympic-paralympic-games lands on IndustriesDetailPage2")
    void blogDetailLinksToIndustriesDetail2() {
        new BlogDetailPage(page).open("how-sports-data-enables-media-to-tell-the-stories-of-sport").click().goToIndustriesDetail2("sports-and-major-events", "olympic-paralympic-games").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/building-sovereign-agentic-ai -> /en/lp/digital-sovereignty-an-atos-strategic-growth-pillar lands on LpDigitalSovereigntyAnPage")
    void blogDetailLinksToLpDigitalSovereigntyAn() {
        new BlogDetailPage(page).open("building-sovereign-agentic-ai").click().goToLpDigitalSovereigntyAn().verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/generative-ai-at-work-how-to-master-human-machine-collaboration-part-1 -> /en/solutions/atos-digital-workplace lands on SiteDetailPage5")
    void blogDetailLinksToSiteDetail5() {
        new BlogDetailPage(page).open("generative-ai-at-work-how-to-master-human-machine-collaboration-part-1").click().goToSiteDetail5("solutions", "atos-digital-workplace").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/practical-roadmap-for-ai-in-sap-environments -> /en/client-success/client-stories/how-swiss-post-uses-sap-to-deliver-the-future lands on ClientSuccessClientStoriesDetailPage")
    void blogDetailLinksToClientSuccessClientStoriesDetail() {
        new BlogDetailPage(page).open("practical-roadmap-for-ai-in-sap-environments").click().goToClientSuccessClientStoriesDetail("how-swiss-post-uses-sap-to-deliver-the-future").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/practical-roadmap-for-ai-in-sap-environments -> /en/alliances-partnerships/atos-and-sap lands on SiteDetailPage6")
    void blogDetailLinksToSiteDetail6() {
        new BlogDetailPage(page).open("practical-roadmap-for-ai-in-sap-environments").click().goToSiteDetail6("atos-and-sap").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/blog/cloud-security-in-the-age-of-ai -> /en/lp/digital-security-magazine-17/three-steps-to-managing-secure-third-party-access-in-your-supply-chain lands on LpDetailPage4")
    void blogDetailLinksToLpDetail4() {
        new BlogDetailPage(page).open("cloud-security-in-the-age-of-ai").click().goToLpDetail4("digital-security-magazine-17", "three-steps-to-managing-secure-third-party-access-in-your-supply-chain").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-workplace/adaptive-service-desk-local-support -> /en/2026/awards_2026_03_30/atos-wins-innovation-technology-of-the-year-at-the-service-desk-institute-awards-2026 lands on SiteDetailPage8")
    void siteDetail4LinksToSiteDetail8() {
        new SiteDetailPage4(page).open("services", "digital-workplace", "adaptive-service-desk-local-support").click().goToSiteDetail8("2026", "awards_2026_03_30", "atos-wins-innovation-technology-of-the-year-at-the-service-desk-institute-awards-2026").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/data-and-ai/data-services -> /en/client-success/client-stories/scottish-water-transforms-wastewater-network-management lands on ClientSuccessClientStoriesDetailPage")
    void siteDetail4LinksToClientSuccessClientStoriesDetail() {
        new SiteDetailPage4(page).open("services", "data-and-ai", "data-services").click().goToClientSuccessClientStoriesDetail("scottish-water-transforms-wastewater-network-management").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery -> /en/blog/beyond-the-completed-migration-the-case-for-continuous-modernization lands on BlogDetailPage")
    void siteDetail4LinksToBlogDetail() {
        new SiteDetailPage4(page).open("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery").click().goToBlogDetail("beyond-the-completed-migration-the-case-for-continuous-modernization").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-applications/application-services -> /en/services/digital-applications/application-services/transformation-scale lands on SiteDetailPage4")
    void siteDetail4LinksToSiteDetail4() {
        new SiteDetailPage4(page).open("services", "digital-applications", "application-services").click().goToSiteDetail4("services", "digital-applications", "application-services", "transformation-scale").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-applications/application-services -> /en/contact-us lands on SiteDetailPage2")
    void siteDetail4LinksToSiteDetail2() {
        new SiteDetailPage4(page).open("services", "digital-applications", "application-services").click().goToSiteDetail2("contact-us").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery -> /en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery/digital-advisor lands on SiteDetailPage7")
    void siteDetail4LinksToSiteDetail7() {
        new SiteDetailPage4(page).open("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery").click().goToSiteDetail7("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery", "digital-advisor").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-applications/application-services -> /en/lp/isg-eu-ai-driven-app-services lands on LpDetailPage")
    void siteDetail4LinksToLpDetail() {
        new SiteDetailPage4(page).open("services", "digital-applications", "application-services").click().goToLpDetail("isg-eu-ai-driven-app-services").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/smart-platforms/dynatrace -> /en/lp/autonomous-ai-driven-operations lands on SiteDetailPage5")
    void siteDetail4LinksToSiteDetail5() {
        new SiteDetailPage4(page).open("services", "smart-platforms", "dynatrace").click().goToSiteDetail5("lp", "autonomous-ai-driven-operations").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-workplace/sustainability -> /en/lp/sustainable-workplace-research-paper lands on LpDetailPage2")
    void siteDetail4LinksToLpDetail2() {
        new SiteDetailPage4(page).open("services", "digital-workplace", "sustainability").click().goToLpDetail2("sustainable-workplace-research-paper").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/modern-it-infrastructure -> /en/2025/news_2025_02_19/atos-cloud-backup-for-aws-powered-by-dell-technologies-centralizes-the-management-of-data-replication-and-data-recovery-in-the-cloud-and-on-premises lands on SiteDetailPage8")
    void siteDetail5LinksToSiteDetail8() {
        new SiteDetailPage5(page).open("services", "cloud-and-modern-infrastructure", "modern-it-infrastructure").click().goToSiteDetail8("2025", "news_2025_02_19", "atos-cloud-backup-for-aws-powered-by-dell-technologies-centralizes-the-management-of-data-replication-and-data-recovery-in-the-cloud-and-on-premises").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/advisory -> /en/services/cloud-and-modern-infrastructure/advisory/cloud-advisory-services lands on SiteDetailPage4")
    void siteDetail5LinksToSiteDetail4() {
        new SiteDetailPage5(page).open("services", "cloud-and-modern-infrastructure", "advisory").click().goToSiteDetail4("services", "cloud-and-modern-infrastructure", "advisory", "cloud-advisory-services").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/advisory -> /en/blog/go-beyond-cloud-first-be-cloud-smart lands on BlogDetailPage")
    void siteDetail5LinksToBlogDetail() {
        new SiteDetailPage5(page).open("services", "cloud-and-modern-infrastructure", "advisory").click().goToBlogDetail("go-beyond-cloud-first-be-cloud-smart").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-workplace/accessibility-services -> /en/expert/neil-milliken lands on SiteDetailPage2")
    void siteDetail5LinksToSiteDetail2() {
        new SiteDetailPage5(page).open("services", "digital-workplace", "accessibility-services").click().goToSiteDetail2("expert", "neil-milliken").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/modern-it-infrastructure -> /en/lp/zero-trust-networking-whitepaper lands on LpDetailPage3")
    void siteDetail5LinksToLpDetail3() {
        new SiteDetailPage5(page).open("services", "cloud-and-modern-infrastructure", "modern-it-infrastructure").click().goToLpDetail3("zero-trust-networking-whitepaper").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/alliances-partnerships/atos-and-aws/agentX -> /en/alliances-partnerships/atos-and-aws lands on SiteDetailPage4")
    void alliancesPartnershipsDetailLinksToSiteDetail4() {
        new AlliancesPartnershipsDetailPage(page).open("atos-and-aws", "agentX").click().goToSiteDetail4("alliances-partnerships", "atos-and-aws").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/alliances-partnerships/atos-and-aws/agentX -> /en/contact-us lands on SiteDetailPage2")
    void alliancesPartnershipsDetailLinksToSiteDetail2() {
        new AlliancesPartnershipsDetailPage(page).open("atos-and-aws", "agentX").click().goToSiteDetail2("contact-us").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/alliances-partnerships/atos-and-aws/agentX -> /en/alliances-partnerships/atos-and-aws/agentx lands on AlliancesPartnershipsDetailPage")
    void alliancesPartnershipsDetailLinksToAlliancesPartnershipsDetail() {
        new AlliancesPartnershipsDetailPage(page).open("atos-and-aws", "agentX").click().goToAlliancesPartnershipsDetail("atos-and-aws", "agentx").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/client-success/client-stories/primetals-sap-s4hana-transformation-atos -> /en/client-success/client-stories/one-erp-a-standardized-sap-s-4hana-system-for-enhanced-healthcare lands on ClientSuccessClientStoriesDetailPage")
    void clientSuccessClientStoriesDetailLinksToClientSuccessClientStoriesDetail() {
        new ClientSuccessClientStoriesDetailPage(page).open("primetals-sap-s4hana-transformation-atos").click().goToClientSuccessClientStoriesDetail("one-erp-a-standardized-sap-s-4hana-system-for-enhanced-healthcare").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/client-success/client-stories/primetals-sap-s4hana-transformation-atos -> /en/alliances-partnerships/atos-and-sap lands on SiteDetailPage6")
    void clientSuccessClientStoriesDetailLinksToSiteDetail6() {
        new ClientSuccessClientStoriesDetailPage(page).open("primetals-sap-s4hana-transformation-atos").click().goToSiteDetail6("atos-and-sap").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/client-success/client-stories/misumi-usa-automating-with-amazon-bedrock -> /en/alliances-partnerships/atos-and-aws lands on SiteDetailPage4")
    void clientSuccessClientStoriesDetailLinksToSiteDetail4() {
        new ClientSuccessClientStoriesDetailPage(page).open("misumi-usa-automating-with-amazon-bedrock").click().goToSiteDetail4("alliances-partnerships", "atos-and-aws").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cybersecurity/hybrid-cloud-security -> /en/blog/turning-eu-sustainability-regulations-into-design-intelligence-from-compliance-to-a-competitive-advantage lands on BlogDetailPage")
    void siteDetail6LinksToBlogDetail() {
        new SiteDetailPage6(page).open("services", "cybersecurity", "hybrid-cloud-security").click().goToBlogDetail("turning-eu-sustainability-regulations-into-design-intelligence-from-compliance-to-a-competitive-advantage").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-workplace/engaged-employee-experience -> /en/services/digital-workplace/engaged-employee-experience/experience-operations-center lands on SiteDetailPage4")
    void siteDetail6LinksToSiteDetail4() {
        new SiteDetailPage6(page).open("services", "digital-workplace", "engaged-employee-experience").click().goToSiteDetail4("services", "digital-workplace", "engaged-employee-experience", "experience-operations-center").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/digital-workplace/intelligent-collaboration -> /en/client-stories/telephony-transformation-for-nhs-trust lands on ClientSuccessClientStoriesDetailPage")
    void siteDetail6LinksToClientSuccessClientStoriesDetail() {
        new SiteDetailPage6(page).open("services", "digital-workplace", "intelligent-collaboration").click().goToClientSuccessClientStoriesDetail("").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/isg-digital-sustainability-2025 -> /en/services/digital-workplace/sustainability lands on SiteDetailPage4")
    void lpDetail2LinksToSiteDetail4() {
        new LpDetailPage2(page).open("isg-digital-sustainability-2025").click().goToSiteDetail4("services", "digital-workplace", "sustainability").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/sustainable-workplace-research-paper -> /en/blog/five-myths-about-workplace-sustainability lands on BlogDetailPage")
    void lpDetail2LinksToBlogDetail() {
        new LpDetailPage2(page).open("sustainable-workplace-research-paper").click().goToBlogDetail("five-myths-about-workplace-sustainability").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/isg-digital-sustainability-2025 -> /en/2026/press-release_2026_02_02/atos-positioned-as-a-leader-in-the-isg-for-digital-sustainability-it-solutions-services-europe lands on SiteDetailPage8")
    void lpDetail2LinksToSiteDetail8() {
        new LpDetailPage2(page).open("isg-digital-sustainability-2025").click().goToSiteDetail8("2026", "press-release_2026_02_02", "atos-positioned-as-a-leader-in-the-isg-for-digital-sustainability-it-solutions-services-europe").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery/digital-engineer -> /en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery/digital-advisor lands on SiteDetailPage7")
    void siteDetail7LinksToSiteDetail7() {
        new SiteDetailPage7(page).open("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery", "digital-engineer").click().goToSiteDetail7("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery", "digital-advisor").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery/digital-advisor -> /en/blog/beyond-the-completed-migration-the-case-for-continuous-modernization lands on BlogDetailPage")
    void siteDetail7LinksToBlogDetail() {
        new SiteDetailPage7(page).open("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery", "digital-advisor").click().goToBlogDetail("beyond-the-completed-migration-the-case-for-continuous-modernization").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/freedom-ai-age -> /en/client-success/client-stories/lilly-the-ai-powered-agent lands on ClientSuccessClientStoriesDetailPage")
    void lpDetail3LinksToClientSuccessClientStoriesDetail() {
        new LpDetailPage3(page).open("freedom-ai-age").click().goToClientSuccessClientStoriesDetail("lilly-the-ai-powered-agent").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-security-magazine-20th-edition -> /en/lp/digital-security-magazine-20th-edition/ai-data-governance lands on LpDetailPage4")
    void lpDigitalSecurityMagazineLinksToLpDetail4() {
        new LpDigitalSecurityMagazinePage(page).open().click().goToLpDetail4("digital-security-magazine-20th-edition", "ai-data-governance").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-security-magazine-20th-edition -> /en/expert/zeina-zakhour lands on ExpertDetailPage")
    void lpDigitalSecurityMagazineLinksToExpertDetail() {
        new LpDigitalSecurityMagazinePage(page).open().click().goToExpertDetail("zeina-zakhour").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data -> /en/lp/digital-security-magazine-20th-edition lands on LpDigitalSecurityMagazinePage")
    void lpDetail4LinksToLpDigitalSecurityMagazine() {
        new LpDetailPage4(page).open("digital-security-magazine-20th-edition", "responsible-ai-starts-with-responsible-data").click().goToLpDigitalSecurityMagazine().verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data -> /en/expert/yann-dietrich lands on SiteDetailPage2")
    void lpDetail4LinksToSiteDetail2() {
        new LpDetailPage4(page).open("digital-security-magazine-20th-edition", "responsible-ai-starts-with-responsible-data").click().goToSiteDetail2("expert", "yann-dietrich").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data -> /en/lp/digital-security-magazine-20th-edition/ai-data-governance lands on LpDetailPage4")
    void lpDetail4LinksToLpDetail4() {
        new LpDetailPage4(page).open("digital-security-magazine-20th-edition", "responsible-ai-starts-with-responsible-data").click().goToLpDetail4("digital-security-magazine-20th-edition", "ai-data-governance").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data -> /en/expert/chris-mcclean lands on ExpertDetailPage")
    void lpDetail4LinksToExpertDetail() {
        new LpDetailPage4(page).open("digital-security-magazine-20th-edition", "responsible-ai-starts-with-responsible-data").click().goToExpertDetail("chris-mcclean").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/2023/press-release_2023_07_11/atos-successfully-delivers-data-driven-digital-services-to-european-games-2023 -> /en/2023/news_2023_05_03/atos-offers-cutting-edge-ticketing-technology-to-the-european-games-2023 lands on SiteDetailPage8")
    void siteDetail8LinksToSiteDetail8() {
        new SiteDetailPage8(page).open("2023", "press-release_2023_07_11", "atos-successfully-delivers-data-driven-digital-services-to-european-games-2023").click().goToSiteDetail8("2023", "news_2023_05_03", "atos-offers-cutting-edge-ticketing-technology-to-the-european-games-2023").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/2025/news_2025_04_30/atos-achieves-microsoft-private-cloud-solution-partner-designation -> /en/partners-and-channels/atos-and-microsoft lands on SiteDetailPage4")
    void siteDetail8LinksToSiteDetail4() {
        new SiteDetailPage8(page).open("2025", "news_2025_04_30", "atos-achieves-microsoft-private-cloud-solution-partner-designation").click().goToSiteDetail4("partners-and-channels", "atos-and-microsoft").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/2024/press-release_2024_03_14/atos-positioned-as-a-leader-in-the-2024-gartner-magic-quadrant-for-outsourced-digital-workplace-services-report -> /en/lp/gartner-mq-for-odws-2024 lands on LpDetailPage6")
    void siteDetail8LinksToLpDetail6() {
        new SiteDetailPage8(page).open("2024", "press-release_2024_03_14", "atos-positioned-as-a-leader-in-the-2024-gartner-magic-quadrant-for-outsourced-digital-workplace-services-report").click().goToLpDetail6("gartner-mq-for-odws-2024").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/2024/press-release_2024_03_14/atos-positioned-as-a-leader-in-the-2024-gartner-magic-quadrant-for-outsourced-digital-workplace-services-report -> /en/solutions/atos-digital-workplace lands on SiteDetailPage5")
    void siteDetail8LinksToSiteDetail5() {
        new SiteDetailPage8(page).open("2024", "press-release_2024_03_14", "atos-positioned-as-a-leader-in-the-2024-gartner-magic-quadrant-for-outsourced-digital-workplace-services-report").click().goToSiteDetail5("solutions", "atos-digital-workplace").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/2026/press-release_2026_02_02/atos-positioned-as-a-leader-in-the-isg-for-digital-sustainability-it-solutions-services-europe -> /en/lp/isg-digital-sustainability-2025 lands on LpDetailPage2")
    void siteDetail8LinksToLpDetail2() {
        new SiteDetailPage8(page).open("2026", "press-release_2026_02_02", "atos-positioned-as-a-leader-in-the-isg-for-digital-sustainability-it-solutions-services-europe").click().goToLpDetail2("isg-digital-sustainability-2025").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/turkiye -> /en/turkiye/personal-data-protection-law-in-turkiye lands on SiteDetailPage2")
    void siteDetail9LinksToSiteDetail2() {
        new SiteDetailPage9(page).open("turkiye").click().goToSiteDetail2("turkiye", "personal-data-protection-law-in-turkiye").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/turkiye -> /en/turkiye/customerservices-tr lands on SiteDetailPage3")
    void siteDetail9LinksToSiteDetail3() {
        new SiteDetailPage9(page).open("turkiye").click().goToSiteDetail3("turkiye").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/asia-pacific -> /en/client-stories/accelerating-wa-health-system-digitalisation lands on ClientSuccessClientStoriesDetailPage")
    void siteDetail9LinksToClientSuccessClientStoriesDetail() {
        new SiteDetailPage9(page).open("asia-pacific").click().goToClientSuccessClientStoriesDetail("").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/atos-netherlands -> /en/2026/press-release_2026_07_23/atos-launches-atos-sovereign-cloud-a-trusted-modernization-platform-designed-and-engineered-in-the-eu lands on SiteDetailPage8")
    void siteDetail9LinksToSiteDetail8() {
        new SiteDetailPage9(page).open("atos-netherlands").click().goToSiteDetail8("2026", "press-release_2026_07_23", "atos-launches-atos-sovereign-cloud-a-trusted-modernization-platform-designed-and-engineered-in-the-eu").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/industries/healthcare-and-life-sciences -> /en/2025/awards_2025_04_08/atos-named-2025-google-cloud-social-impact-partner-of-the-year-for-crisis-response-and-resilience lands on SiteDetailPage8")
    void industriesDetailLinksToSiteDetail8() {
        new IndustriesDetailPage(page).open("healthcare-and-life-sciences").click().goToSiteDetail8("2025", "awards_2025_04_08", "atos-named-2025-google-cloud-social-impact-partner-of-the-year-for-crisis-response-and-resilience").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/atos-threat-research-center -> /en/lp/cybershield lands on LpCybershieldDetailPage")
    void lpAtosThreatResearchLinksToLpCybershieldDetail() {
        new LpAtosThreatResearchPage(page).open().click().goToLpCybershieldDetail("cybershield").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/cybershield/making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective -> /en/lp/cybershield lands on LpCybershieldDetailPage")
    void lpDetail5LinksToLpCybershieldDetail() {
        new LpDetailPage5(page).open("cybershield", "making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective").click().goToLpCybershieldDetail("cybershield").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/cybershield/making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective -> /en/lp/digital-security-magazine-20th-edition lands on LpDigitalSecurityMagazinePage")
    void lpDetail5LinksToLpDigitalSecurityMagazine() {
        new LpDetailPage5(page).open("cybershield", "making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective").click().goToLpDigitalSecurityMagazine().verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/cybershield/making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective -> /en/lp/digital-security-magazine-18 lands on LpDigitalSecurityMagazinePage2")
    void lpDetail5LinksToLpDigitalSecurityMagazine2() {
        new LpDetailPage5(page).open("cybershield", "making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective").click().goToLpDigitalSecurityMagazine2().verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/cybershield/making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective -> /en/lp/cybershield/anatomy-of-access-windows-device-objects-from-a-security-perspective lands on LpDetailPage5")
    void lpDetail5LinksToLpDetail5() {
        new LpDetailPage5(page).open("cybershield", "making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective").click().goToLpDetail5("cybershield", "anatomy-of-access-windows-device-objects-from-a-security-perspective").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/cybershield/category -> /en/lp/cybershield lands on LpCybershieldDetailPage")
    void lpCybershieldDetailLinksToLpCybershieldDetail() {
        new LpCybershieldDetailPage(page).open("category").click().goToLpCybershieldDetail("cybershield").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/gartner-mq-for-odws-2024 -> /en/digital-workplace/sustainability lands on SiteDetailPage4")
    void lpDetail6LinksToSiteDetail4() {
        new LpDetailPage6(page).open("gartner-mq-for-odws-2024").click().goToSiteDetail4("digital-workplace", "sustainability").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-sovereignty-for-switzerland -> /en/blog/sovereignty-isnt-one-size-fits-all-a-pragmatic-path-to-cloud-data-and-ai-control lands on BlogDetailPage")
    void lpDigitalSovereigntyForLinksToBlogDetail() {
        new LpDigitalSovereigntyForPage(page).open().click().goToBlogDetail("sovereignty-isnt-one-size-fits-all-a-pragmatic-path-to-cloud-data-and-ai-control").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/industries/sports-and-major-events/olympic-paralympic-games -> /en/2024/press-release_2024_09_20/atos-achieves-landmark-it-delivery-for-the-olympic-and-paralympic-games-paris-2024-the-most-digital-and-secure-in-history lands on SiteDetailPage8")
    void industriesDetail2LinksToSiteDetail8() {
        new IndustriesDetailPage2(page).open("sports-and-major-events", "olympic-paralympic-games").click().goToSiteDetail8("2024", "press-release_2024_09_20", "atos-achieves-landmark-it-delivery-for-the-olympic-and-paralympic-games-paris-2024-the-most-digital-and-secure-in-history").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/newsroom -> /en/newsroom/all-news-and-press-releases lands on SiteDetailPage8")
    void newsroomLinksToSiteDetail8() {
        new NewsroomPage(page).open().click().goToSiteDetail8("all-news-and-press-releases").verify().isLoaded();
    }

    @Test
    @DisplayName("/en/newsroom -> /en/newsroom/brand-center lands on NewsroomBrandCenterPage")
    void newsroomLinksToNewsroomBrandCenter() {
        new NewsroomPage(page).open().click().goToNewsroomBrandCenter().verify().isLoaded();
    }

    @Test
    @DisplayName("/en/lp/digital-security-magazine-18 -> /en/expert/zeina-zakhour lands on ExpertDetailPage")
    void lpDigitalSecurityMagazine2LinksToExpertDetail() {
        new LpDigitalSecurityMagazinePage2(page).open().click().goToExpertDetail("zeina-zakhour").verify().isLoaded();
    }
}
