// Generated by Suite Builder from a crawl of the site. What the site as a whole does, as the crawl saw it.
// EDIT RULES: do not edit this file; regenerating replaces all of it. It is rebuilt from the crawl. Stories go next to it, in this folder (ai/AI-README.md).
package net.atos.tests.cases;

import java.util.ArrayList;
import java.util.List;
import net.atos.tests.BaseTest;
import net.atos.tests.core.Checks;
import net.atos.tests.core.CookieBanner;
import net.atos.tests.pages.alliancespartnershipsdetail.AlliancesPartnershipsDetailPage;
import net.atos.tests.pages.blog.BlogPage;
import net.atos.tests.pages.blogdetail.BlogDetailPage;
import net.atos.tests.pages.clientsuccess.ClientSuccessPage;
import net.atos.tests.pages.clientsuccessclientstories.ClientSuccessClientStoriesPage;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.ClientSuccessClientStoriesDetailPage;
import net.atos.tests.pages.eventsdetail.EventsDetailPage;
import net.atos.tests.pages.exerciserightsregardingpersonal.ExerciseRightsRegardingPersonalPage;
import net.atos.tests.pages.expertdetail.ExpertDetailPage;
import net.atos.tests.pages.industries.IndustriesPage;
import net.atos.tests.pages.industriesdetail.IndustriesDetailPage;
import net.atos.tests.pages.industriesdetailpage2.IndustriesDetailPage2;
import net.atos.tests.pages.lpatosthreatresearch.LpAtosThreatResearchPage;
import net.atos.tests.pages.lpcybershielddetail.LpCybershieldDetailPage;
import net.atos.tests.pages.lpdetail.LpDetailPage;
import net.atos.tests.pages.lpdetailpage2.LpDetailPage2;
import net.atos.tests.pages.lpdetailpage3.LpDetailPage3;
import net.atos.tests.pages.lpdetailpage4.LpDetailPage4;
import net.atos.tests.pages.lpdetailpage5.LpDetailPage5;
import net.atos.tests.pages.lpdetailpage6.LpDetailPage6;
import net.atos.tests.pages.lpdigitalsecuritymagazine.LpDigitalSecurityMagazinePage;
import net.atos.tests.pages.lpdigitalsecuritymagazinepage2.LpDigitalSecurityMagazinePage2;
import net.atos.tests.pages.lpdigitalsovereigntyan.LpDigitalSovereigntyAnPage;
import net.atos.tests.pages.lpdigitalsovereigntyfor.LpDigitalSovereigntyForPage;
import net.atos.tests.pages.lpoperationalizingaiovercoming.LpOperationalizingAiOvercomingPage;
import net.atos.tests.pages.newsroom.NewsroomPage;
import net.atos.tests.pages.newsroombrandcenter.NewsroomBrandCenterPage;
import net.atos.tests.pages.privacycookiesandother.PrivacyCookiesAndOtherPage;
import net.atos.tests.pages.sitedetail.SiteDetailPage;
import net.atos.tests.pages.sitedetailpage2.SiteDetailPage2;
import net.atos.tests.pages.sitedetailpage3.SiteDetailPage3;
import net.atos.tests.pages.sitedetailpage4.SiteDetailPage4;
import net.atos.tests.pages.sitedetailpage5.SiteDetailPage5;
import net.atos.tests.pages.sitedetailpage6.SiteDetailPage6;
import net.atos.tests.pages.sitedetailpage7.SiteDetailPage7;
import net.atos.tests.pages.sitedetailpage8.SiteDetailPage8;
import net.atos.tests.pages.sitedetailpage9.SiteDetailPage9;
import net.atos.tests.pages.worldwidelocations.WorldwideLocationsPage;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * What the site as a whole does, as the crawl saw it: each test holds the site to something the crawl
 * saw on it, and fails for a reason its owner would care about. Tagged by kind: -Dgroups=lists, seo,
 * consent, controls.
 */
class SiteTest extends BaseTest {

    @Test
    @Tag("lists")
    @DisplayName("BlogDetailPage still links to each of the 3 SiteDetailPage2 pages it linked to")
    void blogDetailPageLinksToEverySiteDetailPage2() {
        new BlogDetailPage(page).open("from-risk-to-resilience-bridging-legal-compliance-and-technical-execution-in-accessibility");
        Checks.linksToEach(page, "SiteDetailPage2 pages", List.of(
                "https://atos.net/en/contact-us",
                "https://atos.net/en/expert/james-thurston",
                "https://atos.net/en/expert/ken-nakata"));
    }

    @Test
    @Tag("lists")
    @DisplayName("SiteDetailPage still links to each of the 4 BlogDetailPage pages it linked to")
    void siteDetailPageLinksToEveryBlogDetailPage() {
        new SiteDetailPage(page).open("en");
        Checks.linksToEach(page, "BlogDetailPage pages", List.of(
                "https://atos.net/en/blog/building-sovereign-agentic-ai",
                "https://atos.net/en/blog/the-dexops-advantage-better-employee-experiences-fewer-disruptions",
                "https://atos.net/en/blog/build-the-team-behind-the-tools-with-dexops",
                "https://atos.net/en/blog/rethinking-sovereignty-for-agentic-ai"));
    }

    @Test
    @Tag("lists")
    @DisplayName("BlogDetailPage still links to each of the 3 SiteDetailPage4 pages it linked to")
    void blogDetailPageLinksToEverySiteDetailPage4() {
        new BlogDetailPage(page).open("building-ai-capability-through-gamified-learning");
        Checks.linksToEach(page, "SiteDetailPage4 pages", List.of(
                "https://atos.net/en/services/data-and-ai/ai-services",
                "https://atos.net/en/services/data-and-ai",
                "https://atos.net/en/alliances-partnerships/atos-and-aws"));
    }

    @Test
    @Tag("lists")
    @DisplayName("SiteDetailPage4 still links to each of the 3 SiteDetailPage7 pages it linked to")
    void siteDetailPage4LinksToEverySiteDetailPage7() {
        new SiteDetailPage4(page).open("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery");
        Checks.linksToEach(page, "SiteDetailPage7 pages", List.of(
                "https://atos.net/en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery/digital-advisor",
                "https://atos.net/en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery/digital-transformation-engineer",
                "https://atos.net/en/services/cloud-and-modern-infrastructure/cmi-agentic-delivery/digital-engineer"));
    }

    @Test
    @Tag("lists")
    @DisplayName("LpDigitalSecurityMagazinePage still links to each of the 3 LpDetailPage4 pages it linked to")
    void lpDigitalSecurityMagazinePageLinksToEveryLpDetailPage4() {
        new LpDigitalSecurityMagazinePage(page).open();
        Checks.linksToEach(page, "LpDetailPage4 pages", List.of(
                "https://atos.net/en/lp/digital-security-magazine-20th-edition/ai-data-governance",
                "https://atos.net/en/lp/digital-security-magazine-20th-edition/how-synthetic-image-and-video-generation-is-opening-new-ground",
                "https://atos.net/en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data"));
    }

    @Test
    @Tag("seo")
    @DisplayName("SiteDetailPage2 has one main heading (h1)")
    void siteDetailPage2HasOneMainHeading() {
        new SiteDetailPage2(page).open("expert", "neil-milliken");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("AlliancesPartnershipsDetailPage has one main heading (h1)")
    void alliancesPartnershipsDetailPageHasOneMainHeading() {
        new AlliancesPartnershipsDetailPage(page).open("atos-and-aws", "agentX");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDetailPage has one main heading (h1)")
    void lpDetailPageHasOneMainHeading() {
        new LpDetailPage(page).open("isg-eu-ai-driven-app-services");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDetailPage2 has one main heading (h1)")
    void lpDetailPage2HasOneMainHeading() {
        new LpDetailPage2(page).open("world-creativity-innovation-week");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("PrivacyCookiesAndOtherPage has one main heading (h1)")
    void privacyCookiesAndOtherPageHasOneMainHeading() {
        new PrivacyCookiesAndOtherPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDetailPage3 has one main heading (h1)")
    void lpDetailPage3HasOneMainHeading() {
        new LpDetailPage3(page).open("zero-trust-networking-whitepaper");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDigitalSecurityMagazinePage has one main heading (h1)")
    void lpDigitalSecurityMagazinePageHasOneMainHeading() {
        new LpDigitalSecurityMagazinePage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDetailPage4 has one main heading (h1)")
    void lpDetailPage4HasOneMainHeading() {
        new LpDetailPage4(page).open("digital-security-magazine-20th-edition", "responsible-ai-starts-with-responsible-data");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpOperationalizingAiOvercomingPage has one main heading (h1)")
    void lpOperationalizingAiOvercomingPageHasOneMainHeading() {
        new LpOperationalizingAiOvercomingPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("ExerciseRightsRegardingPersonalPage has one main heading (h1)")
    void exerciseRightsRegardingPersonalPageHasOneMainHeading() {
        new ExerciseRightsRegardingPersonalPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("ClientSuccessClientStoriesPage has one main heading (h1)")
    void clientSuccessClientStoriesPageHasOneMainHeading() {
        new ClientSuccessClientStoriesPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("ExpertDetailPage has one main heading (h1)")
    void expertDetailPageHasOneMainHeading() {
        new ExpertDetailPage(page).open("chris-mcclean");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpAtosThreatResearchPage has one main heading (h1)")
    void lpAtosThreatResearchPageHasOneMainHeading() {
        new LpAtosThreatResearchPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDetailPage5 has one main heading (h1)")
    void lpDetailPage5HasOneMainHeading() {
        new LpDetailPage5(page).open("cybershield", "making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpCybershieldDetailPage has one main heading (h1)")
    void lpCybershieldDetailPageHasOneMainHeading() {
        new LpCybershieldDetailPage(page).open("category");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("WorldwideLocationsPage has one main heading (h1)")
    void worldwideLocationsPageHasOneMainHeading() {
        new WorldwideLocationsPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDetailPage6 has one main heading (h1)")
    void lpDetailPage6HasOneMainHeading() {
        new LpDetailPage6(page).open("microsoft-365-copilot-your-ai-powered-future-of-work");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDigitalSovereigntyForPage has one main heading (h1)")
    void lpDigitalSovereigntyForPageHasOneMainHeading() {
        new LpDigitalSovereigntyForPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("IndustriesDetailPage2 has one main heading (h1)")
    void industriesDetailPage2HasOneMainHeading() {
        new IndustriesDetailPage2(page).open("sports-and-major-events", "olympic-paralympic-games");
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("IndustriesPage has one main heading (h1)")
    void industriesPageHasOneMainHeading() {
        new IndustriesPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("NewsroomPage has one main heading (h1)")
    void newsroomPageHasOneMainHeading() {
        new NewsroomPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("NewsroomBrandCenterPage has one main heading (h1)")
    void newsroomBrandCenterPageHasOneMainHeading() {
        new NewsroomBrandCenterPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("BlogPage has one main heading (h1)")
    void blogPageHasOneMainHeading() {
        new BlogPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("LpDigitalSovereigntyAnPage has one main heading (h1)")
    void lpDigitalSovereigntyAnPageHasOneMainHeading() {
        new LpDigitalSovereigntyAnPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("ClientSuccessPage has one main heading (h1)")
    void clientSuccessPageHasOneMainHeading() {
        new ClientSuccessPage(page).open();
        Checks.hasCount(page, "main headings (h1)", page.locator("xpath=//h1"), 1);
    }

    @Test
    @Tag("seo")
    @DisplayName("Every page type has a title of its own")
    void everyPageTypeHasATitleOfItsOwn() {
        List<String> titles = new ArrayList<>();
        new SiteDetailPage(page).open("en");
        titles.add(page.title());
        new SiteDetailPage2(page).open("expert", "neil-milliken");
        titles.add(page.title());
        new SiteDetailPage3(page).open("future-makers-research-community");
        titles.add(page.title());
        new BlogDetailPage(page).open("building-sovereign-agentic-ai");
        titles.add(page.title());
        new SiteDetailPage4(page).open("services", "digital-applications", "application-services");
        titles.add(page.title());
        new SiteDetailPage5(page).open("services", "cloud-and-modern-infrastructure", "advisory");
        titles.add(page.title());
        new AlliancesPartnershipsDetailPage(page).open("atos-and-aws", "agentX");
        titles.add(page.title());
        new EventsDetailPage(page).open("nexthink-experience-2026");
        titles.add(page.title());
        new ClientSuccessClientStoriesDetailPage(page).open("unlocking-the-power-of-data-with-project-triton");
        titles.add(page.title());
        new LpDetailPage(page).open("isg-eu-ai-driven-app-services");
        titles.add(page.title());
        new SiteDetailPage6(page).open("services", "cybersecurity", "hybrid-cloud-security");
        titles.add(page.title());
        new LpDetailPage2(page).open("world-creativity-innovation-week");
        titles.add(page.title());
        new PrivacyCookiesAndOtherPage(page).open();
        titles.add(page.title());
        new SiteDetailPage7(page).open("services", "cloud-and-modern-infrastructure", "cmi-agentic-delivery", "digital-engineer");
        titles.add(page.title());
        new LpDetailPage3(page).open("zero-trust-networking-whitepaper");
        titles.add(page.title());
        new LpDigitalSecurityMagazinePage(page).open();
        titles.add(page.title());
        new LpDetailPage4(page).open("digital-security-magazine-20th-edition", "responsible-ai-starts-with-responsible-data");
        titles.add(page.title());
        new LpOperationalizingAiOvercomingPage(page).open();
        titles.add(page.title());
        new ExerciseRightsRegardingPersonalPage(page).open();
        titles.add(page.title());
        new SiteDetailPage8(page).open("2026", "press-release_2026_10_05", "atos-secures-350-million-application-management-contract-with-metropolitan-police-service");
        titles.add(page.title());
        new ClientSuccessClientStoriesPage(page).open();
        titles.add(page.title());
        new ExpertDetailPage(page).open("chris-mcclean");
        titles.add(page.title());
        new SiteDetailPage9(page).open("canada");
        titles.add(page.title());
        new IndustriesDetailPage(page).open("healthcare-and-life-sciences");
        titles.add(page.title());
        new LpAtosThreatResearchPage(page).open();
        titles.add(page.title());
        new LpDetailPage5(page).open("cybershield", "making-vulnerable-drivers-exploitable-without-hardware-the-byovd-perspective");
        titles.add(page.title());
        new LpCybershieldDetailPage(page).open("category");
        titles.add(page.title());
        new WorldwideLocationsPage(page).open();
        titles.add(page.title());
        new LpDetailPage6(page).open("microsoft-365-copilot-your-ai-powered-future-of-work");
        titles.add(page.title());
        new LpDigitalSovereigntyForPage(page).open();
        titles.add(page.title());
        new IndustriesDetailPage2(page).open("sports-and-major-events", "olympic-paralympic-games");
        titles.add(page.title());
        new IndustriesPage(page).open();
        titles.add(page.title());
        new NewsroomPage(page).open();
        titles.add(page.title());
        new NewsroomBrandCenterPage(page).open();
        titles.add(page.title());
        new LpDigitalSecurityMagazinePage2(page).open();
        titles.add(page.title());
        new BlogPage(page).open();
        titles.add(page.title());
        new LpDigitalSovereigntyAnPage(page).open();
        titles.add(page.title());
        new ClientSuccessPage(page).open();
        titles.add(page.title());
        Checks.allDifferent("page types' titles", List.of("SiteDetailPage", "SiteDetailPage2", "SiteDetailPage3", "BlogDetailPage", "SiteDetailPage4", "SiteDetailPage5", "AlliancesPartnershipsDetailPage", "EventsDetailPage", "ClientSuccessClientStoriesDetailPage", "LpDetailPage", "SiteDetailPage6", "LpDetailPage2", "PrivacyCookiesAndOtherPage", "SiteDetailPage7", "LpDetailPage3", "LpDigitalSecurityMagazinePage", "LpDetailPage4", "LpOperationalizingAiOvercomingPage", "ExerciseRightsRegardingPersonalPage", "SiteDetailPage8", "ClientSuccessClientStoriesPage", "ExpertDetailPage", "SiteDetailPage9", "IndustriesDetailPage", "LpAtosThreatResearchPage", "LpDetailPage5", "LpCybershieldDetailPage", "WorldwideLocationsPage", "LpDetailPage6", "LpDigitalSovereigntyForPage", "IndustriesDetailPage2", "IndustriesPage", "NewsroomPage", "NewsroomBrandCenterPage", "LpDigitalSecurityMagazinePage2", "BlogPage", "LpDigitalSovereigntyAnPage", "ClientSuccessPage"), titles);
    }

    @Test
    @Tag("consent")
    @DisplayName("The cookie banner shows, is accepted, and stays away on the next page")
    void cookieBannerIsAcceptedAndStaysAway() {
        new SiteDetailPage(page).open("en");
        assertTrue(CookieBanner.acceptedIn(page), "Expected the cookie banner the crawl saw to show and take the click on its accept button, but it did not (the run's cookie banner lines say why)");
        new SiteDetailPage2(page).open("expert", "neil-milliken");
        assertFalse(CookieBanner.showingNow(page), "Expected the cookie banner to stay away once accepted, but it showed again on the next page: the site did not remember the choice");
    }
}
