// Generated by Suite Builder from a crawl of the site. The smoke tests: GeneratedSmokeTest's, and your changes to them.
// EDIT RULES: this whole file is yours. Suite Builder wrote it once and never overwrites it.
package net.atos.tests.cases;

/**
 * Every page type opens and looks like itself: the tests are GeneratedSmokeTest's, rebuilt from each
 * crawl, and run from here. To change one, override its method in this class, with its @Test and
 * @DisplayName (JUnit does not inherit them); yours runs instead. For example:
 *
 * <pre>
 * &#64;Override
 * &#64;Test
 * &#64;DisplayName("SiteDetailPage loads")
 * void siteDetailPageLoads() {
 *     new SiteDetailPage(page).open().verify().isLoaded();
 * }
 * </pre>
 */
class SmokeTest extends GeneratedSmokeTest {
}
