// Generated by Suite Builder from a crawl of the site. Checks for SiteDetailPage4.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage4.actions;

import net.atos.tests.pages.sitedetailpage4.SiteDetailPage4;
import net.atos.tests.pages.sitedetailpage4.SiteDetail4Elements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on SiteDetailPage4. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class SiteDetail4VerifyActions {
    private final Page page;

    public SiteDetail4VerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public SiteDetail4VerifyActions isLoaded() {
        SiteDetailPage4 here = new SiteDetailPage4(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name, name2, name3) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public SiteDetail4VerifyActions isThePageOf(String name, String name2, String name3) {
        Checks.isOnPath(page, UrlPaths.siteDetail4(name, name2, name3));
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(SiteDetail4Elements.SOME_HEADING)}. */
    public SiteDetail4VerifyActions shows(SiteDetail4Elements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public SiteDetail4VerifyActions doesNotShow(SiteDetail4Elements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public SiteDetail4VerifyActions says(SiteDetail4Elements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public SiteDetail4VerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public SiteDetail4VerifyActions holds(SiteDetail4Elements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public SiteDetail4VerifyActions isEmpty(SiteDetail4Elements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public SiteDetail4VerifyActions refusesEmpty(SiteDetail4Elements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public SiteDetail4VerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, SiteDetail4Elements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
