// Generated by Suite Builder from a crawl of the site. The "Download the white paper" form on LpOperationalizingAiOvercomingPage, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what LpOperationalizingAiOvercomingTasks.fillDownloadTheWhitePaperForm takes.
package net.atos.tests.pages.lpoperationalizingaiovercoming;

import net.atos.tests.core.SiteConfig;

/**
 * The "Download the white paper" form on LpOperationalizingAiOvercomingPage, as one value: its fields in page order, what
 * {@link LpOperationalizingAiOvercomingTasks#fillDownloadTheWhitePaperForm(DownloadTheWhitePaper)} types and chooses. {@code sample()} gives values a test can
 * send; change one with a copy: {@code DownloadTheWhitePaper.sample().withFirstName("...")}.
 */
public record DownloadTheWhitePaper(String firstName, String lastName, String businessEmailAddress, String companyName, String phoneNumber, String jobTitle) {

    /**
     * Values any copy of the site takes, each plausible for its field; one can be set for a run on the
     * command line (-DfirstName=...) or in suite.properties, by its name.
     */
    public static DownloadTheWhitePaper sample() {
        return new DownloadTheWhitePaper(
                SiteConfig.value("firstName", "Test *First Name:"),
                SiteConfig.value("lastName", "Test *Last Name:"),
                SiteConfig.value("businessEmailAddress", "test@example.com"),
                SiteConfig.value("companyName", "Test *Company Name:"),
                SiteConfig.value("phoneNumber", "555-0100"),
                SiteConfig.value("jobTitle", "Test *Job Title:"));
    }

    /** This DownloadTheWhitePaper with firstName in place of its own. */
    public DownloadTheWhitePaper withFirstName(String firstName) {
        return new DownloadTheWhitePaper(firstName, lastName, businessEmailAddress, companyName, phoneNumber, jobTitle);
    }

    /** This DownloadTheWhitePaper with lastName in place of its own. */
    public DownloadTheWhitePaper withLastName(String lastName) {
        return new DownloadTheWhitePaper(firstName, lastName, businessEmailAddress, companyName, phoneNumber, jobTitle);
    }

    /** This DownloadTheWhitePaper with businessEmailAddress in place of its own. */
    public DownloadTheWhitePaper withBusinessEmailAddress(String businessEmailAddress) {
        return new DownloadTheWhitePaper(firstName, lastName, businessEmailAddress, companyName, phoneNumber, jobTitle);
    }

    /** This DownloadTheWhitePaper with companyName in place of its own. */
    public DownloadTheWhitePaper withCompanyName(String companyName) {
        return new DownloadTheWhitePaper(firstName, lastName, businessEmailAddress, companyName, phoneNumber, jobTitle);
    }

    /** This DownloadTheWhitePaper with phoneNumber in place of its own. */
    public DownloadTheWhitePaper withPhoneNumber(String phoneNumber) {
        return new DownloadTheWhitePaper(firstName, lastName, businessEmailAddress, companyName, phoneNumber, jobTitle);
    }

    /** This DownloadTheWhitePaper with jobTitle in place of its own. */
    public DownloadTheWhitePaper withJobTitle(String jobTitle) {
        return new DownloadTheWhitePaper(firstName, lastName, businessEmailAddress, companyName, phoneNumber, jobTitle);
    }
}
