// Generated by Suite Builder from a crawl of the site. Page object for LpOperationalizingAiOvercomingPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpoperationalizingaiovercoming;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.EnterableAction;
import net.atos.tests.core.actions.ExecutableTask;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.pages.lpoperationalizingaiovercoming.actions.LpOperationalizingAiOvercomingClickActions;
import net.atos.tests.pages.lpoperationalizingaiovercoming.actions.LpOperationalizingAiOvercomingEnterActions;
import net.atos.tests.pages.lpoperationalizingaiovercoming.actions.LpOperationalizingAiOvercomingReadActions;
import net.atos.tests.pages.lpoperationalizingaiovercoming.actions.LpOperationalizingAiOvercomingVerifyActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /en/lp/operationalizing-ai-overcoming-the-challenges.
 * Stories call it:  "Read more - Operationalizing AI: Overcoming the Challenges" (the links that
 *                   lead here).
 * Get here:         new LpOperationalizingAiOvercomingPage(page).open()
 *                   from SiteDetailPage5: click().goToLpOperationalizingAiOvercoming()
 * The crawl saw:    1 page of this type (/en/lp/operationalizing-ai-overcoming-the-challenges); it
 *                   showed "Unlock the Full Value of AI for the Enterprise", "Download the white
 *                   paper", "Brian Ray", "Dive Deeper" and "AI Services …".
 * Proven loaded by: the main heading and the heading "Download the white paper" (isLoaded(),
 *                   PROVES_LOADED: what a copy edit leaves alone first).
 * Has a form:       on 1 of 1 page. Sending it on the live site sends real data: read
 *                   ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/en/lp/operationalizing-ai-overcoming-the-challenges.html (the
 *                   page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to
 *                   saved-pages/LpOperationalizingAiOvercomingPage/ (saved-pages/README.md) and add
 *                   what it shows to LpOperationalizingAiOvercomingElements.
 * </pre>
 */
public class LpOperationalizingAiOvercomingPage extends LoadablePage<LpOperationalizingAiOvercomingPage> implements
        ClickableAction<LpOperationalizingAiOvercomingClickActions>,
        EnterableAction<LpOperationalizingAiOvercomingEnterActions>,
        ReadableAction<LpOperationalizingAiOvercomingReadActions>,
        VerifiableAction<LpOperationalizingAiOvercomingVerifyActions>,
        ExecutableTask<LpOperationalizingAiOvercomingTasks>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "Operationalizing AI: Overcoming the Challenges - Atos";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 87180ca3
    static final List<LpOperationalizingAiOvercomingElements> PROVES_LOADED = List.of(
            LpOperationalizingAiOvercomingElements.MAIN_HEADING,
            LpOperationalizingAiOvercomingElements.DOWNLOAD_THE_WHITE_PAPER_HEADING);
    // ==== END YOURS (load-proof) ====

    public LpOperationalizingAiOvercomingPage(Page page) {
        super(page);
    }

    /** Goes to /en/lp/operationalizing-ai-overcoming-the-challenges and waits until it has fully loaded. */
    public LpOperationalizingAiOvercomingPage open() {
        navigate(UrlPaths.LP_OPERATIONALIZING_AI_OVERCOMING);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.LP_OPERATIONALIZING_AI_OVERCOMING);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.LP_OPERATIONALIZING_AI_OVERCOMING);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (LpOperationalizingAiOvercomingElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, LpOperationalizingAiOvercomingElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 0;
    }

    @Override
    public LpOperationalizingAiOvercomingClickActions click() {
        return new LpOperationalizingAiOvercomingClickActions(page);
    }

    @Override
    public LpOperationalizingAiOvercomingEnterActions enter() {
        return new LpOperationalizingAiOvercomingEnterActions(page);
    }

    @Override
    public LpOperationalizingAiOvercomingReadActions read() {
        return new LpOperationalizingAiOvercomingReadActions(page);
    }

    @Override
    public LpOperationalizingAiOvercomingVerifyActions verify() {
        return new LpOperationalizingAiOvercomingVerifyActions(page);
    }

    @Override
    public LpOperationalizingAiOvercomingTasks execute() {
        return new LpOperationalizingAiOvercomingTasks(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
