// Generated by Suite Builder from a crawl of the site. Locators for LpDigitalSecurityMagazinePage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdigitalsecuritymagazine;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.uri.UrlPaths;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /en/lp/digital-security-magazine-20th-edition.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum LpDigitalSecurityMagazineElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Digital Security Magazine 20th Edition": every crawled page of this type showed it. */
    DIGITAL_SECURITY_MAGAZINE_20TH_EDITION_HEADING(page -> Headings.named(page, "Digital Security Magazine 20th Edition")),
    /** Heading "The data security imperative: Protecting what matters most in the AI economy": every crawled page of this type showed it. */
    THE_DATA_SECURITY_IMPERATIVE_PROTECTING_WHAT_MATTERS_MOST_IN_THE_AI_ECONOMY_HEADING(page -> Headings.named(page, "The data security imperative: Protecting what matters most in the AI economy")),
    /** Heading "Building AI on solid foundations": every crawled page of this type showed it. */
    BUILDING_AI_ON_SOLID_FOUNDATIONS_HEADING(page -> Headings.named(page, "Building AI on solid foundations")),
    /** Heading "Zeina Zakhour": every crawled page of this type showed it. */
    ZEINA_ZAKHOUR_HEADING(page -> Headings.named(page, "Zeina Zakhour")),
    /** Heading "In this edition": every crawled page of this type showed it. */
    IN_THIS_EDITION_HEADING(page -> Headings.named(page, "In this edition")),
    /** Heading "Previous editions": every crawled page of this type showed it. */
    PREVIOUS_EDITIONS_HEADING(page -> Headings.named(page, "Previous editions")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: its page read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: its page read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Previous slide (only for visual purpose, links already av...": seen by the crawl on /en/lp/digital-security-magazine-20th-edition. */
    PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Previous slide (only for visual purpose, links already available just before)']")),
    /** button "Next slide (only for visual purpose, links already availa...": seen by the crawl on /en/lp/digital-security-magazine-20th-edition. */
    NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Next slide (only for visual purpose, links already available just before)']")),
    /** button "Play Click to play video": seen by the crawl on /en/lp/digital-security-magazine-20th-edition. */
    PLAY_CLICK_TO_PLAY_VIDEO_BUTTON(page -> page.locator("xpath=//div[@id='div-UuJZv-bNsP0-ykpl']")),
    /** button "Go to slide 1": seen by the crawl on /en/lp/digital-security-magazine-20th-edition. */
    GO_TO_SLIDE_1_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 1']")),
    /** button "Go to slide 2": seen by the crawl on /en/lp/digital-security-magazine-20th-edition. */
    GO_TO_SLIDE_2_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 2']")),

    // "For latest updates on Cybersecurity, Subscribe now." form (from the crawl: nothing was typed, clicked or sent).
    /** email field "*Business Email Address:", required: seen by the crawl on /en/lp/digital-security-magazine-20th-edition. */
    BUSINESS_EMAIL_ADDRESS_INPUT(page -> page.locator("xpath=//input[@id='Email']")),
    /** button "Subscribe": seen by the crawl on /en/lp/digital-security-magazine-20th-edition. */
    SUBSCRIBE_BUTTON(page -> page.locator("xpath=//div[@id='subscribe']//button[normalize-space()='Subscribe']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    LpDigitalSecurityMagazineElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    LpDigitalSecurityMagazineElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    /** A link to LpDetailPage4, e.g. https://atos.net/en/lp/digital-security-magazine-20th-edition/ai-data-governance. */
    public static PageElement getLpDetail4Link(String name, String name2) {
        String href = "/en/lp/" + name + "/" + name2;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("LP_DETAIL4_LINK", "the link to the lp detail page4 \"" + name + "/" + name2 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to ExpertDetailPage, e.g. https://atos.net/en/expert/zeina-zakhour. */
    public static PageElement getExpertDetailLink(String name) {
        String href = "/en/expert/" + name;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("EXPERT_DETAIL_LINK", "the link to the expert detail page \"" + name + "\"", page -> page.locator(xpath).first());
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
