// Generated by Suite Builder from a crawl of the site. Checks for IndustriesDetailPage2.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.industriesdetailpage2.actions;

import net.atos.tests.pages.industriesdetailpage2.IndustriesDetailPage2;
import net.atos.tests.pages.industriesdetailpage2.IndustriesDetail2Elements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on IndustriesDetailPage2. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class IndustriesDetail2VerifyActions {
    private final Page page;

    public IndustriesDetail2VerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public IndustriesDetail2VerifyActions isLoaded() {
        IndustriesDetailPage2 here = new IndustriesDetailPage2(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name, name2) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public IndustriesDetail2VerifyActions isThePageOf(String name, String name2) {
        Checks.isOnPath(page, UrlPaths.industriesDetail2(name, name2));
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(IndustriesDetail2Elements.SOME_HEADING)}. */
    public IndustriesDetail2VerifyActions shows(IndustriesDetail2Elements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public IndustriesDetail2VerifyActions doesNotShow(IndustriesDetail2Elements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public IndustriesDetail2VerifyActions says(IndustriesDetail2Elements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public IndustriesDetail2VerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public IndustriesDetail2VerifyActions holds(IndustriesDetail2Elements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public IndustriesDetail2VerifyActions isEmpty(IndustriesDetail2Elements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public IndustriesDetail2VerifyActions refusesEmpty(IndustriesDetail2Elements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public IndustriesDetail2VerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, IndustriesDetail2Elements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
