// Generated by Suite Builder from a crawl of the site. Page object for LpDigitalSecurityMagazinePage2.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdigitalsecuritymagazinepage2;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.EnterableAction;
import net.atos.tests.core.actions.ExecutableTask;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.pages.lpdigitalsecuritymagazinepage2.actions.LpDigitalSecurityMagazine2ClickActions;
import net.atos.tests.pages.lpdigitalsecuritymagazinepage2.actions.LpDigitalSecurityMagazine2EnterActions;
import net.atos.tests.pages.lpdigitalsecuritymagazinepage2.actions.LpDigitalSecurityMagazine2ReadActions;
import net.atos.tests.pages.lpdigitalsecuritymagazinepage2.actions.LpDigitalSecurityMagazine2VerifyActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /en/lp/digital-security-magazine-18.
 * Stories call it:  "Read more - Digital security magazine 18th Edition" (the links that lead
 *                   here).
 * Get here:         new LpDigitalSecurityMagazinePage2(page).open()
 *                   from LpDetailPage5: click().goToLpDigitalSecurityMagazine2()
 *                   from LpCybershieldDetailPage: click().goToLpDigitalSecurityMagazine2()
 * The crawl saw:    1 page of this type (/en/lp/digital-security-magazine-18); it showed "Digital
 *                   Security Magazine 18th Edition​", "Finding Signal in the Noise", "Zeina
 *                   Zakhour", "In this edition", "Identity at the Core: The New Cyber Perimeter"
 *                   and "Post-Quantum Security: What CISOs should know now".
 * Proven loaded by: the heading "Digital Security Magazine 18th Edition​" and the heading "Finding
 *                   Signal in the Noise" (isLoaded(), PROVES_LOADED: what a copy edit leaves alone
 *                   first).
 * Has a form:       on 1 of 1 page. Sending it on the live site sends real data: read
 *                   ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/en/lp/digital-security-magazine-18.html (the page's HTML when
 *                   crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/LpDigitalSecurityMagazinePage2/
 *                   (saved-pages/README.md) and add what it shows to
 *                   LpDigitalSecurityMagazine2Elements.
 * </pre>
 */
public class LpDigitalSecurityMagazinePage2 extends LoadablePage<LpDigitalSecurityMagazinePage2> implements
        ClickableAction<LpDigitalSecurityMagazine2ClickActions>,
        EnterableAction<LpDigitalSecurityMagazine2EnterActions>,
        ReadableAction<LpDigitalSecurityMagazine2ReadActions>,
        VerifiableAction<LpDigitalSecurityMagazine2VerifyActions>,
        ExecutableTask<LpDigitalSecurityMagazine2Tasks>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "Digital security magazine 18th Edition - Atos";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default a72bbbb5
    static final List<LpDigitalSecurityMagazine2Elements> PROVES_LOADED = List.of(
            LpDigitalSecurityMagazine2Elements.DIGITAL_SECURITY_MAGAZINE_18TH_EDITION_HEADING,
            LpDigitalSecurityMagazine2Elements.FINDING_SIGNAL_IN_THE_NOISE_HEADING);
    // ==== END YOURS (load-proof) ====

    public LpDigitalSecurityMagazinePage2(Page page) {
        super(page);
    }

    /** Goes to /en/lp/digital-security-magazine-18 and waits until it has fully loaded. */
    public LpDigitalSecurityMagazinePage2 open() {
        navigate(UrlPaths.LP_DIGITAL_SECURITY_MAGAZINE2);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.LP_DIGITAL_SECURITY_MAGAZINE2);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.LP_DIGITAL_SECURITY_MAGAZINE2);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (LpDigitalSecurityMagazine2Elements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, LpDigitalSecurityMagazine2Elements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 0;
    }

    @Override
    public LpDigitalSecurityMagazine2ClickActions click() {
        return new LpDigitalSecurityMagazine2ClickActions(page);
    }

    @Override
    public LpDigitalSecurityMagazine2EnterActions enter() {
        return new LpDigitalSecurityMagazine2EnterActions(page);
    }

    @Override
    public LpDigitalSecurityMagazine2ReadActions read() {
        return new LpDigitalSecurityMagazine2ReadActions(page);
    }

    @Override
    public LpDigitalSecurityMagazine2VerifyActions verify() {
        return new LpDigitalSecurityMagazine2VerifyActions(page);
    }

    @Override
    public LpDigitalSecurityMagazine2Tasks execute() {
        return new LpDigitalSecurityMagazine2Tasks(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
