// Generated by Suite Builder from a crawl of the site. Locators for LpDetailPage4.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage4;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.uri.UrlPaths;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 9 pages like /en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data, /en/lp/digital-security-magazine-20th-edition/how-synthetic-image-and-video-generation-is-opening-new-ground, /en/lp/digital-security-magazine-20th-edition/ai-data-governance.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum LpDetail4Elements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Share this article": every crawled page of this type showed it. */
    SHARE_THIS_ARTICLE_HEADING(page -> Headings.named(page, "Share this article")),
    /** Heading "Subscribe for regular insights": every crawled page of this type showed it. */
    SUBSCRIBE_FOR_REGULAR_INSIGHTS_HEADING(page -> Headings.named(page, "Subscribe for regular insights")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: each of its 4 pages read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: each of its 4 pages read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // Links to other pages (from the crawl).
    /** Link "Atos homepage" (href https://atos.net/en/lp/digital-security-magazine-20th-edition) to LpDigitalSecurityMagazinePage, seen by the crawl on /en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data. */
    LP_DIGITAL_SECURITY_MAGAZINE_LINK(page -> page.locator("xpath=//a[@href='/en/lp/digital-security-magazine-20th-edition' or (contains(@href, '//') and substring-after(substring-after(@href, '//'), '/')='en/lp/digital-security-magazine-20th-edition')] >> visible=true").first(), "\"Atos homepage\""),

    // "Subscribe for regular insights" form (from the crawl: nothing was typed, clicked or sent).
    /** email field "*Business Email Address:", required: seen by the crawl on /en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data. */
    BUSINESS_EMAIL_ADDRESS_INPUT(page -> page.locator("xpath=//input[@id='Email']")),
    /** button "Subscribe": seen by the crawl on /en/lp/digital-security-magazine-20th-edition/responsible-ai-starts-with-responsible-data. */
    SUBSCRIBE_BUTTON(page -> page.locator("xpath=//button[normalize-space()='Subscribe']")),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Go to slide 1": seen by the crawl on /en/lp/digital-security-magazine-17/three-steps-to-managing-secure-third-party-access-in-your-supply-chain. */
    GO_TO_SLIDE_1_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 1']")),
    /** button "Go to slide 2": seen by the crawl on /en/lp/digital-security-magazine-17/three-steps-to-managing-secure-third-party-access-in-your-supply-chain. */
    GO_TO_SLIDE_2_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 2']")),
    /** button "Go to slide 3": seen by the crawl on /en/lp/digital-security-magazine-17/three-steps-to-managing-secure-third-party-access-in-your-supply-chain. */
    GO_TO_SLIDE_3_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 3']")),
    /** button "Go to slide 4": seen by the crawl on /en/lp/digital-security-magazine-17/three-steps-to-managing-secure-third-party-access-in-your-supply-chain. */
    GO_TO_SLIDE_4_BUTTON(page -> page.locator("xpath=//span[@aria-label='Go to slide 4']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    LpDetail4Elements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    LpDetail4Elements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    /** A link to SiteDetailPage2, e.g. https://atos.net/en/expert/yann-dietrich. */
    public static PageElement getSiteDetail2Link(String name, String name2) {
        String href = "/en/" + name + "/" + name2;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("SITE_DETAIL2_LINK", "the link to the site detail page2 \"" + name + "/" + name2 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to LpDetailPage4, e.g. https://atos.net/en/lp/digital-security-magazine-20th-edition/ai-data-governance. */
    public static PageElement getLpDetail4Link(String name, String name2) {
        String href = "/en/lp/" + name + "/" + name2;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("LP_DETAIL4_LINK", "the link to the lp detail page4 \"" + name + "/" + name2 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to ExpertDetailPage, e.g. https://atos.net/en/expert/chris-mcclean. */
    public static PageElement getExpertDetailLink(String name) {
        String href = "/en/expert/" + name;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("EXPERT_DETAIL_LINK", "the link to the expert detail page \"" + name + "\"", page -> page.locator(xpath).first());
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
