// Generated by Suite Builder from a crawl of the site. The "Subscribe for regular insights" form on LpDetailPage4, as one value.
// EDIT RULES: do not edit this file; regenerating replaces all of it. A form's own record: what LpDetail4Tasks.fillSubscribeForRegularInsightsForm takes.
package net.atos.tests.pages.lpdetailpage4;

import net.atos.tests.core.SiteConfig;

/**
 * The "Subscribe for regular insights" form on LpDetailPage4, as one value: its fields in page order, what
 * {@link LpDetail4Tasks#fillSubscribeForRegularInsightsForm(SubscribeForRegularInsights)} types and chooses. {@code sample()} gives values a test can
 * send; change one with a copy: {@code SubscribeForRegularInsights.sample().withBusinessEmailAddress("...")}.
 */
public record SubscribeForRegularInsights(String businessEmailAddress) {

    /**
     * Values any copy of the site takes, each plausible for its field; one can be set for a run on the
     * command line (-DbusinessEmailAddress=...) or in suite.properties, by its name.
     */
    public static SubscribeForRegularInsights sample() {
        return new SubscribeForRegularInsights(
                SiteConfig.value("businessEmailAddress", "test@example.com"));
    }

    /** This SubscribeForRegularInsights with businessEmailAddress in place of its own. */
    public SubscribeForRegularInsights withBusinessEmailAddress(String businessEmailAddress) {
        return new SubscribeForRegularInsights(businessEmailAddress);
    }
}
