// Generated by Suite Builder from a crawl of the site. Checks for LpDigitalSecurityMagazinePage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdigitalsecuritymagazine.actions;

import net.atos.tests.pages.lpdigitalsecuritymagazine.LpDigitalSecurityMagazinePage;
import net.atos.tests.pages.lpdigitalsecuritymagazine.LpDigitalSecurityMagazineElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on LpDigitalSecurityMagazinePage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class LpDigitalSecurityMagazineVerifyActions {
    private final Page page;

    public LpDigitalSecurityMagazineVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public LpDigitalSecurityMagazineVerifyActions isLoaded() {
        LpDigitalSecurityMagazinePage here = new LpDigitalSecurityMagazinePage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public LpDigitalSecurityMagazineVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Digital Security Magazine 20th Edition\", \"The data security imperative: Protecting what matters most in the AI economy\", \"Building AI on solid foundations\", \"Zeina Zakhour\", \"In this edition\", \"Previous editions\")",
                LpDigitalSecurityMagazineElements.DIGITAL_SECURITY_MAGAZINE_20TH_EDITION_HEADING, LpDigitalSecurityMagazineElements.THE_DATA_SECURITY_IMPERATIVE_PROTECTING_WHAT_MATTERS_MOST_IN_THE_AI_ECONOMY_HEADING, LpDigitalSecurityMagazineElements.BUILDING_AI_ON_SOLID_FOUNDATIONS_HEADING, LpDigitalSecurityMagazineElements.ZEINA_ZAKHOUR_HEADING, LpDigitalSecurityMagazineElements.IN_THIS_EDITION_HEADING, LpDigitalSecurityMagazineElements.PREVIOUS_EDITIONS_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(LpDigitalSecurityMagazineElements.SOME_HEADING)}. */
    public LpDigitalSecurityMagazineVerifyActions shows(LpDigitalSecurityMagazineElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public LpDigitalSecurityMagazineVerifyActions doesNotShow(LpDigitalSecurityMagazineElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public LpDigitalSecurityMagazineVerifyActions says(LpDigitalSecurityMagazineElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public LpDigitalSecurityMagazineVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public LpDigitalSecurityMagazineVerifyActions holds(LpDigitalSecurityMagazineElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public LpDigitalSecurityMagazineVerifyActions isEmpty(LpDigitalSecurityMagazineElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public LpDigitalSecurityMagazineVerifyActions refusesEmpty(LpDigitalSecurityMagazineElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public LpDigitalSecurityMagazineVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, LpDigitalSecurityMagazineElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
