// Generated by Suite Builder from a crawl of the site. Locators for BlogPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.blog;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for the page at /en/blog.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum BlogElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "The Atos Blog": every crawled page of this type showed it. */
    THE_ATOS_BLOG_HEADING(page -> Headings.named(page, "The Atos Blog")),
    /** Heading "Insights that matter": every crawled page of this type showed it. */
    INSIGHTS_THAT_MATTER_HEADING(page -> Headings.named(page, "Insights that matter")),
    /** Heading "Building Sovereign Agentic AI …": every crawled page of this type showed it. */
    BUILDING_SOVEREIGN_AGENTIC_AI_HEADING(page -> Headings.named(page, "Building Sovereign Agentic AI …")),
    /** Heading "The DEXOps advantage: Better employee experiences, fewer …": every crawled page of this type showed it. */
    THE_DEXOPS_ADVANTAGE_BETTER_EMPLOYEE_EXPERIENCES_FEWER_HEADING(page -> Headings.named(page, "The DEXOps advantage: Better employee experiences, fewer …")),
    /** Heading "Build the team behind the tools with DEXOps …": every crawled page of this type showed it. */
    BUILD_THE_TEAM_BEHIND_THE_TOOLS_WITH_DEXOPS_HEADING(page -> Headings.named(page, "Build the team behind the tools with DEXOps …")),
    /** Heading "Rethinking Sovereignty for Agentic AI …": every crawled page of this type showed it. */
    RETHINKING_SOVEREIGNTY_FOR_AGENTIC_AI_HEADING(page -> Headings.named(page, "Rethinking Sovereignty for Agentic AI …")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: its page read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: its page read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // "search" form (from the crawl: nothing was typed, clicked or sent).
    /** text field "Search our blogs": seen by the crawl on /en/blog. */
    SEARCH_OUR_BLOGS_INPUT(page -> page.locator("xpath=//input[@id='finder-search']")),
    /** button "BUTTON": seen by the crawl on /en/blog. */
    BUTTON(page -> page.locator("xpath=//div[@id='finder']//div[div[normalize-space()='Search filters']]/div[2]/form/button")),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Clear selection": seen by the crawl on /en/blog. */
    CLEAR_SELECTION_BUTTON(page -> page.locator("xpath=//div[normalize-space()='Clear selection']")),
    /** button "Select category": seen by the crawl on /en/blog. */
    SELECT_CATEGORY_BUTTON(page -> page.locator("xpath=//button[normalize-space()='Select category']")),

    // "Select category" form (from the crawl: nothing was typed, clicked or sent).
    /** checkbox "All Blog Topics": seen by the crawl on /en/blog. */
    ALL_BLOG_TOPICS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='All Blog Topics']/@for]")),
    /** checkbox "AI": seen by the crawl on /en/blog. */
    AI_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='AI']/@for]")),
    /** checkbox "Accessibility": seen by the crawl on /en/blog. */
    ACCESSIBILITY_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Accessibility']/@for]")),
    /** checkbox "Careers": seen by the crawl on /en/blog. */
    CAREERS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Careers']/@for]")),
    /** checkbox "Cloud & Modern Infrastructure": seen by the crawl on /en/blog. */
    CLOUD_MODERN_INFRASTRUCTURE_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Cloud & Modern Infrastructure']/@for]")),
    /** checkbox "Connected Solutions": seen by the crawl on /en/blog. */
    CONNECTED_SOLUTIONS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Connected Solutions']/@for]")),
    /** checkbox "Consulting & advisory": seen by the crawl on /en/blog. */
    CONSULTING_ADVISORY_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Consulting & advisory']/@for]")),
    /** checkbox "Customized Services": seen by the crawl on /en/blog. */
    CUSTOMIZED_SERVICES_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Customized Services']/@for]")),
    /** checkbox "Cybersecurity": seen by the crawl on /en/blog. */
    CYBERSECURITY_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Cybersecurity']/@for]")),
    /** checkbox "DEI": seen by the crawl on /en/blog. */
    DEI_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='DEI']/@for]")),
    /** checkbox "Data & Artificial Intelligence": seen by the crawl on /en/blog. */
    DATA_ARTIFICIAL_INTELLIGENCE_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Data & Artificial Intelligence']/@for]")),
    /** checkbox "Data Analytics": seen by the crawl on /en/blog. */
    DATA_ANALYTICS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Data Analytics']/@for]")),
    /** checkbox "Digital Applications": seen by the crawl on /en/blog. */
    DIGITAL_APPLICATIONS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Digital Applications']/@for]")),
    /** checkbox "Digital Transformation": seen by the crawl on /en/blog. */
    DIGITAL_TRANSFORMATION_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Digital Transformation']/@for]")),
    /** checkbox "Digital Workplace": seen by the crawl on /en/blog. */
    DIGITAL_WORKPLACE_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Digital Workplace']/@for]")),
    /** checkbox "Future Makers Research Community": seen by the crawl on /en/blog. */
    FUTURE_MAKERS_RESEARCH_COMMUNITY_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Future Makers Research Community']/@for]")),
    /** checkbox "Hybrid Cloud Security": seen by the crawl on /en/blog. */
    HYBRID_CLOUD_SECURITY_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Hybrid Cloud Security']/@for]")),
    /** checkbox "Industry Transformation": seen by the crawl on /en/blog. */
    INDUSTRY_TRANSFORMATION_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Industry Transformation']/@for]")),
    /** checkbox "Intelligent Networks": seen by the crawl on /en/blog. */
    INTELLIGENT_NETWORKS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Intelligent Networks']/@for]")),
    /** checkbox "Mission Critical Communications": seen by the crawl on /en/blog. */
    MISSION_CRITICAL_COMMUNICATIONS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Mission Critical Communications']/@for]")),
    /** checkbox "Smart Platforms": seen by the crawl on /en/blog. */
    SMART_PLATFORMS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Smart Platforms']/@for]")),
    /** checkbox "Sovereignty": seen by the crawl on /en/blog. */
    SOVEREIGNTY_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Sovereignty']/@for]")),
    /** checkbox "Sports & Major Events": seen by the crawl on /en/blog. */
    SPORTS_MAJOR_EVENTS_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Sports & Major Events']/@for]")),
    /** checkbox "Sustainability": seen by the crawl on /en/blog. */
    SUSTAINABILITY_CHECKBOX(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Sustainability']/@for]")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    BlogElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    BlogElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
