// Generated by Suite Builder from a crawl of the site. Checks for BlogPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.blog.actions;

import net.atos.tests.pages.blog.BlogPage;
import net.atos.tests.pages.blog.BlogElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on BlogPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class BlogVerifyActions {
    private final Page page;

    public BlogVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public BlogVerifyActions isLoaded() {
        BlogPage here = new BlogPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public BlogVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"The Atos Blog\", \"Insights that matter\", \"Building Sovereign Agentic AI …\", \"The DEXOps advantage: Better employee experiences, fewer …\", \"Build the team behind the tools with DEXOps …\", \"Rethinking Sovereignty for Agentic AI …\")",
                BlogElements.THE_ATOS_BLOG_HEADING, BlogElements.INSIGHTS_THAT_MATTER_HEADING, BlogElements.BUILDING_SOVEREIGN_AGENTIC_AI_HEADING, BlogElements.THE_DEXOPS_ADVANTAGE_BETTER_EMPLOYEE_EXPERIENCES_FEWER_HEADING, BlogElements.BUILD_THE_TEAM_BEHIND_THE_TOOLS_WITH_DEXOPS_HEADING, BlogElements.RETHINKING_SOVEREIGNTY_FOR_AGENTIC_AI_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(BlogElements.SOME_HEADING)}. */
    public BlogVerifyActions shows(BlogElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public BlogVerifyActions doesNotShow(BlogElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public BlogVerifyActions says(BlogElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public BlogVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public BlogVerifyActions holds(BlogElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public BlogVerifyActions isEmpty(BlogElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public BlogVerifyActions refusesEmpty(BlogElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public BlogVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, BlogElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
