// Generated by Suite Builder from a crawl of the site. Tasks for SiteDetailPage2.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage2;

import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Multi-step tasks on SiteDetailPage2, built from its actions (fill in a form and submit it, say).
 * The crawl's own are below; add more in the YOURS block.
 */
public class SiteDetail2Tasks {
    private final Page page;

    public SiteDetail2Tasks(Page page) {
        this.page = page;
    }

    /**
     * Fills the "a form" form, field by field in page order, and stops before sending it: a generated
     * test never sends a form (ai/recipes/forms-and-test-data.md). To send it, a story adds {@code .click().submit()}: what the site does then is not something the crawl saw. Its values: {@code SiteDetail2Form.sample()},
     * or a copy with one changed, {@code SiteDetail2Form.sample().withPreferredLanguage("...")}.
     */
    public SiteDetailPage2 fillForm(SiteDetail2Form form) {
        SiteDetailPage2 here = new SiteDetailPage2(page);
        here.enter().preferredLanguage(form.preferredLanguage()).inquiryType(form.inquiryType()).inquiry(form.inquiry()).firstName(form.firstName()).lastName(form.lastName()).companyOrganizationName(form.companyOrganizationName()).businessEmailAddress(form.businessEmailAddress()).country(form.country()).jobTitle(form.jobTitle());
        return here;
    }

    /**
     * @deprecated Takes the form's record now (G-152): {@code fillForm(SiteDetail2Form.sample())}. This one goes
     * in a later release.
     */
    @Deprecated
    public SiteDetailPage2 fillForm(String preferredLanguage, String inquiryType, String inquiry, String firstName, String lastName, String companyOrganizationName, String businessEmailAddress, String country, String jobTitle) {
        return fillForm(new SiteDetail2Form(preferredLanguage, inquiryType, inquiry, firstName, lastName, companyOrganizationName, businessEmailAddress, country, jobTitle));
    }

    // ==== YOURS (tasks): safe to edit; regenerating keeps what is between these lines ====
    // One method per task a story names, built from this page's actions (ai/recipes/add-a-task.md), e.g.:
    // public ThankYouPage signUp(String email) {
    //     SiteDetailPage2 here = new SiteDetailPage2(page);
    //     here.enter().email(email);
    //     here.check().terms();
    //     return here.click().submit();
    // }
    // ==== END YOURS (tasks) ====
}
