// Generated by Suite Builder from a crawl of the site. Locators for SiteDetailPage2.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage2;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.uri.UrlPaths;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 60 pages like /en/terms-and-conditions, /en/privacy, /en/contact-us.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum SiteDetail2Elements implements PageElement {
    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: each of its 30 pages read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: each of its 30 pages read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // Links to other pages (from the crawl).
    /** Link "View Cookies and other tracking technologies" (href https://atos.net/en/privacy/cookies-and-other-tracking-technologies) to PrivacyCookiesAndOtherPage, seen by the crawl on /en/privacy. */
    PRIVACY_COOKIES_AND_OTHER_LINK(page -> page.locator("xpath=//a[@href='/en/privacy/cookies-and-other-tracking-technologies' or (contains(@href, '//') and substring-after(substring-after(@href, '//'), '/')='en/privacy/cookies-and-other-tracking-technologies')] >> visible=true").first(), "\"View Cookies and other tracking technologies\""),
    /** Link "here" (href https://atos.net/en/privacy/exercise-rights-regarding-personal-data) to ExerciseRightsRegardingPersonalPage, seen by the crawl on /en/privacy/global-privacy-notice. */
    EXERCISE_RIGHTS_REGARDING_PERSONAL_LINK(page -> page.locator("xpath=//a[@href='/en/privacy/exercise-rights-regarding-personal-data' or (contains(@href, '//') and substring-after(substring-after(@href, '//'), '/')='en/privacy/exercise-rights-regarding-personal-data')] >> visible=true").first(), "\"here\""),

    // A form (from the crawl: nothing was typed, clicked or sent).
    /** dropdown "Preferred Language": seen by the crawl on /en/contact-us. */
    PREFERRED_LANGUAGE_SELECT(page -> page.locator("xpath=//select[@id='preferredLanguage']")),
    /** dropdown "Inquiry Type", required: seen by the crawl on /en/contact-us. */
    INQUIRY_TYPE_SELECT(page -> page.locator("xpath=//select[@id='enquiryType']")),
    /** text area "Inquiry": seen by the crawl on /en/contact-us. */
    INQUIRY_INPUT(page -> page.locator("xpath=//textarea[@id='enquiry']")),
    /** text field "First Name", required: seen by the crawl on /en/contact-us. */
    FIRST_NAME_INPUT(page -> page.locator("xpath=//input[@id='FirstName']")),
    /** text field "Last Name", required: seen by the crawl on /en/contact-us. */
    LAST_NAME_INPUT(page -> page.locator("xpath=//input[@id='LastName']")),
    /** text field "Company/Organization Name", required: seen by the crawl on /en/contact-us. */
    COMPANY_ORGANIZATION_NAME_INPUT(page -> page.locator("xpath=//input[@id='Company']")),
    /** email field "Business Email Address", required: seen by the crawl on /en/contact-us. */
    BUSINESS_EMAIL_ADDRESS_INPUT(page -> page.locator("xpath=//input[@id='Email']")),
    /** dropdown "Country", required: seen by the crawl on /en/contact-us. */
    COUNTRY_SELECT(page -> page.locator("xpath=//select[@id='Country']")),
    /** button "Submit": seen by the crawl on /en/contact-us. */
    SUBMIT_BUTTON(page -> page.locator("xpath=//button[normalize-space()='Submit']")),
    /** text field "*Job Title:": seen by the crawl on /en/services/digital-applications/business-solutions/contact. */
    JOB_TITLE_INPUT(page -> page.locator("xpath=//input[@id='Title']")),
    /** radio "Automotive Supplier for Microsoft Applications", required: seen by the crawl on /en/services/digital-applications/business-solutions/contact. */
    AUTOMOTIVE_SUPPLIER_FOR_MICROSOFT_APPLICATIONS_RADIO(page -> page.locator("xpath=//main[@id='content']//div[label[normalize-space()='Data2PDF']]/input[1]")),
    /** radio "Data2PDF", required: seen by the crawl on /en/services/digital-applications/business-solutions/contact. */
    DATA2PDF_RADIO(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Data2PDF']/@for]")),
    /** radio "Product Carbon Footprint (PCF)", required: seen by the crawl on /en/services/digital-applications/business-solutions/contact. */
    PRODUCT_CARBON_FOOTPRINT_PCF_RADIO(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Product Carbon Footprint (PCF)']/@for]")),
    /** radio "Digital Product Passport (DPP)", required: seen by the crawl on /en/services/digital-applications/business-solutions/contact. */
    DIGITAL_PRODUCT_PASSPORT_DPP_RADIO(page -> page.locator("xpath=//input[@id=//label[normalize-space()='Digital Product Passport (DPP)']/@for]")),
    /** radio "Integrated Computer Aided Manufacturing (ICAM)", required: seen by the crawl on /en/services/digital-applications/business-solutions/contact. */
    INTEGRATED_COMPUTER_AIDED_MANUFACTURING_ICAM_RADIO(page -> page.locator("xpath=//main[@id='content']//div[label[normalize-space()='Data2PDF']]/input[5]")),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "close": seen by the crawl on /en/expert/neil-milliken. */
    CLOSE_BUTTON(page -> page.locator("xpath=//button[@aria-label='close']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    SiteDetail2Elements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    SiteDetail2Elements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    /** A link to SiteDetailPage2, e.g. /en/contact-us. */
    public static PageElement getSiteDetail2Link(String name) {
        String href = "/en/" + name;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + "] >> visible=true";
        return PageElement.of("SITE_DETAIL2_LINK", "the link to the site detail page2 \"" + name + "\"", page -> page.locator(xpath).first());
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
