// Generated by Suite Builder from a crawl of the site. Click actions for SiteDetailPage3.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage3.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.blogdetail.BlogDetailPage;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.ClientSuccessClientStoriesDetailPage;
import net.atos.tests.pages.lpcybershielddetail.LpCybershieldDetailPage;
import net.atos.tests.pages.lpdetail.LpDetailPage;
import net.atos.tests.pages.lpdetailpage2.LpDetailPage2;
import net.atos.tests.pages.lpdigitalsovereigntyfor.LpDigitalSovereigntyForPage;
import net.atos.tests.pages.sitedetailpage3.SiteDetail3Elements;
import net.atos.tests.pages.sitedetailpage3.SiteDetailPage3;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on SiteDetailPage3. Clicks that change page return the next page; others return this. */
public class SiteDetail3ClickActions {
    private final Page page;

    public SiteDetail3ClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to BlogDetailPage (e.g. Read more - Preparing your workforce for the age of agentic AI) and waits for it. */
    public BlogDetailPage goToBlogDetail(String name) {
        UserActions.click(page, SiteDetail3Elements.getBlogDetailLink(name));
        return new BlogDetailPage(page).get();
    }

    /** Clicks a link to ClientSuccessClientStoriesDetailPage (e.g. Read more >) and waits for it. It opens in a new tab. */
    public ClientSuccessClientStoriesDetailPage goToClientSuccessClientStoriesDetail(String name) {
        Page tab = UserActions.clickOpeningNewTab(page, SiteDetail3Elements.getClientSuccessClientStoriesDetailLink(name));
        return new ClientSuccessClientStoriesDetailPage(tab).get();
    }

    /** Clicks a link to LpDetailPage (e.g. Read more - Agentic AI Hackathon) and waits for it. It opens in a new tab. */
    public LpDetailPage goToLpDetail(String name) {
        Page tab = UserActions.clickOpeningNewTab(page, SiteDetail3Elements.getLpDetailLink(name));
        return new LpDetailPage(tab).get();
    }

    /** Clicks a link to LpDetailPage2 (e.g. Read more - World Creativity​ & Innovation Week​) and waits for it. It opens in a new tab. */
    public LpDetailPage2 goToLpDetail2(String name) {
        Page tab = UserActions.clickOpeningNewTab(page, SiteDetail3Elements.getLpDetail2Link(name));
        return new LpDetailPage2(tab).get();
    }

    /** Clicks a link to LpCybershieldDetailPage (e.g. Learn more >) and waits for it. */
    public LpCybershieldDetailPage goToLpCybershieldDetail(String name) {
        UserActions.click(page, SiteDetail3Elements.getLpCybershieldDetailLink(name));
        return new LpCybershieldDetailPage(page).get();
    }

    /** Clicks the link to LpDigitalSovereigntyForPage (Learn more >) and waits for it. It opens in a new tab. */
    public LpDigitalSovereigntyForPage goToLpDigitalSovereigntyFor() {
        Page tab = UserActions.clickOpeningNewTab(page, SiteDetail3Elements.LP_DIGITAL_SOVEREIGNTY_FOR_LINK);
        return new LpDigitalSovereigntyForPage(tab).get();
    }

    /** Clicks the button "Previous slide (only for visual purpose, links already av...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 previousSlideOnlyForVisual() {
        UserActions.click(page, SiteDetail3Elements.PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Next slide (only for visual purpose, links already availa...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 nextSlideOnlyForVisual() {
        UserActions.click(page, SiteDetail3Elements.NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Play Future Makers Research Community". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 playFutureMakersResearchCommunity() {
        UserActions.click(page, SiteDetail3Elements.PLAY_FUTURE_MAKERS_RESEARCH_COMMUNITY_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "previous slide". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 previousSlide() {
        UserActions.click(page, SiteDetail3Elements.PREVIOUS_SLIDE_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "ARC SVG -Marcom". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 arcSvgMarcom() {
        UserActions.click(page, SiteDetail3Elements.ARC_SVG_MARCOM_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Infustry Research". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 infustryResearch() {
        UserActions.click(page, SiteDetail3Elements.INFUSTRY_RESEARCH_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "next slide". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 nextSlide() {
        UserActions.click(page, SiteDetail3Elements.NEXT_SLIDE_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "previous slide". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 previousSlide2() {
        UserActions.click(page, SiteDetail3Elements.PREVIOUS_SLIDE_BUTTON_2);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "next slide". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 nextSlide2() {
        UserActions.click(page, SiteDetail3Elements.NEXT_SLIDE_BUTTON_2);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Decentralized Embedded Finance (DeEmFi)". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 decentralizedEmbeddedFinanceDeEm() {
        UserActions.click(page, SiteDetail3Elements.DECENTRALIZED_EMBEDDED_FINANCE_DE_EM_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Reimagining Engineering with Sovereign GenAI". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 reimaginingEngineeringWithSovereignGen() {
        UserActions.click(page, SiteDetail3Elements.REIMAGINING_ENGINEERING_WITH_SOVEREIGN_GEN_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Generative AI whitepaper". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 generativeAiWhitepaper() {
        UserActions.click(page, SiteDetail3Elements.GENERATIVE_AI_WHITEPAPER_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 1". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide1() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_1_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 2". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide2() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_2_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 3". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide3() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_3_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 4". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide4() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_4_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 5". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide5() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_5_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 6". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide6() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_6_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 7". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide7() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_7_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 8". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide8() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_8_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 9". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide9() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_9_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 10". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide10() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_10_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 11". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide11() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_11_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 12". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide12() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_12_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 13". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide13() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_13_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 14". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide14() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_14_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 15". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide15() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_15_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Go to slide 16". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 goToSlide16() {
        UserActions.click(page, SiteDetail3Elements.GO_TO_SLIDE_16_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Submit". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 submit() {
        UserActions.click(page, SiteDetail3Elements.SUBMIT_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "previous arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 previousArrow() {
        UserActions.click(page, SiteDetail3Elements.PREVIOUS_ARROW_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "next arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 nextArrow() {
        UserActions.click(page, SiteDetail3Elements.NEXT_ARROW_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Home". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 home() {
        UserActions.click(page, SiteDetail3Elements.HOME_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Digital Sovereignty for Switzerland". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 digitalSovereigntyForSwitzerland() {
        UserActions.click(page, SiteDetail3Elements.DIGITAL_SOVEREIGNTY_FOR_SWITZERLAND_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Play Atos - Your Global AI-powered Digital Partner". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 playAtosYourGlobalAi() {
        UserActions.click(page, SiteDetail3Elements.PLAY_ATOS_YOUR_GLOBAL_AI_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "previous arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 previousArrow2() {
        UserActions.click(page, SiteDetail3Elements.PREVIOUS_ARROW_BUTTON_2);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "next arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 nextArrow2() {
        UserActions.click(page, SiteDetail3Elements.NEXT_ARROW_BUTTON_2);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Six". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 six() {
        UserActions.click(page, SiteDetail3Elements.SIX_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "Swiss Post". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 swissPost() {
        UserActions.click(page, SiteDetail3Elements.SWISS_POST_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Clicks the button "UEFA". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage3 uefa() {
        UserActions.click(page, SiteDetail3Elements.UEFA_BUTTON);
        return new SiteDetailPage3(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public SiteDetail3VerifyActions verify() {
        return new SiteDetail3VerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public SiteDetail3ClickActions acceptTerms() {
    //     UserActions.click(page, SiteDetail3Elements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
