// Generated by Suite Builder from a crawl of the site. Page object for WorldwideLocationsPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.worldwidelocations;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.pages.worldwidelocations.actions.WorldwideLocationsClickActions;
import net.atos.tests.pages.worldwidelocations.actions.WorldwideLocationsReadActions;
import net.atos.tests.pages.worldwidelocations.actions.WorldwideLocationsVerifyActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /en/worldwide-locations.
 * Stories call it:  "View all locations", "Worldwide Locations" (the links that lead here).
 * Get here:         new WorldwideLocationsPage(page).open()
 *                   from any page: navigateTo().worldwideLocations() (in the "Global" menu)
 *                   from any page: navigateTo().worldwideLocations2() (in the "About us" menu)
 * The crawl saw:    1 page of this type (/en/worldwide-locations); it showed "Atos Worldwide
 *                   Locations", "Canada", "Mexico", "USA - North America Headquarters", "Algeria"
 *                   and "Egypt".
 * Proven loaded by: the main heading and the heading "Atos Worldwide Locations" (isLoaded(),
 *                   PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/en/worldwide-locations.html (the page's HTML when crawled: check a
 *                   locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/WorldwideLocationsPage/
 *                   (saved-pages/README.md) and add what it shows to WorldwideLocationsElements.
 * </pre>
 */
public class WorldwideLocationsPage extends LoadablePage<WorldwideLocationsPage> implements
        ClickableAction<WorldwideLocationsClickActions>,
        ReadableAction<WorldwideLocationsReadActions>,
        VerifiableAction<WorldwideLocationsVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "Worldwide Locations - Atos";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 85d074ab
    static final List<WorldwideLocationsElements> PROVES_LOADED = List.of(
            WorldwideLocationsElements.MAIN_HEADING,
            WorldwideLocationsElements.ATOS_WORLDWIDE_LOCATIONS_HEADING);
    // ==== END YOURS (load-proof) ====

    public WorldwideLocationsPage(Page page) {
        super(page);
    }

    /** Goes to /en/worldwide-locations and waits until it has fully loaded. */
    public WorldwideLocationsPage open() {
        navigate(UrlPaths.WORLDWIDE_LOCATIONS);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.WORLDWIDE_LOCATIONS);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.WORLDWIDE_LOCATIONS);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (WorldwideLocationsElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, WorldwideLocationsElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 200;
    }

    @Override
    public WorldwideLocationsClickActions click() {
        return new WorldwideLocationsClickActions(page);
    }

    @Override
    public WorldwideLocationsReadActions read() {
        return new WorldwideLocationsReadActions(page);
    }

    @Override
    public WorldwideLocationsVerifyActions verify() {
        return new WorldwideLocationsVerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
