// Generated by Suite Builder from a crawl of the site. Checks for LpDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetail.actions;

import net.atos.tests.pages.lpdetail.LpDetailPage;
import net.atos.tests.pages.lpdetail.LpDetailElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on LpDetailPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class LpDetailVerifyActions {
    private final Page page;

    public LpDetailVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public LpDetailVerifyActions isLoaded() {
        LpDetailPage here = new LpDetailPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public LpDetailVerifyActions isThePageOf(String name) {
        Checks.isOnPath(page, UrlPaths.lpDetail(name));
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(LpDetailElements.SOME_HEADING)}. */
    public LpDetailVerifyActions shows(LpDetailElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public LpDetailVerifyActions doesNotShow(LpDetailElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public LpDetailVerifyActions says(LpDetailElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public LpDetailVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public LpDetailVerifyActions holds(LpDetailElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public LpDetailVerifyActions isEmpty(LpDetailElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public LpDetailVerifyActions refusesEmpty(LpDetailElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public LpDetailVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, LpDetailElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
