// Generated by Suite Builder from a crawl of the site. Click actions for LpDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetail.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.lpdetail.LpDetailElements;
import net.atos.tests.pages.lpdetail.LpDetailPage;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on LpDetailPage. Clicks that change page return the next page; others return this. */
public class LpDetailClickActions {
    private final Page page;

    public LpDetailClickActions(Page page) {
        this.page = page;
    }

    /** Clicks the button "Submit". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDetailPage submit() {
        UserActions.click(page, LpDetailElements.SUBMIT_BUTTON);
        return new LpDetailPage(page);
    }

    /** Clicks the button "Previous slide (only for visual purpose, links already av...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDetailPage previousSlideOnlyForVisual() {
        UserActions.click(page, LpDetailElements.PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new LpDetailPage(page);
    }

    /** Clicks the button "Next slide (only for visual purpose, links already availa...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDetailPage nextSlideOnlyForVisual() {
        UserActions.click(page, LpDetailElements.NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new LpDetailPage(page);
    }

    /** Clicks the button "Play Click to play video". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDetailPage playClickToPlayVideo() {
        UserActions.click(page, LpDetailElements.PLAY_CLICK_TO_PLAY_VIDEO_BUTTON);
        return new LpDetailPage(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public LpDetailVerifyActions verify() {
        return new LpDetailVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public LpDetailClickActions acceptTerms() {
    //     UserActions.click(page, LpDetailElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
