// Generated by Suite Builder from a crawl of the site. Click actions for LpDetailPage5.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage5.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.lpcybershielddetail.LpCybershieldDetailPage;
import net.atos.tests.pages.lpdetailpage5.LpDetail5Elements;
import net.atos.tests.pages.lpdetailpage5.LpDetailPage5;
import net.atos.tests.pages.lpdigitalsecuritymagazine.LpDigitalSecurityMagazinePage;
import net.atos.tests.pages.lpdigitalsecuritymagazinepage2.LpDigitalSecurityMagazinePage2;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on LpDetailPage5. Clicks that change page return the next page; others return this. */
public class LpDetail5ClickActions {
    private final Page page;

    public LpDetail5ClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to LpCybershieldDetailPage (e.g. Atos homepage) and waits for it. */
    public LpCybershieldDetailPage goToLpCybershieldDetail(String name) {
        UserActions.click(page, LpDetail5Elements.getLpCybershieldDetailLink(name));
        return new LpCybershieldDetailPage(page).get();
    }

    /** Clicks the link to LpDigitalSecurityMagazinePage (Read more - Digital security magazine 20th Edition) and waits for it. It opens in a new tab. */
    public LpDigitalSecurityMagazinePage goToLpDigitalSecurityMagazine() {
        Page tab = UserActions.clickOpeningNewTab(page, LpDetail5Elements.LP_DIGITAL_SECURITY_MAGAZINE_LINK);
        return new LpDigitalSecurityMagazinePage(tab).get();
    }

    /** Clicks the link to LpDigitalSecurityMagazinePage2 (Read more - Digital security magazine 18th Edition) and waits for it. It opens in a new tab. */
    public LpDigitalSecurityMagazinePage2 goToLpDigitalSecurityMagazine2() {
        Page tab = UserActions.clickOpeningNewTab(page, LpDetail5Elements.LP_DIGITAL_SECURITY_MAGAZINE2_LINK);
        return new LpDigitalSecurityMagazinePage2(tab).get();
    }

    /** Clicks a link to LpDetailPage5 (e.g. Anatomy of Access: Windows Device Objects from a Security Perspective) and waits for it. It opens in a new tab. */
    public LpDetailPage5 goToLpDetail5(String name, String name2) {
        Page tab = UserActions.clickOpeningNewTab(page, LpDetail5Elements.getLpDetail5Link(name, name2));
        return new LpDetailPage5(tab).get();
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public LpDetail5VerifyActions verify() {
        return new LpDetail5VerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public LpDetail5ClickActions acceptTerms() {
    //     UserActions.click(page, LpDetail5Elements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
