// Generated by Suite Builder from a crawl of the site. Checks for AlliancesPartnershipsDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.alliancespartnershipsdetail.actions;

import net.atos.tests.pages.alliancespartnershipsdetail.AlliancesPartnershipsDetailPage;
import net.atos.tests.pages.alliancespartnershipsdetail.AlliancesPartnershipsDetailElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on AlliancesPartnershipsDetailPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class AlliancesPartnershipsDetailVerifyActions {
    private final Page page;

    public AlliancesPartnershipsDetailVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public AlliancesPartnershipsDetailVerifyActions isLoaded() {
        AlliancesPartnershipsDetailPage here = new AlliancesPartnershipsDetailPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name, name2) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public AlliancesPartnershipsDetailVerifyActions isThePageOf(String name, String name2) {
        Checks.isOnPath(page, UrlPaths.alliancesPartnershipsDetail(name, name2));
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(AlliancesPartnershipsDetailElements.SOME_HEADING)}. */
    public AlliancesPartnershipsDetailVerifyActions shows(AlliancesPartnershipsDetailElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public AlliancesPartnershipsDetailVerifyActions doesNotShow(AlliancesPartnershipsDetailElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public AlliancesPartnershipsDetailVerifyActions says(AlliancesPartnershipsDetailElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public AlliancesPartnershipsDetailVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public AlliancesPartnershipsDetailVerifyActions holds(AlliancesPartnershipsDetailElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public AlliancesPartnershipsDetailVerifyActions isEmpty(AlliancesPartnershipsDetailElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public AlliancesPartnershipsDetailVerifyActions refusesEmpty(AlliancesPartnershipsDetailElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public AlliancesPartnershipsDetailVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, AlliancesPartnershipsDetailElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
