// Generated by Suite Builder from a crawl of the site. What belongs in this package.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
/**
 * One package per page type, e.g. sitedetail/:
 * SiteDetailPage (how to open it and tell it loaded; its Javadoc says what the crawl saw),
 * SiteDetailElements (locators), and actions/ with a class per door the page needs: SiteDetailReadActions and SiteDetailVerifyActions
 * always; ...ClickActions, ...EnterActions, ...CheckActions and a Tasks class when it has links or buttons, fields, checkboxes, or a form.
 *
 * <p>header/: HeaderElements and FooterElements (the links on nearly every page) and
 * actions/HeaderNavigableActions, which every page's navigateTo() returns.
 *
 * <p>A page the crawl did not read gets a package of its own, like the others:
 * ai/recipes/add-a-page-type.md.
 */
package net.atos.tests.pages;

// ==== YOURS (notes): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (notes) ====
