// Generated by Suite Builder from a crawl of the site. Page object for ClientSuccessClientStoriesDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.clientsuccessclientstoriesdetail;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.actions.ClientSuccessClientStoriesDetailClickActions;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.actions.ClientSuccessClientStoriesDetailReadActions;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.actions.ClientSuccessClientStoriesDetailVerifyActions;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       one page of a family of about 25 pages, like
 *                   /en/client-success/client-stories/unlocking-the-power-of-data-with-project-triton,
 *                   /en/client-success/client-stories/lilly-the-ai-powered-agent,
 *                   /en/client-success/client-stories/scottish-water-and-atos-partnership-in-action.
 * Stories call it:  "Misumi USA: Automating industrial component configuration and order routing
 *                   wit…", "Primetals Technologies accelerates global S/4HANA transformation with
 *                   Atos" (the links that lead here).
 * Get here:         new
 *                   ClientSuccessClientStoriesDetailPage(page).open("unlocking-the-power-of-data-with-project-triton")
 *                   from any page:
 *                   navigateTo().misumiUsaAutomatingIndustrialComponentConfigurationAndOrderRoutingWit()
 *                   (in the "Insights" menu)
 *                   from any page:
 *                   navigateTo().primetalsTechnologiesAcceleratesGlobalS4hanaTransformationWithAtos()
 *                   (in the "Insights" menu)
 *                   from SiteDetailPage: click().goToClientSuccessClientStoriesDetail("")
 *                   from SiteDetailPage3:
 *                   click().goToClientSuccessClientStoriesDetail("how-swiss-post-uses-sap-to-deliver-the-future")
 *                   from BlogDetailPage:
 *                   click().goToClientSuccessClientStoriesDetail("how-swiss-post-uses-sap-to-deliver-the-future")
 * The crawl saw:    18 pages of this type
 *                   (/en/client-success/client-stories/unlocking-the-power-of-data-with-project-triton,
 *                   /en/client-success/client-stories/lilly-the-ai-powered-agent,
 *                   /en/client-success/client-stories/scottish-water-and-atos-partnership-in-action,
 *                   ...); every one showed "At a glance" and "Outcomes".
 * Proven loaded by: the heading "At a glance" and the heading "Outcomes" (isLoaded(),
 *                   PROVES_LOADED: what a copy edit leaves alone first).
 * As crawled:       crawl/pages/en/client-success/client-stories/unlocking-the-power-of-data-with-project-triton.html,
 *                   crawl/pages/en/client-success/client-stories/lilly-the-ai-powered-agent.html,
 *                   ... (the page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to
 *                   saved-pages/ClientSuccessClientStoriesDetailPage/ (saved-pages/README.md) and
 *                   add what it shows to ClientSuccessClientStoriesDetailElements.
 * </pre>
 */
public class ClientSuccessClientStoriesDetailPage extends LoadablePage<ClientSuccessClientStoriesDetailPage> implements
        ClickableAction<ClientSuccessClientStoriesDetailClickActions>,
        ReadableAction<ClientSuccessClientStoriesDetailReadActions>,
        VerifiableAction<ClientSuccessClientStoriesDetailVerifyActions>,
        NavigableAction<HeaderNavigableActions> {

    // The crawled pages of this type had different titles, so the title is not checked.

    /** URL shapes of this page type (from the crawl): "*" is one path segment, "{n}" a number. */
    public static final List<String> URL_SHAPES = List.of("/en/client-success/client-stories/*");

    /** Pages of this type, for open() and the smoke test: the crawl's, until you choose others (a rebuild keeps your list). */
    // ==== YOURS (examples): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 45d4d9a0
    public static final List<String> EXAMPLES = List.of(
            "unlocking-the-power-of-data-with-project-triton",
            "lilly-the-ai-powered-agent",
            "scottish-water-and-atos-partnership-in-action",
            "misumi-usa-automating-with-amazon-bedrock",
            "primetals-sap-s4hana-transformation-atos",
            "ugap-leveraging-the-move-to-cloud",
            "securing-the-olympic-and-paralympic-games-paris-2024",
            "insurance-giant-achmea-accelerates-its-digital-transformation-with-elastic-observability",
            "innogys-hr-landscape-rises-to-s-4hana-cloud",
            "how-swiss-post-uses-sap-to-deliver-the-future",
            "telephony-transformation-for-nhs-trust",
            "one-erp-a-standardized-sap-s-4hana-system-for-enhanced-healthcare",
            "putting-sustainability-at-the-heart-of-pharmaceutical-manufacturing",
            "data-and-analytics-talgo",
            "sunotecs-hr-transformation-for-a-renewable-future",
            "accelerating-wa-health-system-digitalisation",
            "siemens-healthineers",
            "scottish-water-transforms-wastewater-network-management");
    // ==== END YOURS (examples) ====

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default 3a7b6841
    static final List<ClientSuccessClientStoriesDetailElements> PROVES_LOADED = List.of(
            ClientSuccessClientStoriesDetailElements.AT_A_GLANCE_HEADING,
            ClientSuccessClientStoriesDetailElements.OUTCOMES_HEADING);
    // ==== END YOURS (load-proof) ====

    /** The exact page open() asked for; null when a click brought the browser here. */
    private String expectedPath;

    public ClientSuccessClientStoriesDetailPage(Page page) {
        super(page);
    }

    /** Goes to this page and waits until it has fully loaded. */
    public ClientSuccessClientStoriesDetailPage open(String name) {
        expectedPath = UrlPaths.clientSuccessClientStoriesDetail(name);
        navigate(expectedPath);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = expectedPath != null
                ? WaitActions.waitForUrl(page, expectedPath)
                : WaitActions.waitForUrlShape(page, URL_SHAPES);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + (expectedPath != null ? expectedPath : String.join(" or ", URL_SHAPES)));
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);


        for (ClientSuccessClientStoriesDetailElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, ClientSuccessClientStoriesDetailElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 200;
    }

    @Override
    public ClientSuccessClientStoriesDetailClickActions click() {
        return new ClientSuccessClientStoriesDetailClickActions(page);
    }

    @Override
    public ClientSuccessClientStoriesDetailReadActions read() {
        return new ClientSuccessClientStoriesDetailReadActions(page);
    }

    @Override
    public ClientSuccessClientStoriesDetailVerifyActions verify() {
        return new ClientSuccessClientStoriesDetailVerifyActions(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
