// Generated by Suite Builder from a crawl of the site. Locators for LpDetailPage3.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage3;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.uri.UrlPaths;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 2 pages like /en/lp/zero-trust-networking-whitepaper, /en/lp/freedom-ai-age.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum LpDetail3Elements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "Dive Deeper": every crawled page of this type showed it; some spell it "Dive deeper". */
    DIVE_DEEPER_HEADING(page -> Headings.named(page, "Dive Deeper", "Dive deeper")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: each of its 2 pages read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: each of its 2 pages read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Previous slide (only for visual purpose, links already av...": seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Previous slide (only for visual purpose, links already available just before)']")),
    /** button "Next slide (only for visual purpose, links already availa...": seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Next slide (only for visual purpose, links already available just before)']")),

    // A form (from the crawl: nothing was typed, clicked or sent).
    /** dropdown "Preferred Language": seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    PREFERRED_LANGUAGE_SELECT(page -> page.locator("xpath=//select[@id='preferredLanguage']")),
    /** text field "First Name", required: seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    FIRST_NAME_INPUT(page -> page.locator("xpath=//input[@id='FirstName']")),
    /** text field "Last Name", required: seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    LAST_NAME_INPUT(page -> page.locator("xpath=//input[@id='LastName']")),
    /** email field "Business Email Address", required: seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    BUSINESS_EMAIL_ADDRESS_INPUT(page -> page.locator("xpath=//input[@id='Email']")),
    /** text field "Company/Organization Name", required: seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    COMPANY_ORGANIZATION_NAME_INPUT(page -> page.locator("xpath=//input[@id='Company']")),
    /** text field "Job Title": seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    JOB_TITLE_INPUT(page -> page.locator("xpath=//input[@id='SF_Job_Title__c']")),
    /** button "Submit": seen by the crawl on /en/lp/zero-trust-networking-whitepaper. */
    SUBMIT_BUTTON(page -> page.locator("xpath=//button[normalize-space()='Submit']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    LpDetail3Elements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    LpDetail3Elements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    /** A link to ClientSuccessClientStoriesDetailPage, e.g. https://atos.net/en/client-success/client-stories/lilly-the-ai-powered-agent. */
    public static PageElement getClientSuccessClientStoriesDetailLink(String name) {
        String href = "/en/client-success/client-stories/" + name;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("CLIENT_SUCCESS_CLIENT_STORIES_DETAIL_LINK", "the link to the client success client stories detail page \"" + name + "\"", page -> page.locator(xpath).first());
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
