// Generated by Suite Builder from a crawl of the site. Checks for SiteDetailPage8.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage8.actions;

import net.atos.tests.pages.sitedetailpage8.SiteDetailPage8;
import net.atos.tests.pages.sitedetailpage8.SiteDetail8Elements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on SiteDetailPage8. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class SiteDetail8VerifyActions {
    private final Page page;

    public SiteDetail8VerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public SiteDetail8VerifyActions isLoaded() {
        SiteDetailPage8 here = new SiteDetailPage8(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(id, name, name2) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public SiteDetail8VerifyActions isThePageOf(String id, String name, String name2) {
        Checks.isOnPath(page, UrlPaths.siteDetail8(id, name, name2));
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(SiteDetail8Elements.SOME_HEADING)}. */
    public SiteDetail8VerifyActions shows(SiteDetail8Elements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public SiteDetail8VerifyActions doesNotShow(SiteDetail8Elements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public SiteDetail8VerifyActions says(SiteDetail8Elements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public SiteDetail8VerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public SiteDetail8VerifyActions holds(SiteDetail8Elements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public SiteDetail8VerifyActions isEmpty(SiteDetail8Elements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public SiteDetail8VerifyActions refusesEmpty(SiteDetail8Elements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public SiteDetail8VerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, SiteDetail8Elements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
