// Generated by Suite Builder from a crawl of the site. Click actions for LpDigitalSovereigntyAnPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdigitalsovereigntyan.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.lpdigitalsovereigntyan.LpDigitalSovereigntyAnElements;
import net.atos.tests.pages.lpdigitalsovereigntyan.LpDigitalSovereigntyAnPage;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on LpDigitalSovereigntyAnPage. Clicks that change page return the next page; others return this. */
public class LpDigitalSovereigntyAnClickActions {
    private final Page page;

    public LpDigitalSovereigntyAnClickActions(Page page) {
        this.page = page;
    }

    /** Clicks the button "close". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyAnPage close() {
        UserActions.click(page, LpDigitalSovereigntyAnElements.CLOSE_BUTTON);
        return new LpDigitalSovereigntyAnPage(page);
    }

    /** Clicks the button "Submit". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public LpDigitalSovereigntyAnPage submit() {
        UserActions.click(page, LpDigitalSovereigntyAnElements.SUBMIT_BUTTON);
        return new LpDigitalSovereigntyAnPage(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public LpDigitalSovereigntyAnVerifyActions verify() {
        return new LpDigitalSovereigntyAnVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public LpDigitalSovereigntyAnClickActions acceptTerms() {
    //     UserActions.click(page, LpDigitalSovereigntyAnElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
