// Generated by Suite Builder from a crawl of the site. Tasks for LpDetailPage2.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage2;

import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Multi-step tasks on LpDetailPage2, built from its actions (fill in a form and submit it, say).
 * The crawl's own are below; add more in the YOURS block.
 */
public class LpDetail2Tasks {
    private final Page page;

    public LpDetail2Tasks(Page page) {
        this.page = page;
    }

    /**
     * Fills the "Submit your details to receive the complimentary excerpt by " form, field by field in page order, and stops before sending it: a generated
     * test never sends a form (ai/recipes/forms-and-test-data.md). To send it, a story adds {@code .click().submit()}: what the site does then is not something the crawl saw. Its values: {@code SubmitYourDetailsToReceiveTheComplimentaryExcerptBy.sample()},
     * or a copy with one changed, {@code SubmitYourDetailsToReceiveTheComplimentaryExcerptBy.sample().withPreferredLanguage("...")}.
     */
    public LpDetailPage2 fillSubmitYourDetailsToReceiveTheComplimentaryExcerptByForm(SubmitYourDetailsToReceiveTheComplimentaryExcerptBy form) {
        LpDetailPage2 here = new LpDetailPage2(page);
        here.enter().preferredLanguage(form.preferredLanguage()).firstName(form.firstName()).lastName(form.lastName()).businessEmailAddress(form.businessEmailAddress()).companyOrganizationName(form.companyOrganizationName()).jobTitle(form.jobTitle());
        return here;
    }

    /**
     * @deprecated Takes the form's record now (G-152): {@code fillSubmitYourDetailsToReceiveTheComplimentaryExcerptByForm(SubmitYourDetailsToReceiveTheComplimentaryExcerptBy.sample())}. This one goes
     * in a later release.
     */
    @Deprecated
    public LpDetailPage2 fillSubmitYourDetailsToReceiveTheComplimentaryExcerptByForm(String preferredLanguage, String firstName, String lastName, String businessEmailAddress, String companyOrganizationName, String jobTitle) {
        return fillSubmitYourDetailsToReceiveTheComplimentaryExcerptByForm(new SubmitYourDetailsToReceiveTheComplimentaryExcerptBy(preferredLanguage, firstName, lastName, businessEmailAddress, companyOrganizationName, jobTitle));
    }

    // ==== YOURS (tasks): safe to edit; regenerating keeps what is between these lines ====
    // One method per task a story names, built from this page's actions (ai/recipes/add-a-task.md), e.g.:
    // public ThankYouPage signUp(String email) {
    //     LpDetailPage2 here = new LpDetailPage2(page);
    //     here.enter().email(email);
    //     here.check().terms();
    //     return here.click().submit();
    // }
    // ==== END YOURS (tasks) ====
}
