// Generated by Suite Builder from a crawl of the site. EnterActions for EventsDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.eventsdetail.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.SiteConfig;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.eventsdetail.EventsDetailElements;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Text to type into fields on EventsDetailPage.
 * The crawl's own are below; add more (elements to EventsDetailElements, then methods here) in the YOURS block.
 */
public class EventsDetailEnterActions {
    private final Page page;

    public EventsDetailEnterActions(Page page) {
        this.page = page;
    }

    /** Chooses an option of the dropdown "Preferred Language", by its words. */
    public EventsDetailEnterActions preferredLanguage(String option) {
        UserActions.choose(page, EventsDetailElements.PREFERRED_LANGUAGE_SELECT, option);
        return this;
    }

    /** Types into the text field "First Name". */
    public EventsDetailEnterActions firstName(String text) {
        UserActions.type(page, EventsDetailElements.FIRST_NAME_INPUT, text);
        return this;
    }

    /** Empties the text field "First Name". */
    public EventsDetailEnterActions clearFirstName() {
        UserActions.clear(page, EventsDetailElements.FIRST_NAME_INPUT);
        return this;
    }

    /** Types into the text field "Last Name". */
    public EventsDetailEnterActions lastName(String text) {
        UserActions.type(page, EventsDetailElements.LAST_NAME_INPUT, text);
        return this;
    }

    /** Empties the text field "Last Name". */
    public EventsDetailEnterActions clearLastName() {
        UserActions.clear(page, EventsDetailElements.LAST_NAME_INPUT);
        return this;
    }

    /** Types into the email field "Business Email Address". */
    public EventsDetailEnterActions businessEmailAddress(String text) {
        UserActions.type(page, EventsDetailElements.BUSINESS_EMAIL_ADDRESS_INPUT, text);
        return this;
    }

    /** Empties the email field "Business Email Address". */
    public EventsDetailEnterActions clearBusinessEmailAddress() {
        UserActions.clear(page, EventsDetailElements.BUSINESS_EMAIL_ADDRESS_INPUT);
        return this;
    }

    /** Types into the text field "Company/Organization Name". */
    public EventsDetailEnterActions companyOrganizationName(String text) {
        UserActions.type(page, EventsDetailElements.COMPANY_ORGANIZATION_NAME_INPUT, text);
        return this;
    }

    /** Empties the text field "Company/Organization Name". */
    public EventsDetailEnterActions clearCompanyOrganizationName() {
        UserActions.clear(page, EventsDetailElements.COMPANY_ORGANIZATION_NAME_INPUT);
        return this;
    }

    /** Types into the text field "Job Title". */
    public EventsDetailEnterActions jobTitle(String text) {
        UserActions.type(page, EventsDetailElements.JOB_TITLE_INPUT, text);
        return this;
    }

    /** Empties the text field "Job Title". */
    public EventsDetailEnterActions clearJobTitle() {
        UserActions.clear(page, EventsDetailElements.JOB_TITLE_INPUT);
        return this;
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public EventsDetailVerifyActions verify() {
        return new EventsDetailVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per field, e.g.:
    // public EventsDetailEnterActions email(String text) {
    //     UserActions.type(page, EventsDetailElements.EMAIL_INPUT, text);
    //     return this;
    // }
    // A password or other secret: UserActions.typeSecret(page, EventsDetailElements.PASSWORD_INPUT, SiteConfig.secret("password"));
    // A dropdown: UserActions.choose(page, EventsDetailElements.COUNTRY_SELECT, country);
    // ==== END YOURS (actions) ====
}
