// Generated by Suite Builder from a crawl of the site. Click actions for EventsDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.eventsdetail.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.eventsdetail.EventsDetailElements;
import net.atos.tests.pages.eventsdetail.EventsDetailPage;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on EventsDetailPage. Clicks that change page return the next page; others return this. */
public class EventsDetailClickActions {
    private final Page page;

    public EventsDetailClickActions(Page page) {
        this.page = page;
    }

    /** Clicks the button "Previous slide (only for visual purpose, links already av...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public EventsDetailPage previousSlideOnlyForVisual() {
        UserActions.click(page, EventsDetailElements.PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new EventsDetailPage(page);
    }

    /** Clicks the button "Next slide (only for visual purpose, links already availa...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public EventsDetailPage nextSlideOnlyForVisual() {
        UserActions.click(page, EventsDetailElements.NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new EventsDetailPage(page);
    }

    /** Clicks the button "Play Click to play video". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public EventsDetailPage playClickToPlayVideo() {
        UserActions.click(page, EventsDetailElements.PLAY_CLICK_TO_PLAY_VIDEO_BUTTON);
        return new EventsDetailPage(page);
    }

    /** Clicks the button "Submit". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public EventsDetailPage submit() {
        UserActions.click(page, EventsDetailElements.SUBMIT_BUTTON);
        return new EventsDetailPage(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public EventsDetailVerifyActions verify() {
        return new EventsDetailVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public EventsDetailClickActions acceptTerms() {
    //     UserActions.click(page, EventsDetailElements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
