// Generated by Suite Builder from a crawl of the site. EnterActions for ClientSuccessClientStoriesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.clientsuccessclientstories.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.SiteConfig;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.clientsuccessclientstories.ClientSuccessClientStoriesElements;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Text to type into fields on ClientSuccessClientStoriesPage.
 * The crawl's own are below; add more (elements to ClientSuccessClientStoriesElements, then methods here) in the YOURS block.
 */
public class ClientSuccessClientStoriesEnterActions {
    private final Page page;

    public ClientSuccessClientStoriesEnterActions(Page page) {
        this.page = page;
    }

    /** Types into the text field "Search Client story". */
    public ClientSuccessClientStoriesEnterActions searchClientStory(String text) {
        UserActions.type(page, ClientSuccessClientStoriesElements.SEARCH_CLIENT_STORY_INPUT, text);
        return this;
    }

    /** Empties the text field "Search Client story". */
    public ClientSuccessClientStoriesEnterActions clearSearchClientStory() {
        UserActions.clear(page, ClientSuccessClientStoriesElements.SEARCH_CLIENT_STORY_INPUT);
        return this;
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public ClientSuccessClientStoriesVerifyActions verify() {
        return new ClientSuccessClientStoriesVerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per field, e.g.:
    // public ClientSuccessClientStoriesEnterActions email(String text) {
    //     UserActions.type(page, ClientSuccessClientStoriesElements.EMAIL_INPUT, text);
    //     return this;
    // }
    // A password or other secret: UserActions.typeSecret(page, ClientSuccessClientStoriesElements.PASSWORD_INPUT, SiteConfig.secret("password"));
    // A dropdown: UserActions.choose(page, ClientSuccessClientStoriesElements.COUNTRY_SELECT, country);
    // ==== END YOURS (actions) ====
}
