// Generated by Suite Builder from a crawl of the site. Checks for ClientSuccessClientStoriesPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.clientsuccessclientstories.actions;

import net.atos.tests.pages.clientsuccessclientstories.ClientSuccessClientStoriesPage;
import net.atos.tests.pages.clientsuccessclientstories.ClientSuccessClientStoriesElements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on ClientSuccessClientStoriesPage. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class ClientSuccessClientStoriesVerifyActions {
    private final Page page;

    public ClientSuccessClientStoriesVerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load, title and key elements. */
    public ClientSuccessClientStoriesVerifyActions isLoaded() {
        ClientSuccessClientStoriesPage here = new ClientSuccessClientStoriesPage(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public ClientSuccessClientStoriesVerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Atos Client Stories\", \"Celebrating success\", \"Flender China: Accelerating engineering excellence with Agentic AI\", \"Primetals Technologies accelerates global S/4HANA transformation with Atos\", \"SUNOTEC’s HR transformation for a renewable future\", \"Translink: End-to-end observability for seamless travel\")",
                ClientSuccessClientStoriesElements.ATOS_CLIENT_STORIES_HEADING, ClientSuccessClientStoriesElements.CELEBRATING_SUCCESS_HEADING, ClientSuccessClientStoriesElements.FLENDER_CHINA_ACCELERATING_ENGINEERING_EXCELLENCE_WITH_AGENTIC_AI_HEADING, ClientSuccessClientStoriesElements.PRIMETALS_TECHNOLOGIES_ACCELERATES_GLOBAL_S_4HANA_TRANSFORMATION_WITH_ATOS_HEADING, ClientSuccessClientStoriesElements.SUNOTEC_S_HR_TRANSFORMATION_FOR_A_RENEWABLE_FUTURE_HEADING, ClientSuccessClientStoriesElements.TRANSLINK_END_TO_END_OBSERVABILITY_FOR_SEAMLESS_TRAVEL_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(ClientSuccessClientStoriesElements.SOME_HEADING)}. */
    public ClientSuccessClientStoriesVerifyActions shows(ClientSuccessClientStoriesElements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public ClientSuccessClientStoriesVerifyActions doesNotShow(ClientSuccessClientStoriesElements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public ClientSuccessClientStoriesVerifyActions says(ClientSuccessClientStoriesElements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public ClientSuccessClientStoriesVerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public ClientSuccessClientStoriesVerifyActions holds(ClientSuccessClientStoriesElements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public ClientSuccessClientStoriesVerifyActions isEmpty(ClientSuccessClientStoriesElements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public ClientSuccessClientStoriesVerifyActions refusesEmpty(ClientSuccessClientStoriesElements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public ClientSuccessClientStoriesVerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, ClientSuccessClientStoriesElements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
