// Generated by Suite Builder from a crawl of the site. Page object for LpDigitalSovereigntyAnPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdigitalsovereigntyan;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.EnterableAction;
import net.atos.tests.core.actions.ExecutableTask;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.pages.lpdigitalsovereigntyan.actions.LpDigitalSovereigntyAnClickActions;
import net.atos.tests.pages.lpdigitalsovereigntyan.actions.LpDigitalSovereigntyAnEnterActions;
import net.atos.tests.pages.lpdigitalsovereigntyan.actions.LpDigitalSovereigntyAnReadActions;
import net.atos.tests.pages.lpdigitalsovereigntyan.actions.LpDigitalSovereigntyAnVerifyActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /en/lp/digital-sovereignty-an-atos-strategic-growth-pillar.
 * Stories call it:  "Learn more" (the links that lead here).
 * Get here:         new LpDigitalSovereigntyAnPage(page).open()
 *                   from BlogDetailPage: click().goToLpDigitalSovereigntyAn()
 * The crawl saw:    1 page of this type
 *                   (/en/lp/digital-sovereignty-an-atos-strategic-growth-pillar); it showed
 *                   "Digital sovereignty is not optional anymore", "Stay in control of your
 *                   critical data and operations", "Turn digital sovereignty into a competitive
 *                   advantage", "Making sovereignty a board-level imperative", "The benefits of our
 *                   approach to digital sovereignty" and "Dive deeper".
 * Proven loaded by: the main heading and the heading "Digital sovereignty is not optional anymore"
 *                   (isLoaded(), PROVES_LOADED: what a copy edit leaves alone first).
 * Has a form:       on 1 of 1 page. Sending it on the live site sends real data: read
 *                   ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/en/lp/digital-sovereignty-an-atos-strategic-growth-pillar.html (the
 *                   page's HTML when crawled: check a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/LpDigitalSovereigntyAnPage/
 *                   (saved-pages/README.md) and add what it shows to
 *                   LpDigitalSovereigntyAnElements.
 * </pre>
 */
public class LpDigitalSovereigntyAnPage extends LoadablePage<LpDigitalSovereigntyAnPage> implements
        ClickableAction<LpDigitalSovereigntyAnClickActions>,
        EnterableAction<LpDigitalSovereigntyAnEnterActions>,
        ReadableAction<LpDigitalSovereigntyAnReadActions>,
        VerifiableAction<LpDigitalSovereigntyAnVerifyActions>,
        ExecutableTask<LpDigitalSovereigntyAnTasks>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "Digital sovereignty is not optional anymore - Atos";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default ce5f9a1c
    static final List<LpDigitalSovereigntyAnElements> PROVES_LOADED = List.of(
            LpDigitalSovereigntyAnElements.MAIN_HEADING,
            LpDigitalSovereigntyAnElements.DIGITAL_SOVEREIGNTY_IS_NOT_OPTIONAL_ANYMORE_HEADING);
    // ==== END YOURS (load-proof) ====

    public LpDigitalSovereigntyAnPage(Page page) {
        super(page);
    }

    /** Goes to /en/lp/digital-sovereignty-an-atos-strategic-growth-pillar and waits until it has fully loaded. */
    public LpDigitalSovereigntyAnPage open() {
        navigate(UrlPaths.LP_DIGITAL_SOVEREIGNTY_AN);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.LP_DIGITAL_SOVEREIGNTY_AN);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.LP_DIGITAL_SOVEREIGNTY_AN);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (LpDigitalSovereigntyAnElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, LpDigitalSovereigntyAnElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 0;
    }

    @Override
    public LpDigitalSovereigntyAnClickActions click() {
        return new LpDigitalSovereigntyAnClickActions(page);
    }

    @Override
    public LpDigitalSovereigntyAnEnterActions enter() {
        return new LpDigitalSovereigntyAnEnterActions(page);
    }

    @Override
    public LpDigitalSovereigntyAnReadActions read() {
        return new LpDigitalSovereigntyAnReadActions(page);
    }

    @Override
    public LpDigitalSovereigntyAnVerifyActions verify() {
        return new LpDigitalSovereigntyAnVerifyActions(page);
    }

    @Override
    public LpDigitalSovereigntyAnTasks execute() {
        return new LpDigitalSovereigntyAnTasks(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
