// Generated by Suite Builder from a crawl of the site. Locators for AlliancesPartnershipsDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.alliancespartnershipsdetail;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.uri.UrlPaths;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 4 pages like /en/services/cybersecurity/emerging-cyber, /en/services/digital-applications/business-solutions, /en/alliances-partnerships/atos-and-aws/agentX.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum AlliancesPartnershipsDetailElements implements PageElement {
    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main heading: each of its 4 pages read has one main heading (h1), whatever it says. */
    MAIN_HEADING(page -> page.locator("xpath=//h1 >> visible=true").first(), "the main heading"),
    /** The main region: each of its 4 pages read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "Previous slide (only for visual purpose, links already av...": seen by the crawl on /en/services/cybersecurity/emerging-cyber. */
    PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Previous slide (only for visual purpose, links already available just before)']")),
    /** button "Next slide (only for visual purpose, links already availa...": seen by the crawl on /en/services/cybersecurity/emerging-cyber. */
    NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Next slide (only for visual purpose, links already available just before)']")),
    /** button "close": seen by the crawl on /en/alliances-partnerships/atos-and-aws/agentX. */
    CLOSE_BUTTON(page -> page.locator("xpath=//button[@aria-label='close']")),
    /** button "Play Click to play video": seen by the crawl on /en/alliances-partnerships/atos-and-aws/agentX. */
    PLAY_CLICK_TO_PLAY_VIDEO_BUTTON(page -> page.locator("xpath=//div[@aria-label='Play Click to play video']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    AlliancesPartnershipsDetailElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    AlliancesPartnershipsDetailElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    /** A link to SiteDetailPage4, e.g. https://atos.net/en/alliances-partnerships/atos-and-aws. */
    public static PageElement getSiteDetail4Link(String name, String name2) {
        String href = "/en/" + name + "/" + name2;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("SITE_DETAIL4_LINK", "the link to the site detail page4 \"" + name + "/" + name2 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to SiteDetailPage2, e.g. /en/contact-us. */
    public static PageElement getSiteDetail2Link(String name) {
        String href = "/en/" + name;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + "] >> visible=true";
        return PageElement.of("SITE_DETAIL2_LINK", "the link to the site detail page2 \"" + name + "\"", page -> page.locator(xpath).first());
    }

    /** A link to SiteDetailPage5, e.g. https://atos.net/en/services/digital-applications/business-solutions/data2pdf. */
    public static PageElement getSiteDetail5Link(String name, String name2, String name3, String name4) {
        String href = "/en/" + name + "/" + name2 + "/" + name3 + "/" + name4;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("SITE_DETAIL5_LINK", "the link to the site detail page5 \"" + name + "/" + name2 + "/" + name3 + "/" + name4 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to AlliancesPartnershipsDetailPage, e.g. /en/alliances-partnerships/atos-and-aws/agentx. */
    public static PageElement getAlliancesPartnershipsDetailLink(String name, String name2) {
        String href = "/en/alliances-partnerships/" + name + "/" + name2;
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + "] >> visible=true";
        return PageElement.of("ALLIANCES_PARTNERSHIPS_DETAIL_LINK", "the link to the alliances partnerships detail page \"" + name + "/" + name2 + "\"", page -> page.locator(xpath).first());
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
