// Generated by Suite Builder from a crawl of the site. What belongs in this package.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
/**
 * UrlPaths: the path of every page the crawl found, and a place for paths it did not.
 */
package net.atos.tests.uri;

// ==== YOURS (notes): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (notes) ====
