// Generated by Suite Builder from a crawl of the site. Click actions for SiteDetailPage9.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.sitedetailpage9.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.StepLog;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.clientsuccessclientstoriesdetail.ClientSuccessClientStoriesDetailPage;
import net.atos.tests.pages.sitedetailpage2.SiteDetailPage2;
import net.atos.tests.pages.sitedetailpage3.SiteDetailPage3;
import net.atos.tests.pages.sitedetailpage8.SiteDetailPage8;
import net.atos.tests.pages.sitedetailpage9.SiteDetail9Elements;
import net.atos.tests.pages.sitedetailpage9.SiteDetailPage9;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** What can be clicked on SiteDetailPage9. Clicks that change page return the next page; others return this. */
public class SiteDetail9ClickActions {
    private final Page page;

    public SiteDetail9ClickActions(Page page) {
        this.page = page;
    }

    /** Clicks a link to SiteDetailPage2 (e.g. Privacy) and waits for it. */
    public SiteDetailPage2 goToSiteDetail2(String name, String name2) {
        UserActions.click(page, SiteDetail9Elements.getSiteDetail2Link(name, name2));
        return new SiteDetailPage2(page).get();
    }

    /** Clicks a link to SiteDetailPage3 (e.g. Atos Türkiye Customer Services) and waits for it. */
    public SiteDetailPage3 goToSiteDetail3(String name) {
        UserActions.click(page, SiteDetail9Elements.getSiteDetail3Link(name));
        return new SiteDetailPage3(page).get();
    }

    /** Clicks a link to ClientSuccessClientStoriesDetailPage (e.g. Read more >) and waits for it. It opens in a new tab. */
    public ClientSuccessClientStoriesDetailPage goToClientSuccessClientStoriesDetail(String name) {
        Page tab = UserActions.clickOpeningNewTab(page, SiteDetail9Elements.getClientSuccessClientStoriesDetailLink(name));
        return new ClientSuccessClientStoriesDetailPage(tab).get();
    }

    /** Clicks a link to SiteDetailPage8 (e.g. Read more - Atos launches Atos Sovereign Cloud, a trusted modernization platfor…) and waits for it. */
    public SiteDetailPage8 goToSiteDetail8(String id, String name, String name2) {
        UserActions.click(page, SiteDetail9Elements.getSiteDetail8Link(id, name, name2));
        return new SiteDetailPage8(page).get();
    }

    /** Clicks the button "Previous slide (only for visual purpose, links already av...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 previousSlideOnlyForVisual() {
        UserActions.click(page, SiteDetail9Elements.PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Next slide (only for visual purpose, links already availa...". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 nextSlideOnlyForVisual() {
        UserActions.click(page, SiteDetail9Elements.NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Play Atos - Your Global AI-powered Digital Partner". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 playAtosYourGlobalAi() {
        UserActions.click(page, SiteDetail9Elements.PLAY_ATOS_YOUR_GLOBAL_AI_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Go to slide 1". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 goToSlide1() {
        UserActions.click(page, SiteDetail9Elements.GO_TO_SLIDE_1_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Go to slide 2". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 goToSlide2() {
        UserActions.click(page, SiteDetail9Elements.GO_TO_SLIDE_2_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Submit". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 submit() {
        UserActions.click(page, SiteDetail9Elements.SUBMIT_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Play Click to play video". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 playClickToPlayVideo() {
        UserActions.click(page, SiteDetail9Elements.PLAY_CLICK_TO_PLAY_VIDEO_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "previous arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 previousArrow() {
        UserActions.click(page, SiteDetail9Elements.PREVIOUS_ARROW_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "next arrow". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 nextArrow() {
        UserActions.click(page, SiteDetail9Elements.NEXT_ARROW_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Western Australian public health". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 westernAustralianPublicHealth() {
        UserActions.click(page, SiteDetail9Elements.WESTERN_AUSTRALIAN_PUBLIC_HEALTH_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Siemens". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 siemens() {
        UserActions.click(page, SiteDetail9Elements.SIEMENS_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Reimagining Engineering with Sovereign GenAI". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 reimaginingEngineeringWithSovereignGen() {
        UserActions.click(page, SiteDetail9Elements.REIMAGINING_ENGINEERING_WITH_SOVEREIGN_GEN_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Flender China". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 flenderChina() {
        UserActions.click(page, SiteDetail9Elements.FLENDER_CHINA_BUTTON);
        return new SiteDetailPage9(page);
    }

    /** Clicks the button "Go to slide 1". Where it leads the crawl did not see: it returns this page, not checked; a story checks where it lands. */
    public SiteDetailPage9 goToSlide12() {
        UserActions.click(page, SiteDetail9Elements.GO_TO_SLIDE_1_BUTTON_2);
        return new SiteDetailPage9(page);
    }

    /** Done here: the page's checks come next, so a story's chain ends on verify(). */
    public SiteDetail9VerifyActions verify() {
        return new SiteDetail9VerifyActions(page);
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per thing to click, named for what a visitor does (ai/recipes/add-an-action.md), e.g.:
    // public SiteDetail9ClickActions acceptTerms() {
    //     UserActions.click(page, SiteDetail9Elements.ACCEPT_BUTTON);
    //     return this;
    // }
    // ==== END YOURS (actions) ====
}
