// Generated by Suite Builder from a crawl of the site. Tasks for NewsroomBrandCenterPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.newsroombrandcenter;

import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Multi-step tasks on NewsroomBrandCenterPage, built from its actions (fill in a form and submit it, say).
 * The crawl's own are below; add more in the YOURS block.
 */
public class NewsroomBrandCenterTasks {
    private final Page page;

    public NewsroomBrandCenterTasks(Page page) {
        this.page = page;
    }

    /**
     * Fills the "Request to download the Atos logo in high resolution" form, field by field in page order, and stops before sending it: a generated
     * test never sends a form (ai/recipes/forms-and-test-data.md). To send it, a story adds {@code .click().submit()}: what the site does then is not something the crawl saw. Its values: {@code RequestToDownloadTheAtosLogoInHighResolution.sample()},
     * or a copy with one changed, {@code RequestToDownloadTheAtosLogoInHighResolution.sample().withNameAndLastname("...")}.
     */
    public NewsroomBrandCenterPage fillRequestToDownloadTheAtosLogoInHighResolutionForm(RequestToDownloadTheAtosLogoInHighResolution form) {
        NewsroomBrandCenterPage here = new NewsroomBrandCenterPage(page);
        here.enter().nameAndLastname(form.nameAndLastname()).email(form.email()).companyName(form.companyName()).telephone(form.telephone()).purposeOfUsageOfAtos(form.purposeOfUsageOfAtos());
        return here;
    }

    /**
     * @deprecated Takes the form's record now (G-152): {@code fillRequestToDownloadTheAtosLogoInHighResolutionForm(RequestToDownloadTheAtosLogoInHighResolution.sample())}. This one goes
     * in a later release.
     */
    @Deprecated
    public NewsroomBrandCenterPage fillRequestToDownloadTheAtosLogoInHighResolutionForm(String nameAndLastname, String email, String companyName, String telephone, String purposeOfUsageOfAtos) {
        return fillRequestToDownloadTheAtosLogoInHighResolutionForm(new RequestToDownloadTheAtosLogoInHighResolution(nameAndLastname, email, companyName, telephone, purposeOfUsageOfAtos));
    }

    /**
     * Fills the "Please describe the suspected violation. Click all that appl" form, field by field in page order, and stops before sending it: a generated
     * test never sends a form (ai/recipes/forms-and-test-data.md). To send it, a story adds {@code .click().submit2()}: what the site does then is not something the crawl saw. Its values: {@code PleaseDescribeTheSuspectedViolationClickAllThatAppl.sample()},
     * or a copy with one changed, {@code PleaseDescribeTheSuspectedViolationClickAllThatAppl.sample().withWebSiteUrl("...")}.
     */
    public NewsroomBrandCenterPage fillPleaseDescribeTheSuspectedViolationClickAllThatApplForm(PleaseDescribeTheSuspectedViolationClickAllThatAppl form) {
        NewsroomBrandCenterPage here = new NewsroomBrandCenterPage(page);
        here.enter().webSiteUrl(form.webSiteUrl()).printedMaterialsDescribe(form.printedMaterialsDescribe()).otherDescribe(form.otherDescribe()).additionalComments(form.additionalComments()).firstName(form.firstName()).lastName(form.lastName()).email2(form.email2()).anyRelationshipToAtos(form.anyRelationshipToAtos());
        return here;
    }

    /**
     * @deprecated Takes the form's record now (G-152): {@code fillPleaseDescribeTheSuspectedViolationClickAllThatApplForm(PleaseDescribeTheSuspectedViolationClickAllThatAppl.sample())}. This one goes
     * in a later release.
     */
    @Deprecated
    public NewsroomBrandCenterPage fillPleaseDescribeTheSuspectedViolationClickAllThatApplForm(String webSiteUrl, String printedMaterialsDescribe, String otherDescribe, String additionalComments, String firstName, String lastName, String email2, String anyRelationshipToAtos) {
        return fillPleaseDescribeTheSuspectedViolationClickAllThatApplForm(new PleaseDescribeTheSuspectedViolationClickAllThatAppl(webSiteUrl, printedMaterialsDescribe, otherDescribe, additionalComments, firstName, lastName, email2, anyRelationshipToAtos));
    }

    // ==== YOURS (tasks): safe to edit; regenerating keeps what is between these lines ====
    // One method per task a story names, built from this page's actions (ai/recipes/add-a-task.md), e.g.:
    // public ThankYouPage signUp(String email) {
    //     NewsroomBrandCenterPage here = new NewsroomBrandCenterPage(page);
    //     here.enter().email(email);
    //     here.check().terms();
    //     return here.click().submit();
    // }
    // ==== END YOURS (tasks) ====
}
