// Generated by Suite Builder from a crawl of the site. Page object for NewsroomBrandCenterPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.newsroombrandcenter;

import com.microsoft.playwright.Page;
import net.atos.tests.core.LoadablePage;
import net.atos.tests.core.WaitActions;
import net.atos.tests.core.actions.CheckableAction;
import net.atos.tests.core.actions.ClickableAction;
import net.atos.tests.core.actions.EnterableAction;
import net.atos.tests.core.actions.ExecutableTask;
import net.atos.tests.core.actions.NavigableAction;
import net.atos.tests.core.actions.ReadableAction;
import net.atos.tests.core.actions.VerifiableAction;
import net.atos.tests.pages.header.actions.HeaderNavigableActions;
import net.atos.tests.pages.newsroombrandcenter.actions.NewsroomBrandCenterCheckActions;
import net.atos.tests.pages.newsroombrandcenter.actions.NewsroomBrandCenterClickActions;
import net.atos.tests.pages.newsroombrandcenter.actions.NewsroomBrandCenterEnterActions;
import net.atos.tests.pages.newsroombrandcenter.actions.NewsroomBrandCenterReadActions;
import net.atos.tests.pages.newsroombrandcenter.actions.NewsroomBrandCenterVerifyActions;
import net.atos.tests.uri.UrlPaths;

import java.util.List;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * <pre>
 * What it is:       the page at /en/newsroom/brand-center.
 * Stories call it:  "Visit our brand center &gt;" (the links that lead here).
 * Get here:         new NewsroomBrandCenterPage(page).open()
 *                   from NewsroomPage: click().goToNewsroomBrandCenter()
 * The crawl saw:    1 page of this type (/en/newsroom/brand-center); it showed "Brand center",
 *                   "Request to download the Atos logo in high resolution", "CAPTCHA", "Report of
 *                   suspected usage violation", "Please describe the suspected violation. Click all
 *                   that apply *(Required)" and "Atos copyright protected materials (including
 *                   whitepapers, training materials)".
 * Proven loaded by: the main heading and the heading "Brand center" (isLoaded(), PROVES_LOADED:
 *                   what a copy edit leaves alone first).
 * Has a form:       on 1 of 1 page. Sending it on the live site sends real data: read
 *                   ai/recipes/forms-and-test-data.md first.
 * As crawled:       crawl/pages/en/newsroom/brand-center.html (the page's HTML when crawled: check
 *                   a locator there with suite locate).
 * Not seen:         what is behind a login, what a button that is not a link opens, or what a form
 *                   does when sent. Save the page to saved-pages/NewsroomBrandCenterPage/
 *                   (saved-pages/README.md) and add what it shows to NewsroomBrandCenterElements.
 * </pre>
 */
public class NewsroomBrandCenterPage extends LoadablePage<NewsroomBrandCenterPage> implements
        ClickableAction<NewsroomBrandCenterClickActions>,
        CheckableAction<NewsroomBrandCenterCheckActions>,
        EnterableAction<NewsroomBrandCenterEnterActions>,
        ReadableAction<NewsroomBrandCenterReadActions>,
        VerifiableAction<NewsroomBrandCenterVerifyActions>,
        ExecutableTask<NewsroomBrandCenterTasks>,
        NavigableAction<HeaderNavigableActions> {

    /** The title from the crawl. */
    public static final String TITLE = "Brand center - Atos";

    /**
     * What proves this page has loaded: isLoaded() waits for each to show. From the crawl: every page
     * of this type had them; what a copy edit leaves alone comes first. Take out one that comes and goes (an offer, a
     * banner); a rebuild keeps your list, and brings the crawl's newer one while you leave it as it is.
     */
    // ==== YOURS (load-proof): safe to edit; regenerating keeps your change, and brings a newer default while it is unchanged ==== default fbada715
    static final List<NewsroomBrandCenterElements> PROVES_LOADED = List.of(
            NewsroomBrandCenterElements.MAIN_HEADING,
            NewsroomBrandCenterElements.BRAND_CENTER_HEADING);
    // ==== END YOURS (load-proof) ====

    public NewsroomBrandCenterPage(Page page) {
        super(page);
    }

    /** Goes to /en/newsroom/brand-center and waits until it has fully loaded. */
    public NewsroomBrandCenterPage open() {
        navigate(UrlPaths.NEWSROOM_BRAND_CENTER);
        return get();
    }

    @Override
    protected void load() {
        // Not needed: open() goes to the page, and clicks arrive here.
    }

    @Override
    protected void isLoaded() throws Error {
        boolean urlIsCorrect = WaitActions.waitForUrl(page, UrlPaths.NEWSROOM_BRAND_CENTER);
        // The wrong page fails at once: no wait for its load first. An AssertionError, so a report files it as a failed check.
        if (!urlIsCorrect) {
            throw new AssertionError(name() + " did not load! URL was " + page.url() + ", expected " + UrlPaths.NEWSROOM_BRAND_CENTER);
        }
        boolean pageLoaded = WaitActions.waitForPageLoad(page);

        if (!WaitActions.waitForTitle(page, TITLE)) {
            throw new AssertionError(name() + " did not load! Title was \"" + page.title() + "\", expected \"" + TITLE + "\"");
        }

        for (NewsroomBrandCenterElements element : PROVES_LOADED) {
            if (!WaitActions.waitForVisibilityOf(page, element)) {
                throw new AssertionError(name() + " did not load! " + element.name() + " was not visible!");
            }
        }
        if (!pageLoaded) WaitActions.noteStillLoading(page, name()); // proven by address, title and checks: a late load event is named, not failed

        // ==== YOURS (load-checks): safe to edit; regenerating keeps what is between these lines ====
        // More proof that the page has really finished (ai/recipes/wait-for-a-slow-page.md), e.g.:
        // if (!WaitActions.waitForInvisibilityOf(page, NewsroomBrandCenterElements.LOADING_SPINNER)) {
        //     throw new AssertionError(name() + " did not load! LOADING_SPINNER never went away!");
        // }
        // ==== END YOURS (load-checks) ====
    }

    /** What the crawl timed of these pages after their load event (core/Timings flags one much slower). */
    @Override
    protected long crawlSettledMs() {
        return 400;
    }

    @Override
    public NewsroomBrandCenterClickActions click() {
        return new NewsroomBrandCenterClickActions(page);
    }

    @Override
    public NewsroomBrandCenterCheckActions check() {
        return new NewsroomBrandCenterCheckActions(page, true);
    }

    @Override
    public NewsroomBrandCenterCheckActions uncheck() {
        return new NewsroomBrandCenterCheckActions(page, false);
    }

    @Override
    public NewsroomBrandCenterEnterActions enter() {
        return new NewsroomBrandCenterEnterActions(page);
    }

    @Override
    public NewsroomBrandCenterReadActions read() {
        return new NewsroomBrandCenterReadActions(page);
    }

    @Override
    public NewsroomBrandCenterVerifyActions verify() {
        return new NewsroomBrandCenterVerifyActions(page);
    }

    @Override
    public NewsroomBrandCenterTasks execute() {
        return new NewsroomBrandCenterTasks(page);
    }

    @Override
    public HeaderNavigableActions navigateTo() {
        return new HeaderNavigableActions(page);
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // ==== END YOURS (extras) ====
}
