// Generated by Suite Builder from a crawl of the site. Checks for LpDetailPage3.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage3.actions;

import net.atos.tests.pages.lpdetailpage3.LpDetailPage3;
import net.atos.tests.pages.lpdetailpage3.LpDetail3Elements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on LpDetailPage3. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class LpDetail3VerifyActions {
    private final Page page;

    public LpDetail3VerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public LpDetail3VerifyActions isLoaded() {
        LpDetailPage3 here = new LpDetailPage3(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public LpDetail3VerifyActions isThePageOf(String name) {
        Checks.isOnPath(page, UrlPaths.lpDetail3(name));
        return this;
    }

    /** Every section heading this page type shares is visible. */
    public LpDetail3VerifyActions sectionHeadingsVisible() {
        Checks.allShown(page, "its section headings (\"Dive Deeper\")",
                LpDetail3Elements.DIVE_DEEPER_HEADING);
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(LpDetail3Elements.SOME_HEADING)}. */
    public LpDetail3VerifyActions shows(LpDetail3Elements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public LpDetail3VerifyActions doesNotShow(LpDetail3Elements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public LpDetail3VerifyActions says(LpDetail3Elements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public LpDetail3VerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public LpDetail3VerifyActions holds(LpDetail3Elements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public LpDetail3VerifyActions isEmpty(LpDetail3Elements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public LpDetail3VerifyActions refusesEmpty(LpDetail3Elements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public LpDetail3VerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, LpDetail3Elements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
