// Generated by Suite Builder from a crawl of the site. Checks for LpDetailPage2.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage2.actions;

import net.atos.tests.pages.lpdetailpage2.LpDetailPage2;
import net.atos.tests.pages.lpdetailpage2.LpDetail2Elements;
import net.atos.tests.core.Checks;
import net.atos.tests.core.StepLog;
import net.atos.tests.uri.UrlPaths;
import com.microsoft.playwright.Page;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/** Checks on LpDetailPage2. Each one is a step of the test, and fails saying what it expected, in plain English. */
public class LpDetail2VerifyActions {
    private final Page page;

    public LpDetail2VerifyActions(Page page) {
        this.page = page;
    }

    /** The page has fully loaded: URL, page load and key elements. */
    public LpDetail2VerifyActions isLoaded() {
        LpDetailPage2 here = new LpDetailPage2(page);
        StepLog.step("Check that " + here.describe() + " has fully loaded");
        here.get();
        return this;
    }

    /**
     * It is the page of these arguments, the one open(name) goes to: its address says so.
     * isLoaded() proves only that it is one of this family's pages.
     */
    public LpDetail2VerifyActions isThePageOf(String name) {
        Checks.isOnPath(page, UrlPaths.lpDetail2(name));
        return this;
    }

    /** The element is shown, e.g. {@code verify().shows(LpDetail2Elements.SOME_HEADING)}. */
    public LpDetail2VerifyActions shows(LpDetail2Elements element) {
        Checks.isShown(page, element);
        return this;
    }

    /** The element is not shown (gone, or hidden). */
    public LpDetail2VerifyActions doesNotShow(LpDetail2Elements element) {
        Checks.isNotShown(page, element);
        return this;
    }

    /** The element says exactly this (whatever the spacing). */
    public LpDetail2VerifyActions says(LpDetail2Elements element, String text) {
        Checks.hasText(page, element, text);
        return this;
    }

    /** The page shows this text somewhere a visitor can see it. */
    public LpDetail2VerifyActions showsText(String text) {
        Checks.pageShowsText(page, text);
        return this;
    }

    /** The field holds exactly this: what was typed into it. */
    public LpDetail2VerifyActions holds(LpDetail2Elements element, String text) {
        Checks.hasValue(page, element, text);
        return this;
    }

    /** The field is empty. */
    public LpDetail2VerifyActions isEmpty(LpDetail2Elements element) {
        Checks.hasValue(page, element, "");
        return this;
    }

    /** The browser will not send the field's form with it empty (it is required); nothing is sent to find out. */
    public LpDetail2VerifyActions refusesEmpty(LpDetail2Elements element) {
        Checks.refusesEmpty(page, element);
        return this;
    }

    // ==== YOURS (checks): safe to edit; regenerating keeps what is between these lines ====
    // Checks a story needs, named for what it expects (ai/recipes/add-an-action.md), e.g.:
    // public LpDetail2VerifyActions showsOrderConfirmation() {
    //     Checks.isShown(page, LpDetail2Elements.CONFIRMATION_HEADING);
    //     return this;
    // }
    // ==== END YOURS (checks) ====
}
