// Generated by Suite Builder from a crawl of the site. ReadActions for LpDetailPage2.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.lpdetailpage2.actions;

import com.microsoft.playwright.Page;
import net.atos.tests.core.SiteConfig;
import net.atos.tests.core.UserActions;
import net.atos.tests.pages.lpdetailpage2.LpDetail2Elements;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Values to read off LpDetailPage2.
 * The crawl does not know these: add elements to LpDetail2Elements, then methods here.
 */
public class LpDetail2ReadActions {
    private final Page page;

    public LpDetail2ReadActions(Page page) {
        this.page = page;
    }

    /** The page's title. */
    public String title() {
        return page.title();
    }

    /** The page's address. */
    public String url() {
        return page.url();
    }

    // ==== YOURS (actions): safe to edit; regenerating keeps what is between these lines ====
    // One method per value, e.g.:
    // public String orderNumber() {
    //     return UserActions.readText(page, LpDetail2Elements.ORDER_NUMBER_TEXT);
    // }
    // ==== END YOURS (actions) ====
}
