// Generated by Suite Builder from a crawl of the site. Locators for IndustriesDetailPage.
// EDIT RULES: edit only inside YOURS blocks; regenerating keeps them and rewrites the rest of this file.
package net.atos.tests.pages.industriesdetail;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import net.atos.tests.core.Headings;
import net.atos.tests.core.LocatorProvider;
import net.atos.tests.core.PageElement;
import net.atos.tests.uri.UrlPaths;
// ==== YOURS (imports): safe to edit; regenerating keeps what is between these lines ====
// ==== END YOURS (imports) ====

/**
 * Locators for a family of about 2 pages like /en/services/cybersecurity, /en/industries/healthcare-and-life-sciences.
 * Steps name each one by label(): SUBMIT_BUTTON is "the submit button"; a link the crawl saw, by its words.
 */
public enum IndustriesDetailElements implements PageElement {
    // Section headings the crawled pages of this type share. One a test does not use is harmless.
    /** Heading "How we make an impact": every crawled page of this type showed it; some spell it "How We Make an Impact". */
    HOW_WE_MAKE_AN_IMPACT_HEADING(page -> Headings.named(page, "How we make an impact", "How We Make an Impact")),
    /** Heading "Dive deeper": every crawled page of this type showed it; some spell it "Dive Deeper". */
    DIVE_DEEPER_HEADING(page -> Headings.named(page, "Dive deeper", "Dive Deeper")),
    /** Heading "Contact us for more information.": every crawled page of this type showed it. */
    CONTACT_US_FOR_MORE_INFORMATION_HEADING(page -> Headings.named(page, "Contact us for more information.")),

    // What every crawled page of this type has, whatever its words: proof it loaded that a copy edit leaves alone.
    /** The main region: each of its 2 pages read shows a main region. */
    MAIN_REGION(page -> page.locator("xpath=//main | //*[@role='main'] >> visible=true").first(), "the main region"),

    // Links to other pages (from the crawl).
    /** Link "Learn more >" (href https://atos.net/en/lp/digital-security-magazine-20th-edition) to LpDigitalSecurityMagazinePage, seen by the crawl on /en/services/cybersecurity. */
    LP_DIGITAL_SECURITY_MAGAZINE_LINK(page -> page.locator("xpath=//a[@href='/en/lp/digital-security-magazine-20th-edition' or (contains(@href, '//') and substring-after(substring-after(@href, '//'), '/')='en/lp/digital-security-magazine-20th-edition')] >> visible=true").first(), "\"Learn more >\""),
    /** Link "Learn more >" (href https://atos.net/en/lp/atos-threat-research-center) to LpAtosThreatResearchPage, seen by the crawl on /en/services/cybersecurity. */
    LP_ATOS_THREAT_RESEARCH_LINK(page -> page.locator("xpath=//a[@href='/en/lp/atos-threat-research-center' or (contains(@href, '//') and substring-after(substring-after(@href, '//'), '/')='en/lp/atos-threat-research-center')] >> visible=true").first(), "\"Learn more >\""),

    // In the page (from the crawl: nothing was typed, clicked or sent).
    /** button "previous arrow": seen by the crawl on /en/services/cybersecurity. */
    PREVIOUS_ARROW_BUTTON(page -> page.locator("xpath=//div[@aria-label='previous arrow']")),
    /** button "next arrow": seen by the crawl on /en/services/cybersecurity. */
    NEXT_ARROW_BUTTON(page -> page.locator("xpath=//div[@aria-label='next arrow']")),
    /** button "DSm 19": seen by the crawl on /en/services/cybersecurity. */
    DSM_19_BUTTON(page -> page.locator("xpath=//div[@aria-label='DSm 19']")),
    /** button "Adaptive cyber resilience wp": seen by the crawl on /en/services/cybersecurity. */
    ADAPTIVE_CYBER_RESILIENCE_WP_BUTTON(page -> page.locator("xpath=//div[@aria-label='Adaptive cyber resilience wp ']")),
    /** button "CYS main page": seen by the crawl on /en/services/cybersecurity. */
    CYS_MAIN_PAGE_BUTTON(page -> page.locator("xpath=//div[@aria-label='Choose slide to display.']//div[@aria-label='CYS main page']")),
    /** button "TRC": seen by the crawl on /en/services/cybersecurity. */
    TRC_BUTTON(page -> page.locator("xpath=//div[@aria-label='TRC']")),
    /** button "Previous slide (only for visual purpose, links already av...": seen by the crawl on /en/services/cybersecurity. */
    PREVIOUS_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Previous slide (only for visual purpose, links already available just before)']")),
    /** button "Next slide (only for visual purpose, links already availa...": seen by the crawl on /en/services/cybersecurity. */
    NEXT_SLIDE_ONLY_FOR_VISUAL_BUTTON(page -> page.locator("xpath=//div[@aria-label='Next slide (only for visual purpose, links already available just before)']")),
    /** button "previous slide": seen by the crawl on /en/industries/healthcare-and-life-sciences. */
    PREVIOUS_SLIDE_BUTTON(page -> page.locator("xpath=//div[@aria-label='previous slide']")),
    /** button "next slide": seen by the crawl on /en/industries/healthcare-and-life-sciences. */
    NEXT_SLIDE_BUTTON(page -> page.locator("xpath=//div[@aria-label='next slide']")),
    /** button "Solent NHS Trust": seen by the crawl on /en/industries/healthcare-and-life-sciences. */
    SOLENT_NHS_TRUST_BUTTON(page -> page.locator("xpath=//div[@aria-label='Solent NHS Trust']")),
    /** button "CPI": seen by the crawl on /en/industries/healthcare-and-life-sciences. */
    CPI_BUTTON(page -> page.locator("xpath=//div[@aria-label='CPI']")),

    // ==== YOURS (elements): safe to edit; regenerating keeps what is between these lines ====
    // This page's own elements (see ai/recipes/add-an-element.md). Selector Grabber's locators
    // paste straight in, e.g.:
    // SUBMIT_BUTTON(page -> page.locator("xpath=//button[@data-testid='submit']")),
    // ==== END YOURS (elements) ====
    ;

    private final LocatorProvider provider;
    private final String label;

    IndustriesDetailElements(LocatorProvider provider) {
        this(provider, null);
    }

    /** One that steps name by its words on the page ("About"), not by its constant's name. */
    IndustriesDetailElements(LocatorProvider provider, String label) {
        this.provider = provider;
        this.label = label;
    }

    @Override
    public Locator locator(Page page) {
        return provider.get(page);
    }

    @Override
    public String label() {
        return label != null ? label : PageElement.super.label();
    }

    /** A link to SiteDetailPage8, e.g. https://atos.net/en/2025/awards_2025_04_08/atos-named-2025-google-cloud-social-impact-partner-of-the-year-for-crisis-response-and-resilience#:~:text=Paris%2C%20France%20%E2%80%93%20April%208%2C,collaborative%20responses%20and%20prevention%20efforts.. */
    public static PageElement getSiteDetail8Link(String id, String name, String name2) {
        String href = "/en/" + id + "/" + name + "/" + name2 + "#:~:text=Paris%2C%20France%20%E2%80%93%20April%208%2C,collaborative%20responses%20and%20prevention%20efforts.";
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("SITE_DETAIL8_LINK", "the link to the site detail page8 \"" + id + "/" + name + "/" + name2 + "\"", page -> page.locator(xpath).first());
    }

    /** A link to ClientSuccessClientStoriesDetailPage, e.g. https://atos.net/en/client-stories/securing-the-olympic-and-paralympic-games-paris-2024. */
    public static PageElement getClientSuccessClientStoriesDetailLink(String name) {
        String href = name + "/en/client-stories/securing-the-olympic-and-paralympic-games-paris-2024";
        // Written encoded ("Mast%20&%20Harbour") or not ("Mast & Harbour"): sites do both.
        String xpath = "xpath=//a[@href=" + Headings.literal(href) + " or @href=" + Headings.literal(UrlPaths.decoded(href)) + " or (contains(@href, '//') and (substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(href.substring(1)) + " or substring-after(substring-after(@href, '//'), '/')=" + Headings.literal(UrlPaths.decoded(href).substring(1)) + "))] >> visible=true";
        return PageElement.of("CLIENT_SUCCESS_CLIENT_STORIES_DETAIL_LINK", "the link to the client success client stories detail page \"" + name + "\"", page -> page.locator(xpath).first());
    }

    // ==== YOURS (extras): safe to edit; regenerating keeps what is between these lines ====
    // Elements that take a parameter (one row of a table, say), clicked with UserActions.click(page, ...), e.g.:
    // public static PageElement getResultLink(String name) {
    //     String xpath = "xpath=//a[normalize-space()=" + Headings.literal(name) + "]";
    //     return PageElement.of("RESULT_LINK", "the result " + name, page -> page.locator(xpath).first());
    // }
    // ==== END YOURS (extras) ====
}
